// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attachments.sql

package commsdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAttachmentReferences = `-- name: GetAttachmentReferences :many

SELECT
    a.channel_id,
    c.name AS channel_name,
    a.message_id,
    m.thread_id,
    m.sender_id,
    m.content AS message_content,
    m.created_at AS message_created_at,
    a.created_at AS attachment_created_at
FROM comms_attachments a
JOIN comms_messages m ON a.message_id = m.id
JOIN comms_channels c ON a.channel_id = c.id
JOIN comms_channel_participants cp ON cp.channel_id = c.id
WHERE a.entity_type = $1
  AND a.entity_id  = $2
  AND cp.user_id   = $3
  AND cp.left_at  IS NULL
  AND m.deleted_at IS NULL
ORDER BY a.created_at DESC
`

type GetAttachmentReferencesParams struct {
	EntityType string
	EntityID   string
	UserID     string
}

type GetAttachmentReferencesRow struct {
	ChannelID           pgtype.UUID
	ChannelName         pgtype.Text
	MessageID           pgtype.UUID
	ThreadID            pgtype.UUID
	SenderID            string
	MessageContent      string
	MessageCreatedAt    pgtype.Timestamptz
	AttachmentCreatedAt pgtype.Timestamptz
}

// Queries ported from crates/comms_db_client/src/attachments/get_attachment_references.rs
// The Rust function runs all three concurrently and merges/sorts in memory.
// Channel references where the entity was attached to a message in a channel
// the given user is an active participant of.
func (q *Queries) GetAttachmentReferences(ctx context.Context, arg GetAttachmentReferencesParams) ([]GetAttachmentReferencesRow, error) {
	rows, err := q.db.Query(ctx, getAttachmentReferences, arg.EntityType, arg.EntityID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAttachmentReferencesRow
	for rows.Next() {
		var i GetAttachmentReferencesRow
		if err := rows.Scan(
			&i.ChannelID,
			&i.ChannelName,
			&i.MessageID,
			&i.ThreadID,
			&i.SenderID,
			&i.MessageContent,
			&i.MessageCreatedAt,
			&i.AttachmentCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGenericEntityMentionReferences = `-- name: GetGenericEntityMentionReferences :many
SELECT
    em.source_entity_type,
    em.source_entity_id,
    em.entity_type,
    em.entity_id,
    em.user_id,
    em.created_at
FROM comms_entity_mentions em
WHERE em.entity_type = $1
  AND em.entity_id  = $2
  AND em.source_entity_type != 'message'
ORDER BY em.created_at DESC
`

type GetGenericEntityMentionReferencesParams struct {
	EntityType string
	EntityID   string
}

type GetGenericEntityMentionReferencesRow struct {
	SourceEntityType string
	SourceEntityID   string
	EntityType       string
	EntityID         string
	UserID           pgtype.Text
	CreatedAt        pgtype.Timestamptz
}

// Mentions of the entity from non-message sources (no access check upstream).
func (q *Queries) GetGenericEntityMentionReferences(ctx context.Context, arg GetGenericEntityMentionReferencesParams) ([]GetGenericEntityMentionReferencesRow, error) {
	rows, err := q.db.Query(ctx, getGenericEntityMentionReferences, arg.EntityType, arg.EntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGenericEntityMentionReferencesRow
	for rows.Next() {
		var i GetGenericEntityMentionReferencesRow
		if err := rows.Scan(
			&i.SourceEntityType,
			&i.SourceEntityID,
			&i.EntityType,
			&i.EntityID,
			&i.UserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMentionReferences = `-- name: GetMentionReferences :many
SELECT
    m.channel_id,
    c.name AS channel_name,
    m.id AS message_id,
    m.thread_id,
    m.sender_id,
    m.content AS message_content,
    m.created_at AS message_created_at,
    em.created_at AS attachment_created_at
FROM comms_entity_mentions em
JOIN comms_messages m ON (em.source_entity_id = m.id::text AND em.source_entity_type = 'message')
JOIN comms_channels c ON m.channel_id = c.id
JOIN comms_channel_participants cp ON cp.channel_id = c.id
WHERE em.entity_type = $1
  AND em.entity_id  = $2
  AND cp.user_id   = $3
  AND cp.left_at  IS NULL
  AND m.deleted_at IS NULL
ORDER BY em.created_at DESC
`

type GetMentionReferencesParams struct {
	EntityType string
	EntityID   string
	UserID     string
}

type GetMentionReferencesRow struct {
	ChannelID           pgtype.UUID
	ChannelName         pgtype.Text
	MessageID           pgtype.UUID
	ThreadID            pgtype.UUID
	SenderID            string
	MessageContent      string
	MessageCreatedAt    pgtype.Timestamptz
	AttachmentCreatedAt pgtype.Timestamptz
}

// Channel references where the entity was mentioned inside a message.
func (q *Queries) GetMentionReferences(ctx context.Context, arg GetMentionReferencesParams) ([]GetMentionReferencesRow, error) {
	rows, err := q.db.Query(ctx, getMentionReferences, arg.EntityType, arg.EntityID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMentionReferencesRow
	for rows.Next() {
		var i GetMentionReferencesRow
		if err := rows.Scan(
			&i.ChannelID,
			&i.ChannelName,
			&i.MessageID,
			&i.ThreadID,
			&i.SenderID,
			&i.MessageContent,
			&i.MessageCreatedAt,
			&i.AttachmentCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
