// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: channels.sql

package commsdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addChannelParticipant = `-- name: AddChannelParticipant :exec
INSERT INTO comms_channel_participants (channel_id, role, user_id)
VALUES ($1, $2, $3)
`

type AddChannelParticipantParams struct {
	ChannelID pgtype.UUID
	Role      CommsParticipantRole
	UserID    string
}

// Covers the owner/member inserts inside create_channel/seed_channel as well
// as participants::add_participant (role comes from the caller).
func (q *Queries) AddChannelParticipant(ctx context.Context, arg AddChannelParticipantParams) error {
	_, err := q.db.Exec(ctx, addChannelParticipant, arg.ChannelID, arg.Role, arg.UserID)
	return err
}

const checkChannelsForUser = `-- name: CheckChannelsForUser :many
SELECT c.id
FROM comms_channels c
INNER JOIN comms_channel_participants cp ON cp.channel_id = c.id
WHERE cp.user_id = $1 AND cp.left_at IS NULL
AND c.id = ANY($2::uuid[])
`

type CheckChannelsForUserParams struct {
	UserID     string
	ChannelIds []pgtype.UUID
}

// Channels from the given list the user is an active participant of.
func (q *Queries) CheckChannelsForUser(ctx context.Context, arg CheckChannelsForUserParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, checkChannelsForUser, arg.UserID, arg.ChannelIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllChannelIDsPaginated = `-- name: GetAllChannelIDsPaginated :many
SELECT
    id AS channel_id
FROM comms_channels
ORDER BY created_at ASC
LIMIT $1
OFFSET $2
`

type GetAllChannelIDsPaginatedParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) GetAllChannelIDsPaginated(ctx context.Context, arg GetAllChannelIDsPaginatedParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, getAllChannelIDsPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var channel_id pgtype.UUID
		if err := rows.Scan(&channel_id); err != nil {
			return nil, err
		}
		items = append(items, channel_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserChannelIDs = `-- name: GetUserChannelIDs :many
WITH user_channels AS (
    SELECT DISTINCT c.id, c.created_at
    FROM comms_channels c
    INNER JOIN comms_channel_participants cp ON cp.channel_id = c.id
    WHERE cp.user_id = $1 AND cp.left_at IS NULL
)
SELECT id
FROM user_channels
ORDER BY created_at DESC
`

func (q *Queries) GetUserChannelIDs(ctx context.Context, userID string) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, getUserChannelIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertChannel = `-- name: InsertChannel :one

INSERT INTO comms_channels (id, name, owner_id, org_id, team_id, channel_type)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type InsertChannelParams struct {
	ID          pgtype.UUID
	Name        pgtype.Text
	OwnerID     string
	OrgID       pgtype.Int8
	TeamID      pgtype.UUID
	ChannelType CommsChannelType
}

// Queries ported from crates/comms_db_client/src/channels/
// Covers both create_channel (uuid generated by caller) and seed_channel
// (caller supplies the id) -- the SQL is identical.
func (q *Queries) InsertChannel(ctx context.Context, arg InsertChannelParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertChannel,
		arg.ID,
		arg.Name,
		arg.OwnerID,
		arg.OrgID,
		arg.TeamID,
		arg.ChannelType,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
