// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: entity_mentions.sql

package commsdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEntityMentions = `-- name: CreateEntityMentions :execrows

INSERT INTO comms_entity_mentions (id, source_entity_type, source_entity_id, entity_type, entity_id, user_id)
SELECT a.id, $1, $2, b.entity_type, c.entity_id, $3
FROM UNNEST($4::uuid[]) WITH ORDINALITY AS a(id, ord)
JOIN UNNEST($5::varchar[]) WITH ORDINALITY AS b(entity_type, ord) ON b.ord = a.ord
JOIN UNNEST($6::varchar[]) WITH ORDINALITY AS c(entity_id, ord) ON c.ord = a.ord
`

type CreateEntityMentionsParams struct {
	SourceEntityType string
	SourceEntityID   string
	UserID           pgtype.Text
	Ids              []pgtype.UUID
	EntityTypes      []string
	EntityIds        []string
}

// Queries ported from crates/comms_db_client/src/entity_mentions/
// Bulk insert from parallel arrays. The Rust version built per-row copies of
// source_entity_type/source_entity_id/user_id and passed a 6-array UNNEST;
// sqlc only supports single-array UNNEST so the uniform values are scalar
// params joined by ordinality (identical semantics).
func (q *Queries) CreateEntityMentions(ctx context.Context, arg CreateEntityMentionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, createEntityMentions,
		arg.SourceEntityType,
		arg.SourceEntityID,
		arg.UserID,
		arg.Ids,
		arg.EntityTypes,
		arg.EntityIds,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteEntityMentionsBySource = `-- name: DeleteEntityMentionsBySource :execrows
DELETE FROM comms_entity_mentions
WHERE source_entity_id = ANY($1::varchar[])
`

func (q *Queries) DeleteEntityMentionsBySource(ctx context.Context, sourceEntityIds []string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEntityMentionsBySource, sourceEntityIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
