// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package commsdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMessage = `-- name: CreateMessage :one

INSERT INTO comms_messages (id, channel_id, sender_id, content, thread_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING
    id,
    channel_id,
    sender_id,
    content,
    created_at,
    updated_at,
    thread_id,
    edited_at,
    deleted_at
`

type CreateMessageParams struct {
	ID        pgtype.UUID
	ChannelID pgtype.UUID
	SenderID  string
	Content   string
	ThreadID  pgtype.UUID
}

type CreateMessageRow struct {
	ID        pgtype.UUID
	ChannelID pgtype.UUID
	SenderID  string
	Content   string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	ThreadID  pgtype.UUID
	EditedAt  pgtype.Timestamp
	DeletedAt pgtype.Timestamp
}

// Queries ported from crates/comms_db_client/src/messages/
// Covers both create_message (caller generates uuid v7) and seed_message
// (caller supplies the id) -- the SQL is identical.
func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (CreateMessageRow, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.ID,
		arg.ChannelID,
		arg.SenderID,
		arg.Content,
		arg.ThreadID,
	)
	var i CreateMessageRow
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.SenderID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ThreadID,
		&i.EditedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createMessageMentions = `-- name: CreateMessageMentions :many
WITH message_channel AS (
    SELECT comms_messages.channel_id FROM comms_messages WHERE comms_messages.id = $1
),
mentions_to_insert AS (
    -- sqlc only supports single-array UNNEST; pair by ordinality.
    SELECT et.entity_type, ei.entity_id
    FROM UNNEST($2::text[]) WITH ORDINALITY AS et(entity_type, ord)
    JOIN UNNEST($3::text[]) WITH ORDINALITY AS ei(entity_id, ord) ON ei.ord = et.ord
),
inserted_mentions AS (
    INSERT INTO comms_entity_mentions (id, source_entity_type, source_entity_id, entity_type, entity_id, user_id)
    SELECT gen_random_uuid(), 'message', $1::text, m.entity_type, m.entity_id, NULL
    FROM mentions_to_insert m
    WHERE NOT EXISTS (
        SELECT 1 FROM comms_entity_mentions em
        WHERE em.source_entity_type = 'message'
          AND em.source_entity_id = $1::text
          AND em.entity_type = m.entity_type
          AND em.entity_id = m.entity_id
    )
)
SELECT DISTINCT cp.user_id
FROM mentions_to_insert m
CROSS JOIN message_channel mc
JOIN comms_channel_participants cp ON m.entity_id = cp.user_id
WHERE m.entity_type = 'user'
AND cp.channel_id = mc.channel_id
AND cp.left_at IS NULL
`

type CreateMessageMentionsParams struct {
	MessageID   pgtype.UUID
	EntityTypes []string
	EntityIds   []string
}

// Inserts message entity mentions (deduped) and returns the user_ids of
// mentioned users that are active participants of the message's channel.
func (q *Queries) CreateMessageMentions(ctx context.Context, arg CreateMessageMentionsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, createMessageMentions, arg.MessageID, arg.EntityTypes, arg.EntityIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var user_id string
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChannelMessage = `-- name: GetChannelMessage :one
SELECT
    c.id AS channel_id,
    c.name AS name,
    c.channel_type,
    c.org_id,
    m.id AS message_id,
    m.thread_id,
    m.sender_id,
    m.content,
    m.created_at,
    m.updated_at,
    m.deleted_at::timestamptz AS deleted_at
FROM comms_messages m
JOIN comms_channels c ON c."id" = m."channel_id"
WHERE m.id = $1 AND c.id = $2
`

type GetChannelMessageParams struct {
	ID   pgtype.UUID
	ID_2 pgtype.UUID
}

type GetChannelMessageRow struct {
	ChannelID   pgtype.UUID
	Name        pgtype.Text
	ChannelType CommsChannelType
	OrgID       pgtype.Int8
	MessageID   pgtype.UUID
	ThreadID    pgtype.UUID
	SenderID    string
	Content     string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

// Channel + message info used to populate channel messages for search.
func (q *Queries) GetChannelMessage(ctx context.Context, arg GetChannelMessageParams) (GetChannelMessageRow, error) {
	row := q.db.QueryRow(ctx, getChannelMessage, arg.ID, arg.ID_2)
	var i GetChannelMessageRow
	err := row.Scan(
		&i.ChannelID,
		&i.Name,
		&i.ChannelType,
		&i.OrgID,
		&i.MessageID,
		&i.ThreadID,
		&i.SenderID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getChannelMessages = `-- name: GetChannelMessages :many
SELECT
    channel_id,
    id
FROM comms_messages
WHERE channel_id IS NOT NULL
AND (
    $1::bool IS NULL
    OR ($1 AND deleted_at IS NOT NULL)
    OR (NOT $1 AND deleted_at IS NULL)
)
ORDER BY created_at ASC
LIMIT $3
OFFSET $2
`

type GetChannelMessagesParams struct {
	OnlyDeleted pgtype.Bool
	RowOffset   int32
	RowLimit    int32
}

type GetChannelMessagesRow struct {
	ChannelID pgtype.UUID
	ID        pgtype.UUID
}

// Paginated (channel_id, message_id) pairs for search backfill.
// `only_deleted` tri-state: NULL = all, true = only deleted, false = only active.
func (q *Queries) GetChannelMessages(ctx context.Context, arg GetChannelMessagesParams) ([]GetChannelMessagesRow, error) {
	rows, err := q.db.Query(ctx, getChannelMessages, arg.OnlyDeleted, arg.RowOffset, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetChannelMessagesRow
	for rows.Next() {
		var i GetChannelMessagesRow
		if err := rows.Scan(&i.ChannelID, &i.ID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessageDeletionStates = `-- name: GetMessageDeletionStates :many
SELECT
    id,
    deleted_at::timestamptz AS deleted_at
FROM comms_messages
WHERE id = ANY($1::uuid[])
`

type GetMessageDeletionStatesRow struct {
	ID        pgtype.UUID
	DeletedAt pgtype.Timestamptz
}

func (q *Queries) GetMessageDeletionStates(ctx context.Context, messageIds []pgtype.UUID) ([]GetMessageDeletionStatesRow, error) {
	rows, err := q.db.Query(ctx, getMessageDeletionStates, messageIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMessageDeletionStatesRow
	for rows.Next() {
		var i GetMessageDeletionStatesRow
		if err := rows.Scan(&i.ID, &i.DeletedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessageMentionEntities = `-- name: GetMessageMentionEntities :many
SELECT
    entity_type,
    entity_id
FROM comms_entity_mentions
WHERE source_entity_id = $1 AND source_entity_type = 'message'
`

type GetMessageMentionEntitiesRow struct {
	EntityType string
	EntityID   string
}

// entity_type/entity_id pairs mentioned by a message (SimpleMention list).
func (q *Queries) GetMessageMentionEntities(ctx context.Context, messageID string) ([]GetMessageMentionEntitiesRow, error) {
	rows, err := q.db.Query(ctx, getMessageMentionEntities, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMessageMentionEntitiesRow
	for rows.Next() {
		var i GetMessageMentionEntitiesRow
		if err := rows.Scan(&i.EntityType, &i.EntityID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessages = `-- name: GetMessages :many
SELECT
    id,
    channel_id,
    sender_id,
    content,
    created_at,
    updated_at,
    thread_id,
    edited_at,
    deleted_at
FROM (
    SELECT id, channel_id, thread_id, sender_id, content, created_at, updated_at, edited_at, deleted_at, triggered_by_user_id, parent_entity_type, parent_entity_id, imported_author, import_metadata, import_order
    FROM comms_messages
    WHERE channel_id = $1
    AND ($2::timestamptz IS NULL OR created_at >= $2)
    ORDER BY created_at DESC
    LIMIT $3::bigint
) AS latest_messages
ORDER BY created_at ASC
`

type GetMessagesParams struct {
	ChannelID    pgtype.UUID
	Since        pgtype.Timestamptz
	MessageLimit pgtype.Int8
}

type GetMessagesRow struct {
	ID        pgtype.UUID
	ChannelID pgtype.UUID
	SenderID  string
	Content   string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	ThreadID  pgtype.UUID
	EditedAt  pgtype.Timestamp
	DeletedAt pgtype.Timestamp
}

// Latest messages for a channel: most recent first, capped, then re-ordered
// ascending. `since`/`message_limit` may be NULL (no filter / no limit).
func (q *Queries) GetMessages(ctx context.Context, arg GetMessagesParams) ([]GetMessagesRow, error) {
	rows, err := q.db.Query(ctx, getMessages, arg.ChannelID, arg.Since, arg.MessageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMessagesRow
	for rows.Next() {
		var i GetMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.SenderID,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ThreadID,
			&i.EditedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
