// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: channel_notification_email_sent.sql

package notifdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteChannelNotificationEmailSent = `-- name: DeleteChannelNotificationEmailSent :exec

DELETE FROM channel_notification_email_sent
WHERE channel_id = $1 AND user_id = $2
`

type DeleteChannelNotificationEmailSentParams struct {
	ChannelID pgtype.UUID
	UserID    string
}

// Queries ported from crates/notification_db_client/src/channel_notification_email_sent/
func (q *Queries) DeleteChannelNotificationEmailSent(ctx context.Context, arg DeleteChannelNotificationEmailSentParams) error {
	_, err := q.db.Exec(ctx, deleteChannelNotificationEmailSent, arg.ChannelID, arg.UserID)
	return err
}

const deleteChannelNotificationEmailSentByNotificationIDs = `-- name: DeleteChannelNotificationEmailSentByNotificationIDs :exec
DELETE FROM channel_notification_email_sent
USING notification n
WHERE n.id = ANY($1::uuid[])
AND n.event_item_type = 'channel'
AND channel_notification_email_sent.channel_id = n.event_item_id::uuid
AND channel_notification_email_sent.user_id = $2
`

type DeleteChannelNotificationEmailSentByNotificationIDsParams struct {
	NotificationIds []pgtype.UUID
	UserID          string
}

func (q *Queries) DeleteChannelNotificationEmailSentByNotificationIDs(ctx context.Context, arg DeleteChannelNotificationEmailSentByNotificationIDsParams) error {
	_, err := q.db.Exec(ctx, deleteChannelNotificationEmailSentByNotificationIDs, arg.NotificationIds, arg.UserID)
	return err
}

const getChannelNotificationEmailSentBulk = `-- name: GetChannelNotificationEmailSentBulk :many
SELECT channel_id, user_id, created_at
FROM channel_notification_email_sent
WHERE channel_id = $1
AND user_id = ANY($2::text[])
`

type GetChannelNotificationEmailSentBulkParams struct {
	ChannelID pgtype.UUID
	UserIds   []string
}

func (q *Queries) GetChannelNotificationEmailSentBulk(ctx context.Context, arg GetChannelNotificationEmailSentBulkParams) ([]ChannelNotificationEmailSent, error) {
	rows, err := q.db.Query(ctx, getChannelNotificationEmailSentBulk, arg.ChannelID, arg.UserIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChannelNotificationEmailSent
	for rows.Next() {
		var i ChannelNotificationEmailSent
		if err := rows.Scan(&i.ChannelID, &i.UserID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChannelNotificationEmailSentBulkByChannelIDs = `-- name: GetChannelNotificationEmailSentBulkByChannelIDs :many
SELECT channel_id
FROM channel_notification_email_sent
WHERE user_id = $1
AND channel_id = ANY($2::uuid[])
`

type GetChannelNotificationEmailSentBulkByChannelIDsParams struct {
	UserID     string
	ChannelIds []pgtype.UUID
}

func (q *Queries) GetChannelNotificationEmailSentBulkByChannelIDs(ctx context.Context, arg GetChannelNotificationEmailSentBulkByChannelIDsParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, getChannelNotificationEmailSentBulkByChannelIDs, arg.UserID, arg.ChannelIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var channel_id pgtype.UUID
		if err := rows.Scan(&channel_id); err != nil {
			return nil, err
		}
		items = append(items, channel_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertChannelNotificationEmailSentBulk = `-- name: UpsertChannelNotificationEmailSentBulk :exec
INSERT INTO channel_notification_email_sent (channel_id, user_id)
SELECT $1, u FROM UNNEST($2::text[]) AS u
ON CONFLICT (channel_id, user_id) DO NOTHING
`

type UpsertChannelNotificationEmailSentBulkParams struct {
	ChannelID pgtype.UUID
	UserIds   []string
}

func (q *Queries) UpsertChannelNotificationEmailSentBulk(ctx context.Context, arg UpsertChannelNotificationEmailSentBulkParams) error {
	_, err := q.db.Exec(ctx, upsertChannelNotificationEmailSentBulk, arg.ChannelID, arg.UserIds)
	return err
}

const upsertChannelNotificationEmailSentBulkChannelIDs = `-- name: UpsertChannelNotificationEmailSentBulkChannelIDs :exec
INSERT INTO channel_notification_email_sent (user_id, channel_id)
SELECT $1, c FROM UNNEST($2::uuid[]) AS c
ON CONFLICT (channel_id, user_id) DO NOTHING
`

type UpsertChannelNotificationEmailSentBulkChannelIDsParams struct {
	UserID     string
	ChannelIds []pgtype.UUID
}

func (q *Queries) UpsertChannelNotificationEmailSentBulkChannelIDs(ctx context.Context, arg UpsertChannelNotificationEmailSentBulkChannelIDsParams) error {
	_, err := q.db.Exec(ctx, upsertChannelNotificationEmailSentBulkChannelIDs, arg.UserID, arg.ChannelIds)
	return err
}
