// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: devices.sql

package notifdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteUserDeviceByEndpoint = `-- name: DeleteUserDeviceByEndpoint :exec
DELETE FROM notification_user_device_registration
WHERE device_endpoint = $1
`

func (q *Queries) DeleteUserDeviceByEndpoint(ctx context.Context, deviceEndpoint string) error {
	_, err := q.db.Exec(ctx, deleteUserDeviceByEndpoint, deviceEndpoint)
	return err
}

const deleteUserDeviceToken = `-- name: DeleteUserDeviceToken :one
DELETE FROM notification_user_device_registration
WHERE device_token = $1 AND device_type = $2
RETURNING device_endpoint
`

type DeleteUserDeviceTokenParams struct {
	DeviceToken string
	DeviceType  NotificationDeviceTypeOption
}

func (q *Queries) DeleteUserDeviceToken(ctx context.Context, arg DeleteUserDeviceTokenParams) (string, error) {
	row := q.db.QueryRow(ctx, deleteUserDeviceToken, arg.DeviceToken, arg.DeviceType)
	var device_endpoint string
	err := row.Scan(&device_endpoint)
	return device_endpoint, err
}

const getDeviceEndpoint = `-- name: GetDeviceEndpoint :one

SELECT d.device_endpoint
FROM notification_user_device_registration d
WHERE d.device_token = $1
LIMIT 1
`

// Queries ported from crates/notification_db_client/src/device.rs
// Rust used fetch_optional: callers must treat pgx.ErrNoRows as "no device".
func (q *Queries) GetDeviceEndpoint(ctx context.Context, deviceToken string) (string, error) {
	row := q.db.QueryRow(ctx, getDeviceEndpoint, deviceToken)
	var device_endpoint string
	err := row.Scan(&device_endpoint)
	return device_endpoint, err
}

const getUserDeviceEndpoints = `-- name: GetUserDeviceEndpoints :many
SELECT d.device_endpoint
FROM notification_user_device_registration d
WHERE d.user_id = $1
`

func (q *Queries) GetUserDeviceEndpoints(ctx context.Context, userID string) ([]string, error) {
	rows, err := q.db.Query(ctx, getUserDeviceEndpoints, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var device_endpoint string
		if err := rows.Scan(&device_endpoint); err != nil {
			return nil, err
		}
		items = append(items, device_endpoint)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersDeviceEndpoints = `-- name: GetUsersDeviceEndpoints :many
SELECT d.device_endpoint,
       d.user_id,
       d.device_type
FROM notification_user_device_registration d
WHERE d.user_id = ANY($1::text[])
`

type GetUsersDeviceEndpointsRow struct {
	DeviceEndpoint string
	UserID         string
	DeviceType     NotificationDeviceTypeOption
}

func (q *Queries) GetUsersDeviceEndpoints(ctx context.Context, userIds []string) ([]GetUsersDeviceEndpointsRow, error) {
	rows, err := q.db.Query(ctx, getUsersDeviceEndpoints, userIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsersDeviceEndpointsRow
	for rows.Next() {
		var i GetUsersDeviceEndpointsRow
		if err := rows.Scan(&i.DeviceEndpoint, &i.UserID, &i.DeviceType); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUserDevice = `-- name: UpsertUserDevice :exec
INSERT INTO notification_user_device_registration (id, user_id, device_token, device_endpoint, device_type)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (device_endpoint) DO UPDATE SET user_id = $2, device_token = $3, device_type = $5, updated_at = NOW()
`

type UpsertUserDeviceParams struct {
	ID             pgtype.UUID
	UserID         string
	DeviceToken    string
	DeviceEndpoint string
	DeviceType     NotificationDeviceTypeOption
}

// id is a uuid v7 generated by the caller (as in the Rust code).
func (q *Queries) UpsertUserDevice(ctx context.Context, arg UpsertUserDeviceParams) error {
	_, err := q.db.Exec(ctx, upsertUserDevice,
		arg.ID,
		arg.UserID,
		arg.DeviceToken,
		arg.DeviceEndpoint,
		arg.DeviceType,
	)
	return err
}
