// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notification.sql

package notifdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteNotificationByEventItem = `-- name: DeleteNotificationByEventItem :exec

DELETE FROM notification
WHERE event_item_id = $1 AND event_item_type = $2
`

type DeleteNotificationByEventItemParams struct {
	EventItemID   string
	EventItemType string
}

// Queries ported from crates/notification_db_client/src/notification/
// (mod.rs + delete.rs share delete_notification_by_event_item; get.rs has the
// basic-notification fetch and collapse-key update.)
func (q *Queries) DeleteNotificationByEventItem(ctx context.Context, arg DeleteNotificationByEventItemParams) error {
	_, err := q.db.Exec(ctx, deleteNotificationByEventItem, arg.EventItemID, arg.EventItemType)
	return err
}

const getBasicNotification = `-- name: GetBasicNotification :one
SELECT
    n.event_item_id,
    n.event_item_type,
    n.notification_event_type,
    n.apns_collapse_key
FROM notification n
WHERE n.id = $1
`

type GetBasicNotificationRow struct {
	EventItemID           string
	EventItemType         string
	NotificationEventType string
	ApnsCollapseKey       pgtype.Text
}

func (q *Queries) GetBasicNotification(ctx context.Context, id pgtype.UUID) (GetBasicNotificationRow, error) {
	row := q.db.QueryRow(ctx, getBasicNotification, id)
	var i GetBasicNotificationRow
	err := row.Scan(
		&i.EventItemID,
		&i.EventItemType,
		&i.NotificationEventType,
		&i.ApnsCollapseKey,
	)
	return i, err
}

const updateCollapseKey = `-- name: UpdateCollapseKey :one
UPDATE notification
SET apns_collapse_key = $2
WHERE id = $1
RETURNING
    event_item_id,
    event_item_type,
    notification_event_type,
    apns_collapse_key
`

type UpdateCollapseKeyParams struct {
	ID              pgtype.UUID
	ApnsCollapseKey pgtype.Text
}

type UpdateCollapseKeyRow struct {
	EventItemID           string
	EventItemType         string
	NotificationEventType string
	ApnsCollapseKey       pgtype.Text
}

func (q *Queries) UpdateCollapseKey(ctx context.Context, arg UpdateCollapseKeyParams) (UpdateCollapseKeyRow, error) {
	row := q.db.QueryRow(ctx, updateCollapseKey, arg.ID, arg.ApnsCollapseKey)
	var i UpdateCollapseKeyRow
	err := row.Scan(
		&i.EventItemID,
		&i.EventItemType,
		&i.NotificationEventType,
		&i.ApnsCollapseKey,
	)
	return i, err
}
