// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: unsubscribe.sql

package notifdb

import (
	"context"
)

const getUnsubscribedItemUsers = `-- name: GetUnsubscribedItemUsers :many
SELECT u.user_id
FROM user_notification_item_unsubscribe u
WHERE u.item_id = $1
`

func (q *Queries) GetUnsubscribedItemUsers(ctx context.Context, itemID string) ([]string, error) {
	rows, err := q.db.Query(ctx, getUnsubscribedItemUsers, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var user_id string
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserUnsubscribes = `-- name: GetUserUnsubscribes :many
SELECT
    unsubscribe_item.item_id,
    unsubscribe_item.item_type
FROM user_notification_item_unsubscribe unsubscribe_item
WHERE unsubscribe_item.user_id = $1
`

type GetUserUnsubscribesRow struct {
	ItemID   string
	ItemType string
}

func (q *Queries) GetUserUnsubscribes(ctx context.Context, userID string) ([]GetUserUnsubscribesRow, error) {
	rows, err := q.db.Query(ctx, getUserUnsubscribes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserUnsubscribesRow
	for rows.Next() {
		var i GetUserUnsubscribesRow
		if err := rows.Scan(&i.ItemID, &i.ItemType); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isEmailUnsubscribedBatch = `-- name: IsEmailUnsubscribedBatch :many

SELECT t.email::text AS email,
       EXISTS(SELECT 1 FROM notification_email_unsubscribe u WHERE u.email = t.email) AS is_unsubscribed
FROM UNNEST($1::text[]) AS t(email)
`

type IsEmailUnsubscribedBatchRow struct {
	Email          string
	IsUnsubscribed bool
}

// Queries ported from crates/notification_db_client/src/unsubscribe/
// Callers must lowercase emails before calling (Rust did it in-code).
func (q *Queries) IsEmailUnsubscribedBatch(ctx context.Context, emails []string) ([]IsEmailUnsubscribedBatchRow, error) {
	rows, err := q.db.Query(ctx, isEmailUnsubscribedBatch, emails)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IsEmailUnsubscribedBatchRow
	for rows.Next() {
		var i IsEmailUnsubscribedBatchRow
		if err := rows.Scan(&i.Email, &i.IsUnsubscribed); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeEmailUnsubscribe = `-- name: RemoveEmailUnsubscribe :exec
DELETE FROM notification_email_unsubscribe WHERE email = $1
`

func (q *Queries) RemoveEmailUnsubscribe(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, removeEmailUnsubscribe, email)
	return err
}

const removeUnsubscribedItemUser = `-- name: RemoveUnsubscribedItemUser :exec
DELETE FROM user_notification_item_unsubscribe
WHERE user_id = $1 AND item_id = $2
`

type RemoveUnsubscribedItemUserParams struct {
	UserID string
	ItemID string
}

func (q *Queries) RemoveUnsubscribedItemUser(ctx context.Context, arg RemoveUnsubscribedItemUserParams) error {
	_, err := q.db.Exec(ctx, removeUnsubscribedItemUser, arg.UserID, arg.ItemID)
	return err
}

const upsertEmailUnsubscribe = `-- name: UpsertEmailUnsubscribe :exec
INSERT INTO notification_email_unsubscribe (email) VALUES ($1)
ON CONFLICT (email) DO NOTHING
`

func (q *Queries) UpsertEmailUnsubscribe(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, upsertEmailUnsubscribe, email)
	return err
}

const upsertUnsubscribedItemUser = `-- name: UpsertUnsubscribedItemUser :exec
INSERT INTO user_notification_item_unsubscribe (user_id, item_id, item_type)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, item_id) DO NOTHING
`

type UpsertUnsubscribedItemUserParams struct {
	UserID   string
	ItemID   string
	ItemType string
}

func (q *Queries) UpsertUnsubscribedItemUser(ctx context.Context, arg UpsertUnsubscribedItemUserParams) error {
	_, err := q.db.Exec(ctx, upsertUnsubscribedItemUser, arg.UserID, arg.ItemID, arg.ItemType)
	return err
}
