// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_mute.sql

package notifdb

import (
	"context"
)

const getUserMuteNotificationBulk = `-- name: GetUserMuteNotificationBulk :many
SELECT user_id FROM user_mute_notification
WHERE user_id = ANY($1::text[])
`

func (q *Queries) GetUserMuteNotificationBulk(ctx context.Context, userIds []string) ([]string, error) {
	rows, err := q.db.Query(ctx, getUserMuteNotificationBulk, userIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var user_id string
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeUserMuteNotification = `-- name: RemoveUserMuteNotification :exec

DELETE FROM user_mute_notification WHERE user_id = $1
`

// Queries ported from crates/notification_db_client/src/user_mute_notification.rs
func (q *Queries) RemoveUserMuteNotification(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, removeUserMuteNotification, userID)
	return err
}

const upsertUserMuteNotification = `-- name: UpsertUserMuteNotification :exec
INSERT INTO user_mute_notification (user_id) VALUES ($1)
ON CONFLICT (user_id) DO NOTHING
`

func (q *Queries) UpsertUserMuteNotification(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, upsertUserMuteNotification, userID)
	return err
}
