// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account_merge_request_delete.sql

package macrodb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteAccountMergeRequest = `-- name: DeleteAccountMergeRequest :exec
DELETE FROM "account_merge_request"
        WHERE "id" = $1
`

func (q *Queries) DeleteAccountMergeRequest(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAccountMergeRequest, id)
	return err
}
