// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account_merge_request_get.sql

package macrodb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkMergeRequestForToMergeMacroUserId = `-- name: CheckMergeRequestForToMergeMacroUserId :one
SELECT
            id
        FROM account_merge_request
        WHERE to_merge_macro_user_id = $1
`

func (q *Queries) CheckMergeRequestForToMergeMacroUserId(ctx context.Context, toMergeMacroUserID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, checkMergeRequestForToMergeMacroUserId, toMergeMacroUserID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getMergeRequestInfo = `-- name: GetMergeRequestInfo :one
SELECT
            "id" as "merge_request_id",
            "to_merge_macro_user_id" as "to_merge_macro_user_id"
        FROM "account_merge_request"
        WHERE "code" = $1 AND "macro_user_id" = $2
`

type GetMergeRequestInfoParams struct {
	Code        string
	MacroUserID pgtype.UUID
}

type GetMergeRequestInfoRow struct {
	MergeRequestID     pgtype.UUID
	ToMergeMacroUserID pgtype.UUID
}

func (q *Queries) GetMergeRequestInfo(ctx context.Context, arg GetMergeRequestInfoParams) (GetMergeRequestInfoRow, error) {
	row := q.db.QueryRow(ctx, getMergeRequestInfo, arg.Code, arg.MacroUserID)
	var i GetMergeRequestInfoRow
	err := row.Scan(&i.MergeRequestID, &i.ToMergeMacroUserID)
	return i, err
}
