// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: account_merge_request_create.sql

package macrodb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccountMergeRequest = `-- name: CreateAccountMergeRequest :one
INSERT INTO "account_merge_request" (id, macro_user_id, to_merge_macro_user_id, code, created_at)
        VALUES ($1, $2, $3, $4, NOW())
        RETURNING "code"
`

type CreateAccountMergeRequestParams struct {
	ID                 pgtype.UUID
	MacroUserID        pgtype.UUID
	ToMergeMacroUserID pgtype.UUID
	Code               string
}

func (q *Queries) CreateAccountMergeRequest(ctx context.Context, arg CreateAccountMergeRequestParams) (string, error) {
	row := q.db.QueryRow(ctx, createAccountMergeRequest,
		arg.ID,
		arg.MacroUserID,
		arg.ToMergeMacroUserID,
		arg.Code,
	)
	var code string
	err := row.Scan(&code)
	return code, err
}
