// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: advisory_lock.sql

package macrodb

import (
	"context"
)

const tryAcquireUserRefreshXactLock = `-- name: TryAcquireUserRefreshXactLock :one
SELECT pg_try_advisory_xact_lock($1)
`

func (q *Queries) TryAcquireUserRefreshXactLock(ctx context.Context, pgTryAdvisoryXactLock int64) (bool, error) {
	row := q.db.QueryRow(ctx, tryAcquireUserRefreshXactLock, pgTryAdvisoryXactLock)
	var pg_try_advisory_xact_lock bool
	err := row.Scan(&pg_try_advisory_xact_lock)
	return pg_try_advisory_xact_lock, err
}
