// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: annotations_delete_anchor.sql

package macrodb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deletePdfHighlightAnchor = `-- name: DeletePdfHighlightAnchor :one
SELECT a.owner, a."threadId" as thread_id, d.owner as document_owner, d.id as document_id
        FROM "PdfHighlightAnchor" a
        JOIN "Document" d ON a."documentId" = d.id
        WHERE a.uuid = $1 AND a."deletedAt" IS NULL
`

type DeletePdfHighlightAnchorRow struct {
	Owner         string
	ThreadID      pgtype.Int8
	DocumentOwner string
	DocumentID    string
}

func (q *Queries) DeletePdfHighlightAnchor(ctx context.Context, uuid pgtype.UUID) (DeletePdfHighlightAnchorRow, error) {
	row := q.db.QueryRow(ctx, deletePdfHighlightAnchor, uuid)
	var i DeletePdfHighlightAnchorRow
	err := row.Scan(
		&i.Owner,
		&i.ThreadID,
		&i.DocumentOwner,
		&i.DocumentID,
	)
	return i, err
}

const deletePdfHighlightAnchor2 = `-- name: DeletePdfHighlightAnchor2 :exec
UPDATE "PdfHighlightAnchor"
        SET "deletedAt" = NOW()
        WHERE uuid = $1 AND "deletedAt" IS NULL
`

func (q *Queries) DeletePdfHighlightAnchor2(ctx context.Context, uuid pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePdfHighlightAnchor2, uuid)
	return err
}

const deletePdfHighlightAnchor3 = `-- name: DeletePdfHighlightAnchor3 :exec
UPDATE "PdfHighlightAnchor"
            SET "threadId" = NULL
            WHERE uuid = $1 AND "deletedAt" IS NULL
`

func (q *Queries) DeletePdfHighlightAnchor3(ctx context.Context, uuid pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePdfHighlightAnchor3, uuid)
	return err
}
