// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: annotations_delete_thread.sql

package macrodb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteDocumentThread = `-- name: DeleteDocumentThread :one
UPDATE "Thread"
            SET "deletedAt" = NOW()
            WHERE id = $1 and "deletedAt" IS NULL
            RETURNING "deletedAt"
`

func (q *Queries) DeleteDocumentThread(ctx context.Context, id int64) (pgtype.Timestamp, error) {
	row := q.db.QueryRow(ctx, deleteDocumentThread, id)
	var deletedAt pgtype.Timestamp
	err := row.Scan(&deletedAt)
	return deletedAt, err
}

const deleteDocumentThread2 = `-- name: DeleteDocumentThread2 :exec
UPDATE "Comment"
            SET "deletedAt" = NOW()
            WHERE "threadId" = $1
`

func (q *Queries) DeleteDocumentThread2(ctx context.Context, threadid int64) error {
	_, err := q.db.Exec(ctx, deleteDocumentThread2, threadid)
	return err
}
