// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: annotations_edit_comment.sql

package macrodb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const editDocumentComment = `-- name: EditDocumentComment :one
SELECT c.owner, t."documentId" as document_id, d.name as document_name, d."fileType" as file_type, dt.sub_type as "sub_type", d.owner as document_owner
        FROM "Comment" c
        JOIN "Thread" t ON c."threadId" = t.id
        JOIN "Document" d ON t."documentId" = d.id
        LEFT JOIN document_sub_type dt ON dt.document_id = d.id
        WHERE c.id = $1 and c."deletedAt" IS NULL AND t."deletedAt" IS NULL
`

type EditDocumentCommentRow struct {
	Owner         string
	DocumentID    string
	DocumentName  string
	FileType      pgtype.Text
	SubType       NullDocumentSubTypeValue
	DocumentOwner string
}

func (q *Queries) EditDocumentComment(ctx context.Context, id int64) (EditDocumentCommentRow, error) {
	row := q.db.QueryRow(ctx, editDocumentComment, id)
	var i EditDocumentCommentRow
	err := row.Scan(
		&i.Owner,
		&i.DocumentID,
		&i.DocumentName,
		&i.FileType,
		&i.SubType,
		&i.DocumentOwner,
	)
	return i, err
}

const editDocumentComment2 = `-- name: EditDocumentComment2 :one
UPDATE "Comment" c
        SET "text" = $1, "metadata" = $2, "updatedAt" = NOW()
        WHERE "id" = $3 AND "deletedAt" IS NULL
        RETURNING 
            c.id as comment_id, 
            c."threadId" as thread_id, 
            c.owner, 
            c.sender, 
            c.text, 
            c.metadata, 
            c."createdAt"::timestamptz as created_at, 
            c."updatedAt"::timestamptz as updated_at, 
            c."deletedAt"::timestamptz as deleted_at, 
            c.order
`

type EditDocumentComment2Params struct {
	Text     string
	Metadata []byte
	ID       int64
}

type EditDocumentComment2Row struct {
	CommentID int64
	ThreadID  int64
	Owner     string
	Sender    pgtype.Text
	Text      string
	Metadata  []byte
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
	Order     pgtype.Int4
}

func (q *Queries) EditDocumentComment2(ctx context.Context, arg EditDocumentComment2Params) (EditDocumentComment2Row, error) {
	row := q.db.QueryRow(ctx, editDocumentComment2, arg.Text, arg.Metadata, arg.ID)
	var i EditDocumentComment2Row
	err := row.Scan(
		&i.CommentID,
		&i.ThreadID,
		&i.Owner,
		&i.Sender,
		&i.Text,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Order,
	)
	return i, err
}
