// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: annotations_create_comment.sql

package macrodb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDocumentComment = `-- name: CreateDocumentComment :one
UPDATE "Thread" t
                SET "updatedAt" = NOW(), "metadata" = $3
                WHERE t."documentId" = $1 AND t."deletedAt" IS NULL AND t.id = $2
                RETURNING
                    t.id as thread_id, 
                    t.resolved, 
                    t."documentId" as document_id, 
                    t."createdAt"::timestamptz as created_at, 
                    t."updatedAt"::timestamptz as updated_at, 
                    t."deletedAt"::timestamptz as deleted_at, 
                    t.metadata, 
                    t.owner
`

type CreateDocumentCommentParams struct {
	DocumentId string
	ID         int64
	Metadata   []byte
}

type CreateDocumentCommentRow struct {
	ThreadID   int64
	Resolved   bool
	DocumentID string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	DeletedAt  pgtype.Timestamptz
	Metadata   []byte
	Owner      string
}

func (q *Queries) CreateDocumentComment(ctx context.Context, arg CreateDocumentCommentParams) (CreateDocumentCommentRow, error) {
	row := q.db.QueryRow(ctx, createDocumentComment, arg.DocumentId, arg.ID, arg.Metadata)
	var i CreateDocumentCommentRow
	err := row.Scan(
		&i.ThreadID,
		&i.Resolved,
		&i.DocumentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Metadata,
		&i.Owner,
	)
	return i, err
}

const createDocumentComment2 = `-- name: CreateDocumentComment2 :one
UPDATE "Thread" t
                SET "updatedAt" = NOW()
                WHERE t."documentId" = $1 AND t."deletedAt" IS NULL AND t.id = $2
                RETURNING
                    t.id as thread_id, 
                    t.resolved, 
                    t."documentId" as document_id, 
                    t."createdAt"::timestamptz as created_at, 
                    t."updatedAt"::timestamptz as updated_at, 
                    t."deletedAt"::timestamptz as deleted_at, 
                    t.metadata, 
                    t.owner
`

type CreateDocumentComment2Params struct {
	DocumentId string
	ID         int64
}

type CreateDocumentComment2Row struct {
	ThreadID   int64
	Resolved   bool
	DocumentID string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	DeletedAt  pgtype.Timestamptz
	Metadata   []byte
	Owner      string
}

func (q *Queries) CreateDocumentComment2(ctx context.Context, arg CreateDocumentComment2Params) (CreateDocumentComment2Row, error) {
	row := q.db.QueryRow(ctx, createDocumentComment2, arg.DocumentId, arg.ID)
	var i CreateDocumentComment2Row
	err := row.Scan(
		&i.ThreadID,
		&i.Resolved,
		&i.DocumentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Metadata,
		&i.Owner,
	)
	return i, err
}

const createDocumentComment3 = `-- name: CreateDocumentComment3 :one
INSERT INTO "Thread" AS t 
                ("owner", "documentId", "createdAt", "updatedAt", "metadata")
                VALUES ($1, $2, NOW(), NOW(), $3)
                RETURNING
                    t.id as thread_id, 
                    t.resolved, 
                    t."documentId" as document_id, 
                    t."createdAt"::timestamptz as created_at, 
                    t."updatedAt"::timestamptz as updated_at, 
                    t."deletedAt"::timestamptz as deleted_at, 
                    t.metadata, 
                    t.owner
`

type CreateDocumentComment3Params struct {
	Owner      string
	DocumentId string
	Metadata   []byte
}

type CreateDocumentComment3Row struct {
	ThreadID   int64
	Resolved   bool
	DocumentID string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	DeletedAt  pgtype.Timestamptz
	Metadata   []byte
	Owner      string
}

func (q *Queries) CreateDocumentComment3(ctx context.Context, arg CreateDocumentComment3Params) (CreateDocumentComment3Row, error) {
	row := q.db.QueryRow(ctx, createDocumentComment3, arg.Owner, arg.DocumentId, arg.Metadata)
	var i CreateDocumentComment3Row
	err := row.Scan(
		&i.ThreadID,
		&i.Resolved,
		&i.DocumentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Metadata,
		&i.Owner,
	)
	return i, err
}

const createDocumentComment4 = `-- name: CreateDocumentComment4 :one
INSERT INTO "Comment" AS c 
        ("threadId", "owner", "text", "metadata")
        VALUES ($1, $2, $3, $4)
        RETURNING
            c.id as comment_id, 
            c."threadId" as thread_id, 
            c.owner, 
            c.sender, 
            c.text, 
            c.metadata, 
            c."createdAt"::timestamptz as created_at, 
            c."updatedAt"::timestamptz as updated_at, 
            c."deletedAt"::timestamptz as deleted_at, 
            c.order
`

type CreateDocumentComment4Params struct {
	ThreadId int64
	Owner    string
	Text     string
	Metadata []byte
}

type CreateDocumentComment4Row struct {
	CommentID int64
	ThreadID  int64
	Owner     string
	Sender    pgtype.Text
	Text      string
	Metadata  []byte
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
	Order     pgtype.Int4
}

func (q *Queries) CreateDocumentComment4(ctx context.Context, arg CreateDocumentComment4Params) (CreateDocumentComment4Row, error) {
	row := q.db.QueryRow(ctx, createDocumentComment4,
		arg.ThreadId,
		arg.Owner,
		arg.Text,
		arg.Metadata,
	)
	var i CreateDocumentComment4Row
	err := row.Scan(
		&i.CommentID,
		&i.ThreadID,
		&i.Owner,
		&i.Sender,
		&i.Text,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Order,
	)
	return i, err
}
