// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: annotations_create_anchor.sql

package macrodb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const attachAnchorToThread = `-- name: AttachAnchorToThread :exec
INSERT INTO "ThreadAnchor" ("threadId", "anchorId", "anchorTableName")
    VALUES ($1, $2, $3::"anchor_table_name")
`

type AttachAnchorToThreadParams struct {
	ThreadId int64
	AnchorId pgtype.UUID
	Column3  AnchorTableName
}

func (q *Queries) AttachAnchorToThread(ctx context.Context, arg AttachAnchorToThreadParams) error {
	_, err := q.db.Exec(ctx, attachAnchorToThread, arg.ThreadId, arg.AnchorId, arg.Column3)
	return err
}

const createPdfHighlightAnchor = `-- name: CreatePdfHighlightAnchor :exec
INSERT INTO "PdfHighlightRect" ("pdfHighlightAnchorId", "top", "left", "width", "height")
    SELECT unnest($1::uuid[]), unnest($2::double precision[]), unnest($3::double precision[]), unnest($4::double precision[]), unnest($5::double precision[])
`

type CreatePdfHighlightAnchorParams struct {
	Column1 []pgtype.UUID
	Column2 []float64
	Column3 []float64
	Column4 []float64
	Column5 []float64
}

func (q *Queries) CreatePdfHighlightAnchor(ctx context.Context, arg CreatePdfHighlightAnchorParams) error {
	_, err := q.db.Exec(ctx, createPdfHighlightAnchor,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
	)
	return err
}

const validateThreadExists = `-- name: ValidateThreadExists :one
SELECT 1
    FROM "Thread" t
    WHERE t.id = $1 AND t."deletedAt" IS NULL
`

func (q *Queries) ValidateThreadExists(ctx context.Context, id int64) (int32, error) {
	row := q.db.QueryRow(ctx, validateThreadExists, id)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
