// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: blocked_email.sql

package macrodb

import (
	"context"
)

const bulkUpsertBlockEmail = `-- name: BulkUpsertBlockEmail :exec
INSERT INTO "BlockedEmail" (email)
            SELECT email FROM unnest($1::text[]) AS email
            ON CONFLICT (email) DO NOTHING
`

func (q *Queries) BulkUpsertBlockEmail(ctx context.Context, dollar_1 []string) error {
	_, err := q.db.Exec(ctx, bulkUpsertBlockEmail, dollar_1)
	return err
}

const getBlockedEmails = `-- name: GetBlockedEmails :many
SELECT email
            FROM "BlockedEmail"
            WHERE "email" = ANY($1::text[])
`

func (q *Queries) GetBlockedEmails(ctx context.Context, dollar_1 []string) ([]string, error) {
	rows, err := q.db.Query(ctx, getBlockedEmails, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var email string
		if err := rows.Scan(&email); err != nil {
			return nil, err
		}
		items = append(items, email)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBlockEmail = `-- name: UpsertBlockEmail :exec
INSERT INTO "BlockedEmail" (email)
            VALUES ($1)
            ON CONFLICT (email) DO NOTHING
`

func (q *Queries) UpsertBlockEmail(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, upsertBlockEmail, email)
	return err
}
