// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: calendar_event_get_events_for_search.sql

package macrodb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCalendarEventsForSearch = `-- name: GetCalendarEventsForSearch :many
SELECT
            event.id AS "id",
            event.owner_id AS "owner_id",
            event.title AS "title",
            event.status AS "status",
            event.starts_at,
            event.ends_at,
            event.start_date,
            event.end_date,
            event.time_zone,
            (cardinality(event.recurrence_lines) > 0) AS "is_recurring",
            event.conference_url,
            event.organizer_email,
            event.organizer_name,
            event.description,
            event.is_read_only AS "is_read_only",
            event.created_at AS "created_at",
            event.updated_at AS "updated_at",
            occurrence.occurrence_key AS "occurrence_key",
            occurrence.starts_at AS "occurrence_starts_at",
            occurrence.ends_at AS "occurrence_ends_at",
            occurrence.start_date AS "occurrence_start_date",
            occurrence.end_date AS "occurrence_end_date"
        FROM calendar_events event
        LEFT JOIN LATERAL (
            SELECT
                instance.occurrence_key,
                instance.starts_at,
                instance.ends_at,
                instance.start_date,
                instance.end_date
            FROM calendar_event_occurrences instance
            WHERE instance.event_id = event.id
              AND NOT instance.is_cancelled
            ORDER BY
                (COALESCE(instance.starts_at, instance.start_date::timestamp AT TIME ZONE 'UTC') >= $3) DESC,
                CASE WHEN COALESCE(instance.starts_at, instance.start_date::timestamp AT TIME ZONE 'UTC') >= $3
                    THEN COALESCE(instance.starts_at, instance.start_date::timestamp AT TIME ZONE 'UTC') END ASC,
                COALESCE(instance.starts_at, instance.start_date::timestamp AT TIME ZONE 'UTC') DESC,
                instance.occurrence_key
            LIMIT 1
        ) occurrence ON true
        WHERE event."id" = ANY($2::uuid[])
          AND (
                event.owner_id = $1
                OR EXISTS (
                    SELECT 1
                    FROM macro_user_links link
                    WHERE link.link_id = event.source_link_id
                      AND link.primary_macro_id = $1
                )
          )
`

type GetCalendarEventsForSearchParams struct {
	OwnerID  string
	Column2  []pgtype.UUID
	StartsAt pgtype.Timestamptz
}

type GetCalendarEventsForSearchRow struct {
	ID                  pgtype.UUID
	OwnerID             string
	Title               string
	Status              string
	StartsAt            pgtype.Timestamptz
	EndsAt              pgtype.Timestamptz
	StartDate           pgtype.Date
	EndDate             pgtype.Date
	TimeZone            pgtype.Text
	IsRecurring         bool
	ConferenceUrl       pgtype.Text
	OrganizerEmail      pgtype.Text
	OrganizerName       pgtype.Text
	Description         pgtype.Text
	IsReadOnly          bool
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	OccurrenceKey       string
	OccurrenceStartsAt  pgtype.Timestamptz
	OccurrenceEndsAt    pgtype.Timestamptz
	OccurrenceStartDate pgtype.Date
	OccurrenceEndDate   pgtype.Date
}

func (q *Queries) GetCalendarEventsForSearch(ctx context.Context, arg GetCalendarEventsForSearchParams) ([]GetCalendarEventsForSearchRow, error) {
	rows, err := q.db.Query(ctx, getCalendarEventsForSearch, arg.OwnerID, arg.Column2, arg.StartsAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCalendarEventsForSearchRow
	for rows.Next() {
		var i GetCalendarEventsForSearchRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Title,
			&i.Status,
			&i.StartsAt,
			&i.EndsAt,
			&i.StartDate,
			&i.EndDate,
			&i.TimeZone,
			&i.IsRecurring,
			&i.ConferenceUrl,
			&i.OrganizerEmail,
			&i.OrganizerName,
			&i.Description,
			&i.IsReadOnly,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OccurrenceKey,
			&i.OccurrenceStartsAt,
			&i.OccurrenceEndsAt,
			&i.OccurrenceStartDate,
			&i.OccurrenceEndDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
