// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chat_read.sql

package macrodb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserMessages = `-- name: GetUserMessages :many
SELECT 
      m.id 
    FROM 
      "ChatMessage" m
    JOIN 
      "Chat" c on c."id" = m."chatId"
    WHERE
      "userId" = $1
    AND
      m."updatedAt" <= $2
    AND 
      m."updatedAt" >= $3
    AND 
      "role" = 'user'
    
    ORDER BY 
      m."updatedAt" DESC
    LIMIT 
      $4
    OFFSET $5
`

type GetUserMessagesParams struct {
	UserId      string
	UpdatedAt   pgtype.Timestamp
	UpdatedAt_2 pgtype.Timestamp
	Limit       int32
	Offset      int32
}

func (q *Queries) GetUserMessages(ctx context.Context, arg GetUserMessagesParams) ([]string, error) {
	rows, err := q.db.Query(ctx, getUserMessages,
		arg.UserId,
		arg.UpdatedAt,
		arg.UpdatedAt_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
