// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chat_delete.sql

package macrodb

import (
	"context"
)

const deleteChat = `-- name: DeleteChat :one
SELECT "sharePermissionId" as share_permission_id
            FROM "ChatPermission"
            WHERE "chatId"=$1
`

func (q *Queries) DeleteChat(ctx context.Context, chatid string) (string, error) {
	row := q.db.QueryRow(ctx, deleteChat, chatid)
	var share_permission_id string
	err := row.Scan(&share_permission_id)
	return share_permission_id, err
}

const deleteChat2 = `-- name: DeleteChat2 :exec
DELETE FROM "SharePermission" WHERE id = $1
`

func (q *Queries) DeleteChat2(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteChat2, id)
	return err
}

const deleteChat3 = `-- name: DeleteChat3 :exec
DELETE FROM "Chat"
        WHERE id = $1
`

func (q *Queries) DeleteChat3(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteChat3, id)
	return err
}

const deleteChatBulkTsx = `-- name: DeleteChatBulkTsx :exec
DELETE FROM "Pin" WHERE "pinnedItemId" = ANY($1::text[]) AND "pinnedItemType" = $2
`

type DeleteChatBulkTsxParams struct {
	Column1        []string
	PinnedItemType string
}

func (q *Queries) DeleteChatBulkTsx(ctx context.Context, arg DeleteChatBulkTsxParams) error {
	_, err := q.db.Exec(ctx, deleteChatBulkTsx, arg.Column1, arg.PinnedItemType)
	return err
}

const deleteChatBulkTsx2 = `-- name: DeleteChatBulkTsx2 :exec
DELETE FROM "UserHistory" WHERE "itemId" = ANY($1::text[]) AND "itemType" = $2
`

type DeleteChatBulkTsx2Params struct {
	Column1  []string
	ItemType string
}

func (q *Queries) DeleteChatBulkTsx2(ctx context.Context, arg DeleteChatBulkTsx2Params) error {
	_, err := q.db.Exec(ctx, deleteChatBulkTsx2, arg.Column1, arg.ItemType)
	return err
}

const deleteChatBulkTsx3 = `-- name: DeleteChatBulkTsx3 :exec
DELETE FROM "SharePermission"
            WHERE id IN (
                SELECT "sharePermissionId"
                FROM "ChatPermission"
                WHERE "chatId" = ANY($1::text[])
            )
`

func (q *Queries) DeleteChatBulkTsx3(ctx context.Context, dollar_1 []string) error {
	_, err := q.db.Exec(ctx, deleteChatBulkTsx3, dollar_1)
	return err
}

const deleteChatBulkTsx4 = `-- name: DeleteChatBulkTsx4 :exec
DELETE FROM "Chat"
        WHERE "id" = ANY($1::text[])
`

func (q *Queries) DeleteChatBulkTsx4(ctx context.Context, dollar_1 []string) error {
	_, err := q.db.Exec(ctx, deleteChatBulkTsx4, dollar_1)
	return err
}

const softDeleteChat = `-- name: SoftDeleteChat :exec
DELETE FROM "UserHistory" WHERE "itemId" = $1 AND "itemType" = $2
`

type SoftDeleteChatParams struct {
	ItemId   string
	ItemType string
}

func (q *Queries) SoftDeleteChat(ctx context.Context, arg SoftDeleteChatParams) error {
	_, err := q.db.Exec(ctx, softDeleteChat, arg.ItemId, arg.ItemType)
	return err
}

const softDeleteChat2 = `-- name: SoftDeleteChat2 :exec
UPDATE "Chat" SET "deletedAt" = NOW() WHERE id = $1
`

func (q *Queries) SoftDeleteChat2(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, softDeleteChat2, id)
	return err
}
