// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chat_preview.sql

package macrodb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const batchGetDocumentPreviewV2 = `-- name: BatchGetDocumentPreviewV2 :many
SELECT
                c.id as chat_id,
                c.name as chat_name,
                c."userId" as owner,
                c."updatedAt"::timestamptz as "updated_at"
            FROM
                "Chat" c
            WHERE
                c."id" = ANY($1::text[])
`

type BatchGetDocumentPreviewV2Row struct {
	ChatID    string
	ChatName  string
	Owner     string
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) BatchGetDocumentPreviewV2(ctx context.Context, dollar_1 []string) ([]BatchGetDocumentPreviewV2Row, error) {
	rows, err := q.db.Query(ctx, batchGetDocumentPreviewV2, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BatchGetDocumentPreviewV2Row
	for rows.Next() {
		var i BatchGetDocumentPreviewV2Row
		if err := rows.Scan(
			&i.ChatID,
			&i.ChatName,
			&i.Owner,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
