// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chat.sql

package macrodb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getBasicChat = `-- name: GetBasicChat :one
SELECT
            c.id as "id",
            c.name as "name",
            c."projectId" as "project_id",
            c."userId" as "user_id",
            c."deletedAt"::timestamptz as "deleted_at"
        FROM
            "Chat" c
        WHERE
            c.id = $1
`

type GetBasicChatRow struct {
	ID        string
	Name      string
	ProjectID pgtype.Text
	UserID    string
	DeletedAt pgtype.Timestamptz
}

func (q *Queries) GetBasicChat(ctx context.Context, id string) (GetBasicChatRow, error) {
	row := q.db.QueryRow(ctx, getBasicChat, id)
	var i GetBasicChatRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProjectID,
		&i.UserID,
		&i.DeletedAt,
	)
	return i, err
}

const getChatIdsForMessages = `-- name: GetChatIdsForMessages :many
SELECT DISTINCT m."chatId" as chat_id
        FROM "ChatMessage" m
        WHERE m."id" = ANY($1::text[])
`

func (q *Queries) GetChatIdsForMessages(ctx context.Context, dollar_1 []string) ([]string, error) {
	rows, err := q.db.Query(ctx, getChatIdsForMessages, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var chat_id string
		if err := rows.Scan(&chat_id); err != nil {
			return nil, err
		}
		items = append(items, chat_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChatsToDelete = `-- name: GetChatsToDelete :many
SELECT c.id
            FROM "Chat" c
            WHERE c."deletedAt" IS NOT NULL AND c."deletedAt" <= $1
`

func (q *Queries) GetChatsToDelete(ctx context.Context, deletedat pgtype.Timestamp) ([]string, error) {
	rows, err := q.db.Query(ctx, getChatsToDelete, deletedat)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
