// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chat_history.sql

package macrodb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getChatHistory = `-- name: GetChatHistory :many
SELECT
            c.id as chat_id,
            c.name as chat_title,
            m.content::text as message_content,
            m."createdAt" as message_created_at,
            ma.entity_id::text as attachment_id
        FROM "Chat" c
        JOIN "ChatMessage" m ON m."chatId" = c.id
        LEFT JOIN "ChatAttachment" ma ON ma."messageId" = m.id
        WHERE c.id = $1
        ORDER BY m."createdAt" ASC
`

type GetChatHistoryRow struct {
	ChatID           string
	ChatTitle        string
	MessageContent   string
	MessageCreatedAt pgtype.Timestamp
	AttachmentID     string
}

func (q *Queries) GetChatHistory(ctx context.Context, id string) ([]GetChatHistoryRow, error) {
	rows, err := q.db.Query(ctx, getChatHistory, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetChatHistoryRow
	for rows.Next() {
		var i GetChatHistoryRow
		if err := rows.Scan(
			&i.ChatID,
			&i.ChatTitle,
			&i.MessageContent,
			&i.MessageCreatedAt,
			&i.AttachmentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChatHistoryForMessages = `-- name: GetChatHistoryForMessages :many
SELECT
            c.id as chat_id,
            c.name as chat_title,
            m.content::text as message_content,
            m."createdAt" as message_created_at,
            ma.entity_id::text as attachment_id
        FROM "Chat" c
        JOIN "ChatMessage" m ON m."chatId" = c.id
        LEFT JOIN "ChatAttachment" ma ON ma."messageId" = m.id
        WHERE m."id" = ANY($1::text[])
        ORDER BY m."createdAt" ASC
`

type GetChatHistoryForMessagesRow struct {
	ChatID           string
	ChatTitle        string
	MessageContent   string
	MessageCreatedAt pgtype.Timestamp
	AttachmentID     string
}

func (q *Queries) GetChatHistoryForMessages(ctx context.Context, dollar_1 []string) ([]GetChatHistoryForMessagesRow, error) {
	rows, err := q.db.Query(ctx, getChatHistoryForMessages, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetChatHistoryForMessagesRow
	for rows.Next() {
		var i GetChatHistoryForMessagesRow
		if err := rows.Scan(
			&i.ChatID,
			&i.ChatTitle,
			&i.MessageContent,
			&i.MessageCreatedAt,
			&i.AttachmentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
