// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chat_revert_delete.sql

package macrodb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const revertDeleteChat = `-- name: RevertDeleteChat :one
UPDATE "Chat"
        SET "deletedAt" = NULL
        WHERE id = $1
        RETURNING "userId" as owner
`

func (q *Queries) RevertDeleteChat(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, revertDeleteChat, id)
	var owner string
	err := row.Scan(&owner)
	return owner, err
}

const revertDeleteChat2 = `-- name: RevertDeleteChat2 :exec
INSERT INTO "UserHistory" ("userId", "itemId", "itemType", "createdAt", "updatedAt")
        VALUES ($1, $2, $3, NOW(), NOW())
        ON CONFLICT ("userId", "itemId", "itemType") DO UPDATE
        SET "updatedAt" = NOW()
`

type RevertDeleteChat2Params struct {
	UserId   string
	ItemId   string
	ItemType string
}

func (q *Queries) RevertDeleteChat2(ctx context.Context, arg RevertDeleteChat2Params) error {
	_, err := q.db.Exec(ctx, revertDeleteChat2, arg.UserId, arg.ItemId, arg.ItemType)
	return err
}

const revertDeleteChat3 = `-- name: RevertDeleteChat3 :one
SELECT "deletedAt" as deleted_at FROM "Project" WHERE "id" = $1
`

func (q *Queries) RevertDeleteChat3(ctx context.Context, id string) (pgtype.Timestamp, error) {
	row := q.db.QueryRow(ctx, revertDeleteChat3, id)
	var deleted_at pgtype.Timestamp
	err := row.Scan(&deleted_at)
	return deleted_at, err
}

const revertDeleteChat4 = `-- name: RevertDeleteChat4 :exec
UPDATE "Chat" SET "projectId" = NULL WHERE "id" = $1
`

func (q *Queries) RevertDeleteChat4(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, revertDeleteChat4, id)
	return err
}
