// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dcs_append_attachment_to_chat.sql

package macrodb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addAttachment = `-- name: AddAttachment :one
INSERT INTO "ChatAttachment" ("entity_type", "entity_id", "chatId")
            VALUES ($1, $2, $3)
            RETURNING id
`

type AddAttachmentParams struct {
	EntityType string
	EntityID   pgtype.UUID
	ChatId     pgtype.Text
}

func (q *Queries) AddAttachment(ctx context.Context, arg AddAttachmentParams) (string, error) {
	row := q.db.QueryRow(ctx, addAttachment, arg.EntityType, arg.EntityID, arg.ChatId)
	var id string
	err := row.Scan(&id)
	return id, err
}

const appendAttachmentToChat = `-- name: AppendAttachmentToChat :exec
UPDATE "Chat" SET "updatedAt" = NOW()
        WHERE id = $1
`

func (q *Queries) AppendAttachmentToChat(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, appendAttachmentToChat, id)
	return err
}
