// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dcs_copy_messages.sql

package macrodb

import (
	"context"
)

const copyMessages = `-- name: CopyMessages :exec
INSERT INTO "ChatMessage" ("chatId", "createdAt", "updatedAt", "content", "role", "model")
        SELECT $1, "createdAt", "updatedAt", "content", "role", "model"
        FROM "ChatMessage"
        WHERE "ChatMessage"."chatId"=$2
`

type CopyMessagesParams struct {
	ChatId   string
	ChatId_2 string
}

func (q *Queries) CopyMessages(ctx context.Context, arg CopyMessagesParams) error {
	_, err := q.db.Exec(ctx, copyMessages, arg.ChatId, arg.ChatId_2)
	return err
}
