// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dcs_create_chat_message.sql

package macrodb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createChatMessage = `-- name: CreateChatMessage :one
INSERT INTO "ChatMessage" ("id", "chatId", "content", "role", "model", "createdAt", "updatedAt")
            VALUES ($1, $2, $3, $4, $5, $6, $7)
            RETURNING id
`

type CreateChatMessageParams struct {
	ID        string
	ChatId    string
	Content   []byte
	Role      string
	Model     pgtype.Text
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

func (q *Queries) CreateChatMessage(ctx context.Context, arg CreateChatMessageParams) (string, error) {
	row := q.db.QueryRow(ctx, createChatMessage,
		arg.ID,
		arg.ChatId,
		arg.Content,
		arg.Role,
		arg.Model,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const createChatMessage2 = `-- name: CreateChatMessage2 :exec
INSERT INTO "ChatAttachment" ("entity_type", "entity_id", "chatId", "messageId")
            SELECT unnest($1::TEXT[]), unnest($2::UUID[]), unnest($3::TEXT[]), unnest($4::TEXT[])
`

type CreateChatMessage2Params struct {
	Column1 []string
	Column2 []pgtype.UUID
	Column3 []string
	Column4 []string
}

func (q *Queries) CreateChatMessage2(ctx context.Context, arg CreateChatMessage2Params) error {
	_, err := q.db.Exec(ctx, createChatMessage2,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	return err
}
