// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dcs_get_documents.sql

package macrodb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDocumentsCount = `-- name: GetDocumentsCount :one
SELECT COUNT(*) as "count"
            FROM "Document" d
            WHERE d."deletedAt" IS NULL
`

func (q *Queries) GetDocumentsCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getDocumentsCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getDocumentsWithoutTextCount = `-- name: GetDocumentsWithoutTextCount :one
SELECT COUNT(*) as "count"
            FROM "Document" d
            LEFT JOIN "DocumentText" dt ON d.id = dt."documentId"
            WHERE d."deletedAt" IS NULL
            AND dt."documentId" IS NULL
`

func (q *Queries) GetDocumentsWithoutTextCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getDocumentsWithoutTextCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getPaginatedDocuments = `-- name: GetPaginatedDocuments :many
SELECT
            d.id,
            d."owner",
            d.name,
            d."fileType" as "file_type",
            di.id as "document_version_id"
        FROM
            "Document" d
        LEFT JOIN LATERAL (
            SELECT
                i.id
            FROM
                "DocumentInstance" i
            WHERE
                i."documentId" = d.id
            ORDER BY
                i."createdAt" ASC
            LIMIT 1
        ) di ON true
        WHERE
            d."deletedAt" IS NULL
            AND d."fileType" IS NOT NULL
        ORDER BY d."createdAt" DESC
        LIMIT $1 OFFSET $2
`

type GetPaginatedDocumentsParams struct {
	Limit  int32
	Offset int32
}

type GetPaginatedDocumentsRow struct {
	ID                string
	Owner             string
	Name              string
	FileType          pgtype.Text
	DocumentVersionID int64
}

func (q *Queries) GetPaginatedDocuments(ctx context.Context, arg GetPaginatedDocumentsParams) ([]GetPaginatedDocumentsRow, error) {
	rows, err := q.db.Query(ctx, getPaginatedDocuments, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPaginatedDocumentsRow
	for rows.Next() {
		var i GetPaginatedDocumentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.Name,
			&i.FileType,
			&i.DocumentVersionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPaginatedDocumentsWithoutText = `-- name: GetPaginatedDocumentsWithoutText :many
SELECT
            d.id,
            d.name,
            d.owner,
            d."fileType" as "file_type",
            di.id as "document_version_id"
        FROM
            "Document" d
        LEFT JOIN "DocumentText" dt ON d.id = dt."documentId"
        LEFT JOIN LATERAL (
            SELECT
                i.id
            FROM
                "DocumentInstance" i
            WHERE
                i."documentId" = d.id
            ORDER BY
                i."createdAt" ASC
            LIMIT 1
        ) di ON true
        WHERE
            d."deletedAt" IS NULL
            AND dt."documentId" IS NULL
            AND d."fileType" IS NOT NULL
        ORDER BY d."createdAt" DESC
        LIMIT $1 OFFSET $2
`

type GetPaginatedDocumentsWithoutTextParams struct {
	Limit  int32
	Offset int32
}

type GetPaginatedDocumentsWithoutTextRow struct {
	ID                string
	Name              string
	Owner             string
	FileType          pgtype.Text
	DocumentVersionID int64
}

func (q *Queries) GetPaginatedDocumentsWithoutText(ctx context.Context, arg GetPaginatedDocumentsWithoutTextParams) ([]GetPaginatedDocumentsWithoutTextRow, error) {
	rows, err := q.db.Query(ctx, getPaginatedDocumentsWithoutText, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPaginatedDocumentsWithoutTextRow
	for rows.Next() {
		var i GetPaginatedDocumentsWithoutTextRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Owner,
			&i.FileType,
			&i.DocumentVersionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
