// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dcs_get_document_text.sql

package macrodb

import (
	"context"
)

const batchDocumentTextExtractionStatus = `-- name: BatchDocumentTextExtractionStatus :many
SELECT DISTINCT
            d."documentId",
            LENGTH(REGEXP_REPLACE(d."content", '\s', '', 'g')) AS content_length
        FROM
            "DocumentText" d
        WHERE
            d."documentId" = ANY($1::text[])
`

type BatchDocumentTextExtractionStatusRow struct {
	DocumentId    string
	ContentLength float64
}

func (q *Queries) BatchDocumentTextExtractionStatus(ctx context.Context, dollar_1 []string) ([]BatchDocumentTextExtractionStatusRow, error) {
	rows, err := q.db.Query(ctx, batchDocumentTextExtractionStatus, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BatchDocumentTextExtractionStatusRow
	for rows.Next() {
		var i BatchDocumentTextExtractionStatusRow
		if err := rows.Scan(&i.DocumentId, &i.ContentLength); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const documentTextExtractionStatus = `-- name: DocumentTextExtractionStatus :one
SELECT
            LENGTH(REGEXP_REPLACE(d."content", '\s', '', 'g')) AS content_length
        FROM
            "DocumentText" d
        WHERE
            d."documentId" = $1
`

func (q *Queries) DocumentTextExtractionStatus(ctx context.Context, documentid string) (float64, error) {
	row := q.db.QueryRow(ctx, documentTextExtractionStatus, documentid)
	var content_length float64
	err := row.Scan(&content_length)
	return content_length, err
}

const getDocumentTextsWithNoTokens = `-- name: GetDocumentTextsWithNoTokens :many
SELECT
            d."documentId" as "document_id"
        FROM
            "DocumentText" d
        WHERE
            d."tokenCount" = 0
`

func (q *Queries) GetDocumentTextsWithNoTokens(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, getDocumentTextsWithNoTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var document_id string
		if err := rows.Scan(&document_id); err != nil {
			return nil, err
		}
		items = append(items, document_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPdfDocxDocumentText = `-- name: GetPdfDocxDocumentText :one
SELECT
            d."documentId" as "document_id",
            d.content as "content",
            d."tokenCount" as "token_count"
        FROM
            "DocumentText" d
        WHERE
            d."documentId" = $1
`

type GetPdfDocxDocumentTextRow struct {
	DocumentID string
	Content    string
	TokenCount int64
}

func (q *Queries) GetPdfDocxDocumentText(ctx context.Context, documentid string) (GetPdfDocxDocumentTextRow, error) {
	row := q.db.QueryRow(ctx, getPdfDocxDocumentText, documentid)
	var i GetPdfDocxDocumentTextRow
	err := row.Scan(&i.DocumentID, &i.Content, &i.TokenCount)
	return i, err
}

const getPdfDocxTokenCount = `-- name: GetPdfDocxTokenCount :one
SELECT
            "tokenCount" as token_count
            FROM
            "DocumentText"
            WHERE
            "documentId" = $1
`

func (q *Queries) GetPdfDocxTokenCount(ctx context.Context, documentid string) (int64, error) {
	row := q.db.QueryRow(ctx, getPdfDocxTokenCount, documentid)
	var token_count int64
	err := row.Scan(&token_count)
	return token_count, err
}
