// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dcs_delete_chat_message.sql

package macrodb

import (
	"context"
)

const deleteChatMessage = `-- name: DeleteChatMessage :one
DELETE FROM "ChatMessage"
          WHERE id = $1
          RETURNING id
`

func (q *Queries) DeleteChatMessage(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, deleteChatMessage, id)
	var id_2 string
	err := row.Scan(&id_2)
	return id_2, err
}
