// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dcs_get_chats_for_attachment.sql

package macrodb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLatestSingleAttachmentChat = `-- name: GetLatestSingleAttachmentChat :one
WITH SingleAttachmentChats AS (
                SELECT
                    "chatId",
                    COUNT(*) as attachment_count
                FROM "ChatAttachment"
                GROUP BY "chatId"
                HAVING COUNT(*) = 1
            )
            SELECT
                c.id,
                c.name,
                c."userId" as "user_id",
                c."createdAt"::timestamptz as "created_at",
                c."updatedAt"::timestamptz as "updated_at",
                c."deletedAt"::timestamptz as "deleted_at",
                c.model,
                c."tokenCount" as "token_count",
                c."projectId" as "project_id",
                c."isPersistent" as "is_persistent"
            FROM "Chat" c
            INNER JOIN "ChatAttachment" ca ON c.id = ca."chatId"
            INNER JOIN SingleAttachmentChats sac ON c.id = sac."chatId"
            WHERE
                ca."entity_id"::TEXT = $1 AND c."userId" = $2
                AND
                c."deletedAt" IS NULL

            ORDER BY c."updatedAt" DESC
            LIMIT 1
`

type GetLatestSingleAttachmentChatParams struct {
	EntityID pgtype.UUID
	UserId   string
}

type GetLatestSingleAttachmentChatRow struct {
	ID           string
	Name         string
	UserID       string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
	Model        string
	TokenCount   pgtype.Int8
	ProjectID    pgtype.Text
	IsPersistent bool
}

func (q *Queries) GetLatestSingleAttachmentChat(ctx context.Context, arg GetLatestSingleAttachmentChatParams) (GetLatestSingleAttachmentChatRow, error) {
	row := q.db.QueryRow(ctx, getLatestSingleAttachmentChat, arg.EntityID, arg.UserId)
	var i GetLatestSingleAttachmentChatRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Model,
		&i.TokenCount,
		&i.ProjectID,
		&i.IsPersistent,
	)
	return i, err
}

const getMultiAttachmentChat = `-- name: GetMultiAttachmentChat :many
WITH MultiAttachmentChats AS (
                SELECT
                    "chatId",
                    COUNT(*) as attachment_count
                FROM "ChatAttachment"
                GROUP BY "chatId"
            )
            SELECT
                c.id,
                c.name,
                c."userId" as "user_id",
                c."createdAt"::timestamptz as "created_at",
                c."updatedAt"::timestamptz as "updated_at",
                c."deletedAt"::timestamptz as "deleted_at",
                c.model,
                c."tokenCount" as "token_count",
                c."projectId" as "project_id",
                c."isPersistent" as "is_persistent"
            FROM "Chat" c
            INNER JOIN "ChatAttachment" ca ON c.id = ca."chatId"
            INNER JOIN MultiAttachmentChats mac ON c.id = mac."chatId"
            WHERE
                ca."entity_id"::TEXT = $1 AND c."userId" = $2
                    AND
                c."deletedAt" IS NULL
            ORDER BY c."updatedAt" DESC
`

type GetMultiAttachmentChatParams struct {
	EntityID pgtype.UUID
	UserId   string
}

type GetMultiAttachmentChatRow struct {
	ID           string
	Name         string
	UserID       string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
	Model        string
	TokenCount   pgtype.Int8
	ProjectID    pgtype.Text
	IsPersistent bool
}

func (q *Queries) GetMultiAttachmentChat(ctx context.Context, arg GetMultiAttachmentChatParams) ([]GetMultiAttachmentChatRow, error) {
	rows, err := q.db.Query(ctx, getMultiAttachmentChat, arg.EntityID, arg.UserId)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMultiAttachmentChatRow
	for rows.Next() {
		var i GetMultiAttachmentChatRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Model,
			&i.TokenCount,
			&i.ProjectID,
			&i.IsPersistent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
