// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dcs_get_chat.sql

package macrodb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getChatDb = `-- name: GetChatDb :one
SELECT
              c.id,
              c.name,
              c.model,
              c."userId" as "user_id",
              c."createdAt"::timestamptz as "created_at",
              c."updatedAt"::timestamptz as "updated_at",
              c."deletedAt"::timestamptz as "deleted_at",
              c."projectId" as "project_id",
              c."tokenCount" as "token_count",
              c."isPersistent" as "is_persistent"
          FROM "Chat" c WHERE c.id = $1
`

type GetChatDbRow struct {
	ID           string
	Name         string
	Model        string
	UserID       string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
	ProjectID    pgtype.Text
	TokenCount   pgtype.Int8
	IsPersistent bool
}

func (q *Queries) GetChatDb(ctx context.Context, id string) (GetChatDbRow, error) {
	row := q.db.QueryRow(ctx, getChatDb, id)
	var i GetChatDbRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Model,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ProjectID,
		&i.TokenCount,
		&i.IsPersistent,
	)
	return i, err
}

const getChatName = `-- name: GetChatName :one
SELECT name
        FROM "Chat"
        WHERE id = $1
`

func (q *Queries) GetChatName(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getChatName, id)
	var name string
	err := row.Scan(&name)
	return name, err
}

const getMessages = `-- name: GetMessages :many
SELECT
            cm.id AS "id",
            cm.content,
            cm.role,
            cm.model,
            COALESCE(
                (
                    SELECT json_agg(
                        json_build_object(
                            'entity_type', ca."entity_type",
                            'entity_id', ca."entity_id"::TEXT
                        )
                    )
                    FROM "ChatAttachment" ca
                    WHERE ca."messageId" = cm.id
                ),
                '[]'::jsonb
            )::jsonb AS attachments
        FROM
            "ChatMessage" cm
        WHERE
            cm."chatId" = $1
        ORDER BY
            cm."createdAt" ASC
`

type GetMessagesRow struct {
	ID          string
	Content     []byte
	Role        string
	Model       pgtype.Text
	Attachments []byte
}

func (q *Queries) GetMessages(ctx context.Context, chatid string) ([]GetMessagesRow, error) {
	rows, err := q.db.Query(ctx, getMessages, chatid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMessagesRow
	for rows.Next() {
		var i GetMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.Role,
			&i.Model,
			&i.Attachments,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWebCitations = `-- name: GetWebCitations :many
SELECT
            "messageId" as "message_id",
            "url",
            "title",
            "description",
            "favicon_url",
            "image_url"
        FROM "WebAnnotations" wa
        INNER JOIN "ChatMessage" cm ON cm.id = wa."messageId"
        WHERE cm."chatId" = $1
`

type GetWebCitationsRow struct {
	MessageID   pgtype.Text
	Url         string
	Title       string
	Description pgtype.Text
	FaviconUrl  pgtype.Text
	ImageUrl    pgtype.Text
}

func (q *Queries) GetWebCitations(ctx context.Context, chatid string) ([]GetWebCitationsRow, error) {
	rows, err := q.db.Query(ctx, getWebCitations, chatid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetWebCitationsRow
	for rows.Next() {
		var i GetWebCitationsRow
		if err := rows.Scan(
			&i.MessageID,
			&i.Url,
			&i.Title,
			&i.Description,
			&i.FaviconUrl,
			&i.ImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rawAttachments = `-- name: RawAttachments :many
SELECT
              ca.id,
              ca."chatId" as "chat_id",
              ca."entity_id"::TEXT as "attachment_id",
              ca."entity_type" as "attachment_type",
              ca."messageId" as "message_id"
          FROM
              "ChatAttachment" ca
          WHERE ca."chatId" = $1
          ORDER BY ca.id ASC
`

type RawAttachmentsRow struct {
	ID             string
	ChatID         pgtype.Text
	AttachmentID   string
	AttachmentType string
	MessageID      pgtype.Text
}

func (q *Queries) RawAttachments(ctx context.Context, chatid pgtype.Text) ([]RawAttachmentsRow, error) {
	rows, err := q.db.Query(ctx, rawAttachments, chatid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RawAttachmentsRow
	for rows.Next() {
		var i RawAttachmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.AttachmentID,
			&i.AttachmentType,
			&i.MessageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
