// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dcs_batch_verify.sql

package macrodb

import (
	"context"
)

const batchVerify = `-- name: BatchVerify :many
SELECT d."documentId" as "document_id"
            FROM "DocumentText" as d
            WHERE d."documentId" = ANY($1::text[])
            AND d."tokenCount" > 0
`

func (q *Queries) BatchVerify(ctx context.Context, dollar_1 []string) ([]string, error) {
	rows, err := q.db.Query(ctx, batchVerify, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var document_id string
		if err := rows.Scan(&document_id); err != nil {
			return nil, err
		}
		items = append(items, document_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
