// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dcs_get_chats.sql

package macrodb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getChats = `-- name: GetChats :many
SELECT
            c.id,
            c.name,
            c.model,
            c."tokenCount" as "token_count",
            c."userId" as "user_id",
            c."createdAt"::timestamptz as "created_at",
            c."updatedAt"::timestamptz as "updated_at",
            c."deletedAt"::timestamptz as "deleted_at",
            c."projectId" as "project_id",
            c."isPersistent" as "is_persistent"
        FROM "Chat" c
        WHERE c."userId" = $1 AND c."deletedAt" IS NULL
`

type GetChatsRow struct {
	ID           string
	Name         string
	Model        string
	TokenCount   pgtype.Int8
	UserID       string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
	ProjectID    pgtype.Text
	IsPersistent bool
}

func (q *Queries) GetChats(ctx context.Context, userid string) ([]GetChatsRow, error) {
	rows, err := q.db.Query(ctx, getChats, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetChatsRow
	for rows.Next() {
		var i GetChatsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Model,
			&i.TokenCount,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ProjectID,
			&i.IsPersistent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
