// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dcs_get_attachment.sql

package macrodb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAttachment = `-- name: GetAttachment :one
SELECT
                ca.id,
                ca."entity_type" as "attachment_type",
                ca."entity_id"::TEXT as "attachment_id",
                ca."chatId" as "chat_id",
                ca."messageId" as "message_id"
            FROM
                "ChatAttachment" ca
            WHERE
                ca."id" = $1
            LIMIT 1
`

type GetAttachmentRow struct {
	ID             string
	AttachmentType string
	AttachmentID   string
	ChatID         pgtype.Text
	MessageID      pgtype.Text
}

func (q *Queries) GetAttachment(ctx context.Context, id string) (GetAttachmentRow, error) {
	row := q.db.QueryRow(ctx, getAttachment, id)
	var i GetAttachmentRow
	err := row.Scan(
		&i.ID,
		&i.AttachmentType,
		&i.AttachmentID,
		&i.ChatID,
		&i.MessageID,
	)
	return i, err
}
