// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dcs_does_document_exist.sql

package macrodb

import (
	"context"
)

const doesDocumentExist = `-- name: DoesDocumentExist :one
SELECT
            d.id
        FROM
            "Document" d
        WHERE
            d.id = $1
`

func (q *Queries) DoesDocumentExist(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, doesDocumentExist, id)
	var id_2 string
	err := row.Scan(&id_2)
	return id_2, err
}
