// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: document_initialize_onboarding_documents.sql

package macrodb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOnboardingDocx = `-- name: CreateOnboardingDocx :one
INSERT INTO "DocumentBom" ("documentId")
            VALUES ($1)
            RETURNING id
`

func (q *Queries) CreateOnboardingDocx(ctx context.Context, documentid string) (int64, error) {
	row := q.db.QueryRow(ctx, createOnboardingDocx, documentid)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createProjectTransaction = `-- name: CreateProjectTransaction :one
INSERT INTO "Project" ("name", "userId", "parentId", "createdAt", "updatedAt")
        VALUES ($1, $2, $3, NOW(), NOW())
        RETURNING id, name, "userId"::text as user_id, "createdAt"::timestamptz as created_at, "deletedAt"::timestamptz as deleted_at,
        "updatedAt"::timestamptz as updated_at, "parentId" as parent_id
`

type CreateProjectTransactionParams struct {
	Name     string
	UserId   string
	ParentId pgtype.Text
}

type CreateProjectTransactionRow struct {
	ID        string
	Name      string
	UserID    string
	CreatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	ParentID  pgtype.Text
}

func (q *Queries) CreateProjectTransaction(ctx context.Context, arg CreateProjectTransactionParams) (CreateProjectTransactionRow, error) {
	row := q.db.QueryRow(ctx, createProjectTransaction, arg.Name, arg.UserId, arg.ParentId)
	var i CreateProjectTransactionRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UserID,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.UpdatedAt,
		&i.ParentID,
	)
	return i, err
}
