// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: document_get_document_views.sql

package macrodb

import (
	"context"
)

const getDocumentViewCount = `-- name: GetDocumentViewCount :one
SELECT COUNT(*)
            FROM "DocumentView" dv
            WHERE dv."document_id" = $1
`

func (q *Queries) GetDocumentViewCount(ctx context.Context, documentID string) (int64, error) {
	row := q.db.QueryRow(ctx, getDocumentViewCount, documentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getDocumentViews = `-- name: GetDocumentViews :many
SELECT
                u.email
            FROM "UserHistory" uh
            JOIN "User" u ON uh."userId" = u.id
            WHERE uh."itemId" = $1 AND uh."itemType" = 'document'
`

func (q *Queries) GetDocumentViews(ctx context.Context, itemid string) ([]string, error) {
	rows, err := q.db.Query(ctx, getDocumentViews, itemid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var email string
		if err := rows.Scan(&email); err != nil {
			return nil, err
		}
		items = append(items, email)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
