// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: document_get_document_history.sql

package macrodb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDocumentHistoryInfo = `-- name: GetDocumentHistoryInfo :many
SELECT
            c."id" as "item_id",
            c."owner" as "owner",
            c."fileType" as "file_type",
            c."name" as "file_name",
            c."createdAt" as "created_at",
            c."updatedAt" as "updated_at",
            c."deletedAt" as "deleted_at",
            uh."updatedAt" as "viewed_at",
            c."projectId" as "project_id",
            dt.sub_type as "sub_type"
        FROM
            "Document" c
        LEFT JOIN document_sub_type dt ON dt.document_id = c.id
        LEFT JOIN
            "UserHistory" uh ON uh."itemId" = c."id"
                AND uh."userId" = $1
                AND uh."itemType" = 'document'
        WHERE
            c."id" = ANY($2::text[])
        ORDER BY
            c."updatedAt" DESC
`

type GetDocumentHistoryInfoParams struct {
	UserId  string
	Column2 []string
}

type GetDocumentHistoryInfoRow struct {
	ItemID    string
	Owner     string
	FileType  pgtype.Text
	FileName  string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	DeletedAt pgtype.Timestamp
	ViewedAt  pgtype.Timestamp
	ProjectID pgtype.Text
	SubType   NullDocumentSubTypeValue
}

func (q *Queries) GetDocumentHistoryInfo(ctx context.Context, arg GetDocumentHistoryInfoParams) ([]GetDocumentHistoryInfoRow, error) {
	rows, err := q.db.Query(ctx, getDocumentHistoryInfo, arg.UserId, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDocumentHistoryInfoRow
	for rows.Next() {
		var i GetDocumentHistoryInfoRow
		if err := rows.Scan(
			&i.ItemID,
			&i.Owner,
			&i.FileType,
			&i.FileName,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ViewedAt,
			&i.ProjectID,
			&i.SubType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
