// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: document_get_all_documents.sql

package macrodb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAllDocumentIdsPaginated = `-- name: GetAllDocumentIdsPaginated :many
SELECT
            id as "document_id"
        FROM
            "Document"
        WHERE
            "deletedAt" IS NULL
        ORDER BY
            "createdAt" ASC
        LIMIT $1
        OFFSET $2
`

type GetAllDocumentIdsPaginatedParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) GetAllDocumentIdsPaginated(ctx context.Context, arg GetAllDocumentIdsPaginatedParams) ([]string, error) {
	rows, err := q.db.Query(ctx, getAllDocumentIdsPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var document_id string
		if err := rows.Scan(&document_id); err != nil {
			return nil, err
		}
		items = append(items, document_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllDocuments = `-- name: GetAllDocuments :one
SELECT COUNT(*) as "count"
        FROM "Document" d
        WHERE d."deletedAt" IS NULL
`

func (q *Queries) GetAllDocuments(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getAllDocuments)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAllDocuments2 = `-- name: GetAllDocuments2 :many
SELECT
            d.id as document_id,
            d.owner as owner,
            d.name as document_name,
            COALESCE(db.id, di.id) as "document_version_id",
            d."branchedFromId" as "branched_from_id",
            d."branchedFromVersionId" as "branched_from_version_id",
            d."documentFamilyId" as "document_family_id",
            d."fileType" as file_type,
            d."createdAt"::timestamptz as created_at,
            d."updatedAt"::timestamptz as updated_at,
            d."deletedAt"::timestamptz as deleted_at,
            db.bom_parts as "document_bom",
            di.modification_data as "modification_data",
            d."projectId" as "project_id",
            p.name as "project_name",
            di.sha as "sha",
            dt.sub_type as "sub_type"
        FROM
            "Document" d
        LEFT JOIN document_sub_type dt ON dt.document_id = d.id
        LEFT JOIN LATERAL (
            SELECT
                b.id,
                (
                    SELECT
                        json_agg(
                            json_build_object(
                                'id', bp.id,
                                'sha', bp.sha,
                                'path', bp.path
                            )
                        )
                    FROM
                        "BomPart" bp
                    WHERE
                        bp."documentBomId" = b.id
                ) as bom_parts
            FROM
                "DocumentBom" b
            WHERE
                b."documentId" = d.id
            ORDER BY
                b."createdAt" DESC
            LIMIT 1
        ) db ON d."fileType" = 'docx'
        LEFT JOIN LATERAL (
            SELECT
                i.id,
                i."documentId",
                i."sha",
                i."createdAt",
                (
                    SELECT
                        imod."modificationData"
                    FROM
                        "DocumentInstanceModificationData" imod
                    WHERE
                        imod."documentInstanceId" = i.id
                ) as modification_data,
                i."updatedAt"
            FROM
                "DocumentInstance" i
            WHERE
                i."documentId" = d.id
            ORDER BY
                i."updatedAt" DESC
            LIMIT 1
        ) di ON d."fileType" IS DISTINCT FROM 'docx'
        LEFT JOIN "Project" p ON p.id = d."projectId"
        WHERE
        d."deletedAt" IS NULL
        ORDER BY d."createdAt" DESC
        LIMIT $1 OFFSET $2
`

type GetAllDocuments2Params struct {
	Limit  int32
	Offset int32
}

type GetAllDocuments2Row struct {
	DocumentID            string
	Owner                 string
	DocumentName          string
	DocumentVersionID     int64
	BranchedFromID        pgtype.Text
	BranchedFromVersionID pgtype.Int8
	DocumentFamilyID      pgtype.Int8
	FileType              pgtype.Text
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	DeletedAt             pgtype.Timestamptz
	DocumentBom           []byte
	ModificationData      []byte
	ProjectID             pgtype.Text
	ProjectName           pgtype.Text
	Sha                   string
	SubType               NullDocumentSubTypeValue
}

func (q *Queries) GetAllDocuments2(ctx context.Context, arg GetAllDocuments2Params) ([]GetAllDocuments2Row, error) {
	rows, err := q.db.Query(ctx, getAllDocuments2, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllDocuments2Row
	for rows.Next() {
		var i GetAllDocuments2Row
		if err := rows.Scan(
			&i.DocumentID,
			&i.Owner,
			&i.DocumentName,
			&i.DocumentVersionID,
			&i.BranchedFromID,
			&i.BranchedFromVersionID,
			&i.DocumentFamilyID,
			&i.FileType,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DocumentBom,
			&i.ModificationData,
			&i.ProjectID,
			&i.ProjectName,
			&i.Sha,
			&i.SubType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDocumentsToDelete = `-- name: GetDocumentsToDelete :many
SELECT d.id
            FROM "Document" d
            WHERE d."deletedAt" IS NOT NULL AND d."deletedAt" <= $1
`

func (q *Queries) GetDocumentsToDelete(ctx context.Context, deletedat pgtype.Timestamp) ([]string, error) {
	rows, err := q.db.Query(ctx, getDocumentsToDelete, deletedat)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
