// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: document_create_blank_docx.sql

package macrodb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBlankDocx = `-- name: CreateBlankDocx :one
SELECT name FROM "Project" WHERE id = $1
`

func (q *Queries) CreateBlankDocx(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, createBlankDocx, id)
	var name string
	err := row.Scan(&name)
	return name, err
}

const createBlankDocx2 = `-- name: CreateBlankDocx2 :one
INSERT INTO "Document" (owner, name, "fileType", "projectId")
            VALUES ($1, $2, $3, $4)
            RETURNING id
`

type CreateBlankDocx2Params struct {
	Owner     string
	Name      string
	FileType  pgtype.Text
	ProjectId pgtype.Text
}

func (q *Queries) CreateBlankDocx2(ctx context.Context, arg CreateBlankDocx2Params) (string, error) {
	row := q.db.QueryRow(ctx, createBlankDocx2,
		arg.Owner,
		arg.Name,
		arg.FileType,
		arg.ProjectId,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const createBlankDocx3 = `-- name: CreateBlankDocx3 :one
INSERT INTO "DocumentFamily" ("rootDocumentId")
                VALUES ($1)
                RETURNING id
`

func (q *Queries) CreateBlankDocx3(ctx context.Context, rootdocumentid string) (int64, error) {
	row := q.db.QueryRow(ctx, createBlankDocx3, rootdocumentid)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createBlankDocx4 = `-- name: CreateBlankDocx4 :exec
UPDATE "Document" SET "documentFamilyId" = $1 WHERE id = $2
`

type CreateBlankDocx4Params struct {
	DocumentFamilyId pgtype.Int8
	ID               string
}

func (q *Queries) CreateBlankDocx4(ctx context.Context, arg CreateBlankDocx4Params) error {
	_, err := q.db.Exec(ctx, createBlankDocx4, arg.DocumentFamilyId, arg.ID)
	return err
}

const createBlankDocx5 = `-- name: CreateBlankDocx5 :one
INSERT INTO "DocumentBom" ("documentId")
                VALUES ($1)
                RETURNING id, "createdAt"::timestamptz as created_at, "updatedAt"::timestamptz as updated_at
`

type CreateBlankDocx5Row struct {
	ID        int64
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) CreateBlankDocx5(ctx context.Context, documentid string) (CreateBlankDocx5Row, error) {
	row := q.db.QueryRow(ctx, createBlankDocx5, documentid)
	var i CreateBlankDocx5Row
	err := row.Scan(&i.ID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}
