// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: document_revert_delete.sql

package macrodb

import (
	"context"
)

const revertDeleteDocument = `-- name: RevertDeleteDocument :one
UPDATE "Document"
        SET "deletedAt" = NULL
        WHERE id = $1
        RETURNING owner as owner
`

func (q *Queries) RevertDeleteDocument(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, revertDeleteDocument, id)
	var owner string
	err := row.Scan(&owner)
	return owner, err
}

const revertDeleteDocument2 = `-- name: RevertDeleteDocument2 :exec
UPDATE "Document" SET "projectId" = NULL WHERE "id" = $1
`

func (q *Queries) RevertDeleteDocument2(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, revertDeleteDocument2, id)
	return err
}
