// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: document_preview.sql

package macrodb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const batchGetDocumentPreviewV22 = `-- name: BatchGetDocumentPreviewV22 :many
SELECT
                d.id as "document_id",
                d.name as "document_name",
                d."fileType" as file_type,
                d.owner as "owner",
                d."updatedAt"::timestamptz as "updated_at",
                dt.sub_type as "sub_type",
                CASE 
                    WHEN dt.sub_type = 'task' 
                        AND ep_status.values->'value' ? $2
                    THEN true 
                    WHEN dt.sub_type = 'task'
                    THEN false
                    ELSE NULL 
                END::bool as "is_completed"
            FROM "Document" d
            LEFT JOIN document_sub_type dt ON dt.document_id = d.id
            LEFT JOIN entity_properties ep_status 
                ON dt.sub_type = 'task'
                AND ep_status.entity_id = d.id 
                AND ep_status.entity_type = 'TASK'
                AND ep_status.property_definition_id = $3
            WHERE
                d."id" = ANY($1::text[])
`

type BatchGetDocumentPreviewV22Params struct {
	Column1              []string
	Values               []byte
	PropertyDefinitionID pgtype.UUID
}

type BatchGetDocumentPreviewV22Row struct {
	DocumentID   string
	DocumentName string
	FileType     pgtype.Text
	Owner        string
	UpdatedAt    pgtype.Timestamptz
	SubType      NullDocumentSubTypeValue
	IsCompleted  bool
}

func (q *Queries) BatchGetDocumentPreviewV22(ctx context.Context, arg BatchGetDocumentPreviewV22Params) ([]BatchGetDocumentPreviewV22Row, error) {
	rows, err := q.db.Query(ctx, batchGetDocumentPreviewV22, arg.Column1, arg.Values, arg.PropertyDefinitionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BatchGetDocumentPreviewV22Row
	for rows.Next() {
		var i BatchGetDocumentPreviewV22Row
		if err := rows.Scan(
			&i.DocumentID,
			&i.DocumentName,
			&i.FileType,
			&i.Owner,
			&i.UpdatedAt,
			&i.SubType,
			&i.IsCompleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
