// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: document_delete_document.sql

package macrodb

import (
	"context"
)

const deleteDocument = `-- name: DeleteDocument :one
SELECT "sharePermissionId" as share_permission_id
            FROM "DocumentPermission"
            WHERE "documentId"=$1
`

func (q *Queries) DeleteDocument(ctx context.Context, documentid string) (string, error) {
	row := q.db.QueryRow(ctx, deleteDocument, documentid)
	var share_permission_id string
	err := row.Scan(&share_permission_id)
	return share_permission_id, err
}

const deleteDocument2 = `-- name: DeleteDocument2 :exec
DELETE FROM "Document" WHERE id = $1
`

func (q *Queries) DeleteDocument2(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteDocument2, id)
	return err
}

const deleteDocumentVersion = `-- name: DeleteDocumentVersion :one
SELECT
            (SELECT COUNT(*) FROM "DocumentInstance" WHERE "DocumentInstance"."documentId" = $1) +
            (SELECT COUNT(*) FROM "DocumentBom" WHERE "DocumentBom"."documentId" = $1) AS total_count
`

func (q *Queries) DeleteDocumentVersion(ctx context.Context, documentid string) (int32, error) {
	row := q.db.QueryRow(ctx, deleteDocumentVersion, documentid)
	var total_count int32
	err := row.Scan(&total_count)
	return total_count, err
}

const deleteDocumentVersion2 = `-- name: DeleteDocumentVersion2 :exec
DELETE FROM "DocumentBom" WHERE id = $2 and "documentId" = $1
`

type DeleteDocumentVersion2Params struct {
	DocumentId string
	ID         int64
}

func (q *Queries) DeleteDocumentVersion2(ctx context.Context, arg DeleteDocumentVersion2Params) error {
	_, err := q.db.Exec(ctx, deleteDocumentVersion2, arg.DocumentId, arg.ID)
	return err
}

const deleteDocumentVersion3 = `-- name: DeleteDocumentVersion3 :exec
DELETE FROM "DocumentInstance" WHERE id = $2 and "documentId" = $1
`

type DeleteDocumentVersion3Params struct {
	DocumentId string
	ID         int64
}

func (q *Queries) DeleteDocumentVersion3(ctx context.Context, arg DeleteDocumentVersion3Params) error {
	_, err := q.db.Exec(ctx, deleteDocumentVersion3, arg.DocumentId, arg.ID)
	return err
}

const getShasForDeletion = `-- name: GetShasForDeletion :many
SELECT bp.sha
        FROM "BomPart" bp
        JOIN "DocumentBom" db ON bp."documentBomId" = db.id
        WHERE db."documentId" = $1
`

func (q *Queries) GetShasForDeletion(ctx context.Context, documentid string) ([]string, error) {
	rows, err := q.db.Query(ctx, getShasForDeletion, documentid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var sha string
		if err := rows.Scan(&sha); err != nil {
			return nil, err
		}
		items = append(items, sha)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
