// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: document_list_documents_with_access.sql

package macrodb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listDocumentsWithAccess = `-- name: ListDocumentsWithAccess :many
WITH user_source_ids AS (
            SELECT cp.channel_id::text as source_id FROM comms_channel_participants cp
                WHERE cp.user_id = $1 AND cp.left_at IS NULL
            UNION ALL
            SELECT t.team_id::text FROM team_user t
                WHERE t.user_id = $1
            UNION ALL
            SELECT $1
        ),
        user_accessible_documents AS (
            SELECT DISTINCT ON (entity_id) entity_id, access_level
            FROM entity_access
            WHERE source_id = ANY(SELECT source_id FROM user_source_ids)
              AND entity_type = 'document'
            ORDER BY entity_id,
                CASE access_level::text
                    WHEN 'owner' THEN 4
                    WHEN 'edit' THEN 3
                    WHEN 'comment' THEN 2
                    WHEN 'view' THEN 1
                    ELSE 0
                END DESC
        )
        SELECT
            d.id as "document_id",
            d.name as "document_name",
            d.owner as "owner",
            d."fileType" as "file_type",
            d."projectId" as "project_id",
            d."createdAt"::timestamptz as "created_at",
            d."updatedAt"::timestamptz as "updated_at",
            d."deletedAt"::timestamptz as "deleted_at",
            uad.access_level::text as "access_level"
        FROM "Document" d
        INNER JOIN user_accessible_documents uad ON uad.entity_id = d.id::uuid
        WHERE d."deletedAt" IS NULL
        AND ($2::text[] IS NULL OR d."fileType" = ANY($2::text[]))
        AND (
            CASE uad.access_level::text
                WHEN 'owner' THEN 4
                WHEN 'edit' THEN 3
                WHEN 'comment' THEN 2
                WHEN 'view' THEN 1
                ELSE 0
            END >=
            CASE $3::text
                WHEN 'owner' THEN 4
                WHEN 'edit' THEN 3
                WHEN 'comment' THEN 2
                WHEN 'view' THEN 1
                ELSE 0
            END
        )
        ORDER BY d."updatedAt" DESC
        LIMIT $4 OFFSET $5
`

type ListDocumentsWithAccessParams struct {
	UserID  string
	Column2 []string
	Column3 string
	Limit   int32
	Offset  int32
}

type ListDocumentsWithAccessRow struct {
	DocumentID   string
	DocumentName string
	Owner        string
	FileType     pgtype.Text
	ProjectID    pgtype.Text
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
	AccessLevel  string
}

func (q *Queries) ListDocumentsWithAccess(ctx context.Context, arg ListDocumentsWithAccessParams) ([]ListDocumentsWithAccessRow, error) {
	rows, err := q.db.Query(ctx, listDocumentsWithAccess,
		arg.UserID,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDocumentsWithAccessRow
	for rows.Next() {
		var i ListDocumentsWithAccessRow
		if err := rows.Scan(
			&i.DocumentID,
			&i.DocumentName,
			&i.Owner,
			&i.FileType,
			&i.ProjectID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.AccessLevel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
