// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: document_document_email.sql

package macrodb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDocumentEmailRecord = `-- name: CreateDocumentEmailRecord :exec
INSERT INTO "document_email" (document_id, email_attachment_id)
            VALUES ($1, $2)
`

type CreateDocumentEmailRecordParams struct {
	DocumentID        string
	EmailAttachmentID pgtype.UUID
}

func (q *Queries) CreateDocumentEmailRecord(ctx context.Context, arg CreateDocumentEmailRecordParams) error {
	_, err := q.db.Exec(ctx, createDocumentEmailRecord, arg.DocumentID, arg.EmailAttachmentID)
	return err
}
