// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: document_save_document.sql

package macrodb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertAllCommentData = `-- name: InsertAllCommentData :many
SELECT c.id, c."createdAt" as created_at, c."updatedAt" as updated_at
        FROM "Comment" c
        JOIN "Thread" t ON c."threadId" = t.id
        WHERE t."documentId" = $1
`

type InsertAllCommentDataRow struct {
	ID        int64
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

func (q *Queries) InsertAllCommentData(ctx context.Context, documentid string) ([]InsertAllCommentDataRow, error) {
	rows, err := q.db.Query(ctx, insertAllCommentData, documentid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InsertAllCommentDataRow
	for rows.Next() {
		var i InsertAllCommentDataRow
		if err := rows.Scan(&i.ID, &i.CreatedAt, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAllCommentData10 = `-- name: InsertAllCommentData10 :one
INSERT INTO "PdfHighlightAnchor" (
            "uuid", "documentId", "owner", "page", "red", "green", "blue", "alpha", 
            "type", "text", "pageViewportWidth", "pageViewportHeight", 
            "threadId", "createdAt", "updatedAt"
        )
        VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
        RETURNING uuid
`

type InsertAllCommentData10Params struct {
	Uuid               pgtype.UUID
	DocumentId         string
	Owner              string
	Page               int32
	Red                int32
	Green              int32
	Blue               int32
	Alpha              float64
	Type               int32
	Text               string
	PageViewportWidth  float64
	PageViewportHeight float64
	ThreadId           pgtype.Int8
	CreatedAt          pgtype.Timestamp
	UpdatedAt          pgtype.Timestamp
}

func (q *Queries) InsertAllCommentData10(ctx context.Context, arg InsertAllCommentData10Params) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertAllCommentData10,
		arg.Uuid,
		arg.DocumentId,
		arg.Owner,
		arg.Page,
		arg.Red,
		arg.Green,
		arg.Blue,
		arg.Alpha,
		arg.Type,
		arg.Text,
		arg.PageViewportWidth,
		arg.PageViewportHeight,
		arg.ThreadId,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var uuid pgtype.UUID
	err := row.Scan(&uuid)
	return uuid, err
}

const insertAllCommentData11 = `-- name: InsertAllCommentData11 :one
INSERT INTO "PdfHighlightAnchor" (
            "documentId", "owner", "page", "red", "green", "blue", "alpha", 
            "type", "text", "pageViewportWidth", "pageViewportHeight", 
            "threadId", "createdAt", "updatedAt"
        )
        VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
        RETURNING uuid
`

type InsertAllCommentData11Params struct {
	DocumentId         string
	Owner              string
	Page               int32
	Red                int32
	Green              int32
	Blue               int32
	Alpha              float64
	Type               int32
	Text               string
	PageViewportWidth  float64
	PageViewportHeight float64
	ThreadId           pgtype.Int8
	CreatedAt          pgtype.Timestamp
	UpdatedAt          pgtype.Timestamp
}

func (q *Queries) InsertAllCommentData11(ctx context.Context, arg InsertAllCommentData11Params) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertAllCommentData11,
		arg.DocumentId,
		arg.Owner,
		arg.Page,
		arg.Red,
		arg.Green,
		arg.Blue,
		arg.Alpha,
		arg.Type,
		arg.Text,
		arg.PageViewportWidth,
		arg.PageViewportHeight,
		arg.ThreadId,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var uuid pgtype.UUID
	err := row.Scan(&uuid)
	return uuid, err
}

const insertAllCommentData12 = `-- name: InsertAllCommentData12 :one
INSERT INTO "PdfHighlightRect" (
                            "top", "left", "width", "height", "pdfHighlightAnchorId"
                        )
                        VALUES ($1, $2, $3, $4, $5)
                        RETURNING id
`

type InsertAllCommentData12Params struct {
	Top                  float64
	Left                 float64
	Width                float64
	Height               float64
	PdfHighlightAnchorId pgtype.UUID
}

func (q *Queries) InsertAllCommentData12(ctx context.Context, arg InsertAllCommentData12Params) (int64, error) {
	row := q.db.QueryRow(ctx, insertAllCommentData12,
		arg.Top,
		arg.Left,
		arg.Width,
		arg.Height,
		arg.PdfHighlightAnchorId,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertAllCommentData2 = `-- name: InsertAllCommentData2 :many
SELECT a.uuid, a."createdAt" as created_at, a."updatedAt" as updated_at
        FROM "PdfHighlightAnchor" a
        WHERE a."documentId" = $1
`

type InsertAllCommentData2Row struct {
	Uuid      pgtype.UUID
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

func (q *Queries) InsertAllCommentData2(ctx context.Context, documentid string) ([]InsertAllCommentData2Row, error) {
	rows, err := q.db.Query(ctx, insertAllCommentData2, documentid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InsertAllCommentData2Row
	for rows.Next() {
		var i InsertAllCommentData2Row
		if err := rows.Scan(&i.Uuid, &i.CreatedAt, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAllCommentData3 = `-- name: InsertAllCommentData3 :exec
DELETE FROM "Thread" WHERE "documentId" = $1
`

func (q *Queries) InsertAllCommentData3(ctx context.Context, documentid string) error {
	_, err := q.db.Exec(ctx, insertAllCommentData3, documentid)
	return err
}

const insertAllCommentData4 = `-- name: InsertAllCommentData4 :exec
DELETE FROM "PdfHighlightAnchor" WHERE "documentId" = $1
`

func (q *Queries) InsertAllCommentData4(ctx context.Context, documentid string) error {
	_, err := q.db.Exec(ctx, insertAllCommentData4, documentid)
	return err
}

const insertAllCommentData5 = `-- name: InsertAllCommentData5 :one
INSERT INTO "Thread" ("owner", "documentId", "createdAt", "updatedAt", "resolved")
            VALUES ($1, $2, $3, $4, $5)
            RETURNING id
`

type InsertAllCommentData5Params struct {
	Owner      string
	DocumentId string
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
	Resolved   bool
}

func (q *Queries) InsertAllCommentData5(ctx context.Context, arg InsertAllCommentData5Params) (int64, error) {
	row := q.db.QueryRow(ctx, insertAllCommentData5,
		arg.Owner,
		arg.DocumentId,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Resolved,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertAllCommentData6 = `-- name: InsertAllCommentData6 :one
INSERT INTO "PdfPlaceableCommentAnchor" ("uuid", "documentId", "owner", "page", "originalPage", "originalIndex", "shouldLockOnSave", "xPct", "yPct", "widthPct", "heightPct", "rotation", "threadId", "wasEdited", "wasDeleted", "allowableEdits")
            VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
            RETURNING uuid
`

type InsertAllCommentData6Params struct {
	Uuid             pgtype.UUID
	DocumentId       string
	Owner            string
	Page             int32
	OriginalPage     int32
	OriginalIndex    int32
	ShouldLockOnSave bool
	XPct             float64
	YPct             float64
	WidthPct         float64
	HeightPct        float64
	Rotation         float64
	ThreadId         pgtype.Int8
	WasEdited        bool
	WasDeleted       bool
	AllowableEdits   []byte
}

func (q *Queries) InsertAllCommentData6(ctx context.Context, arg InsertAllCommentData6Params) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertAllCommentData6,
		arg.Uuid,
		arg.DocumentId,
		arg.Owner,
		arg.Page,
		arg.OriginalPage,
		arg.OriginalIndex,
		arg.ShouldLockOnSave,
		arg.XPct,
		arg.YPct,
		arg.WidthPct,
		arg.HeightPct,
		arg.Rotation,
		arg.ThreadId,
		arg.WasEdited,
		arg.WasDeleted,
		arg.AllowableEdits,
	)
	var uuid pgtype.UUID
	err := row.Scan(&uuid)
	return uuid, err
}

const insertAllCommentData7 = `-- name: InsertAllCommentData7 :one
INSERT INTO "Comment" ("threadId", "owner", "sender", "text", "createdAt", "updatedAt", "order")
                VALUES ($1, $2, $3, $4, $5, $6, $7)
                RETURNING id
`

type InsertAllCommentData7Params struct {
	ThreadId  int64
	Owner     string
	Sender    pgtype.Text
	Text      string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	Order     pgtype.Int4
}

func (q *Queries) InsertAllCommentData7(ctx context.Context, arg InsertAllCommentData7Params) (int64, error) {
	row := q.db.QueryRow(ctx, insertAllCommentData7,
		arg.ThreadId,
		arg.Owner,
		arg.Sender,
		arg.Text,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Order,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertAllCommentData8 = `-- name: InsertAllCommentData8 :one
INSERT INTO "Thread" ("owner", "documentId", "createdAt", "updatedAt", "resolved")
                            VALUES ($1, $2, $3, $4, $5)
                            RETURNING id
`

type InsertAllCommentData8Params struct {
	Owner      string
	DocumentId string
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
	Resolved   bool
}

func (q *Queries) InsertAllCommentData8(ctx context.Context, arg InsertAllCommentData8Params) (int64, error) {
	row := q.db.QueryRow(ctx, insertAllCommentData8,
		arg.Owner,
		arg.DocumentId,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Resolved,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertAllCommentData9 = `-- name: InsertAllCommentData9 :one
INSERT INTO "Comment" ("threadId", "owner", "sender", "text", "createdAt", "updatedAt", "order")
                                VALUES ($1, $2, $3, $4, $5, $6, $7)
                                RETURNING id
`

type InsertAllCommentData9Params struct {
	ThreadId  int64
	Owner     string
	Sender    pgtype.Text
	Text      string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	Order     pgtype.Int4
}

func (q *Queries) InsertAllCommentData9(ctx context.Context, arg InsertAllCommentData9Params) (int64, error) {
	row := q.db.QueryRow(ctx, insertAllCommentData9,
		arg.ThreadId,
		arg.Owner,
		arg.Sender,
		arg.Text,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Order,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const saveDocument = `-- name: SaveDocument :one
UPDATE "Document" SET "updatedAt" = NOW()
        WHERE id = $1
        RETURNING id as "document_id", owner, "fileType" as file_type, name as document_name,
        "branchedFromId" as branched_from_id, "branchedFromVersionId" as branched_from_version_id,
        "documentFamilyId" as document_family_id,
        "projectId" as project_id,
        "deletedAt"::timestamptz as "deleted_at"
`

type SaveDocumentRow struct {
	DocumentID            string
	Owner                 string
	FileType              pgtype.Text
	DocumentName          string
	BranchedFromID        pgtype.Text
	BranchedFromVersionID pgtype.Int8
	DocumentFamilyID      pgtype.Int8
	ProjectID             pgtype.Text
	DeletedAt             pgtype.Timestamptz
}

func (q *Queries) SaveDocument(ctx context.Context, id string) (SaveDocumentRow, error) {
	row := q.db.QueryRow(ctx, saveDocument, id)
	var i SaveDocumentRow
	err := row.Scan(
		&i.DocumentID,
		&i.Owner,
		&i.FileType,
		&i.DocumentName,
		&i.BranchedFromID,
		&i.BranchedFromVersionID,
		&i.DocumentFamilyID,
		&i.ProjectID,
		&i.DeletedAt,
	)
	return i, err
}

const saveDocument2 = `-- name: SaveDocument2 :one
select name from "Project" where id = $1
`

func (q *Queries) SaveDocument2(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, saveDocument2, id)
	var name string
	err := row.Scan(&name)
	return name, err
}

const saveDocument3 = `-- name: SaveDocument3 :one
INSERT INTO "DocumentInstance" ("documentId", "sha")
                VALUES ($1, $2)
                RETURNING id, sha, "createdAt"::timestamptz as created_at, "updatedAt"::timestamptz as updated_at
`

type SaveDocument3Params struct {
	DocumentId string
	Sha        string
}

type SaveDocument3Row struct {
	ID        int64
	Sha       string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) SaveDocument3(ctx context.Context, arg SaveDocument3Params) (SaveDocument3Row, error) {
	row := q.db.QueryRow(ctx, saveDocument3, arg.DocumentId, arg.Sha)
	var i SaveDocument3Row
	err := row.Scan(
		&i.ID,
		&i.Sha,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const saveDocument4 = `-- name: SaveDocument4 :exec
INSERT INTO "DocumentInstanceModificationData" ("documentInstanceId", "modificationData")
                        VALUES ($1, $2)
`

type SaveDocument4Params struct {
	DocumentInstanceId int64
	ModificationData   []byte
}

func (q *Queries) SaveDocument4(ctx context.Context, arg SaveDocument4Params) error {
	_, err := q.db.Exec(ctx, saveDocument4, arg.DocumentInstanceId, arg.ModificationData)
	return err
}

const saveDocument5 = `-- name: SaveDocument5 :one
SELECT sub_type as "sub_type" FROM document_sub_type WHERE document_id = $1
`

func (q *Queries) SaveDocument5(ctx context.Context, documentID string) (DocumentSubTypeValue, error) {
	row := q.db.QueryRow(ctx, saveDocument5, documentID)
	var sub_type DocumentSubTypeValue
	err := row.Scan(&sub_type)
	return sub_type, err
}

const tryInsertCommentData = `-- name: TryInsertCommentData :exec
SAVEPOINT comment_data_insertion
`

func (q *Queries) TryInsertCommentData(ctx context.Context) error {
	_, err := q.db.Exec(ctx, tryInsertCommentData)
	return err
}

const tryInsertCommentData2 = `-- name: TryInsertCommentData2 :exec
RELEASE SAVEPOINT comment_data_insertion
`

func (q *Queries) TryInsertCommentData2(ctx context.Context) error {
	_, err := q.db.Exec(ctx, tryInsertCommentData2)
	return err
}

const tryInsertCommentData3 = `-- name: TryInsertCommentData3 :exec
ROLLBACK TO SAVEPOINT comment_data_insertion
`

func (q *Queries) TryInsertCommentData3(ctx context.Context) error {
	_, err := q.db.Exec(ctx, tryInsertCommentData3)
	return err
}
