// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: document_build_pdf_modification_data.sql

package macrodb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCompletePdfModificationData = `-- name: GetCompletePdfModificationData :many
SELECT 
            t.id as thread_id, 
            t.resolved as is_resolved,
            a.uuid as anchor_uuid, 
            a.page, 
            a."originalPage" as original_page,
            a."originalIndex" as original_index,
            a."shouldLockOnSave" as should_lock_on_save,
            a."wasEdited" as was_edited,
            a."wasDeleted" as was_deleted,
            a."allowableEdits" as allowable_edits,
            a."xPct" as x_pct,
            a."yPct" as y_pct,
            a."widthPct" as width_pct,
            a."heightPct" as height_pct,
            a.rotation
        FROM "Thread" t
        JOIN "PdfPlaceableCommentAnchor" a ON t."id" = a."threadId"
        WHERE t."documentId" = $1
`

type GetCompletePdfModificationDataRow struct {
	ThreadID         int64
	IsResolved       bool
	AnchorUuid       pgtype.UUID
	Page             int32
	OriginalPage     int32
	OriginalIndex    int32
	ShouldLockOnSave bool
	WasEdited        bool
	WasDeleted       bool
	AllowableEdits   []byte
	XPct             float64
	YPct             float64
	WidthPct         float64
	HeightPct        float64
	Rotation         float64
}

func (q *Queries) GetCompletePdfModificationData(ctx context.Context, documentid string) ([]GetCompletePdfModificationDataRow, error) {
	rows, err := q.db.Query(ctx, getCompletePdfModificationData, documentid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCompletePdfModificationDataRow
	for rows.Next() {
		var i GetCompletePdfModificationDataRow
		if err := rows.Scan(
			&i.ThreadID,
			&i.IsResolved,
			&i.AnchorUuid,
			&i.Page,
			&i.OriginalPage,
			&i.OriginalIndex,
			&i.ShouldLockOnSave,
			&i.WasEdited,
			&i.WasDeleted,
			&i.AllowableEdits,
			&i.XPct,
			&i.YPct,
			&i.WidthPct,
			&i.HeightPct,
			&i.Rotation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCompletePdfModificationData2 = `-- name: GetCompletePdfModificationData2 :many
SELECT 
                id, 
                owner, 
                text as content, 
                "createdAt" as created_at, 
                "updatedAt" as updated_at,
                "order"
            FROM "Comment" 
            WHERE "threadId" = $1
            ORDER BY "order"
`

type GetCompletePdfModificationData2Row struct {
	ID        int64
	Owner     string
	Content   string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	Order     pgtype.Int4
}

func (q *Queries) GetCompletePdfModificationData2(ctx context.Context, threadid int64) ([]GetCompletePdfModificationData2Row, error) {
	rows, err := q.db.Query(ctx, getCompletePdfModificationData2, threadid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCompletePdfModificationData2Row
	for rows.Next() {
		var i GetCompletePdfModificationData2Row
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Order,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCompletePdfModificationData3 = `-- name: GetCompletePdfModificationData3 :many
SELECT 
            a.uuid, 
            a."threadId" as thread_id,
            a.page, 
            a.red, 
            a.green, 
            a.blue, 
            a.alpha,
            a.type as highlight_type, 
            a.text,
            a."pageViewportWidth" as page_viewport_width, 
            a."pageViewportHeight" as page_viewport_height, 
            a."createdAt"::timestamptz as created_at, 
            a."updatedAt"::timestamptz as updated_at
        FROM "PdfHighlightAnchor" a
        WHERE a."documentId" = $1
`

type GetCompletePdfModificationData3Row struct {
	Uuid               pgtype.UUID
	ThreadID           pgtype.Int8
	Page               int32
	Red                int32
	Green              int32
	Blue               int32
	Alpha              float64
	HighlightType      int32
	Text               string
	PageViewportWidth  float64
	PageViewportHeight float64
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

func (q *Queries) GetCompletePdfModificationData3(ctx context.Context, documentid string) ([]GetCompletePdfModificationData3Row, error) {
	rows, err := q.db.Query(ctx, getCompletePdfModificationData3, documentid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCompletePdfModificationData3Row
	for rows.Next() {
		var i GetCompletePdfModificationData3Row
		if err := rows.Scan(
			&i.Uuid,
			&i.ThreadID,
			&i.Page,
			&i.Red,
			&i.Green,
			&i.Blue,
			&i.Alpha,
			&i.HighlightType,
			&i.Text,
			&i.PageViewportWidth,
			&i.PageViewportHeight,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCompletePdfModificationData4 = `-- name: GetCompletePdfModificationData4 :many
SELECT 
                phr.top,
                phr.left,
                phr.width,
                phr.height
            FROM "PdfHighlightRect" phr 
            WHERE phr."pdfHighlightAnchorId" = $1
`

type GetCompletePdfModificationData4Row struct {
	Top    float64
	Left   float64
	Width  float64
	Height float64
}

func (q *Queries) GetCompletePdfModificationData4(ctx context.Context, pdfhighlightanchorid pgtype.UUID) ([]GetCompletePdfModificationData4Row, error) {
	rows, err := q.db.Query(ctx, getCompletePdfModificationData4, pdfhighlightanchorid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCompletePdfModificationData4Row
	for rows.Next() {
		var i GetCompletePdfModificationData4Row
		if err := rows.Scan(
			&i.Top,
			&i.Left,
			&i.Width,
			&i.Height,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCompletePdfModificationData5 = `-- name: GetCompletePdfModificationData5 :one
SELECT resolved as is_resolved
                FROM "Thread"
                WHERE id = $1
`

func (q *Queries) GetCompletePdfModificationData5(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRow(ctx, getCompletePdfModificationData5, id)
	var is_resolved bool
	err := row.Scan(&is_resolved)
	return is_resolved, err
}

const getCompletePdfModificationData6 = `-- name: GetCompletePdfModificationData6 :many
SELECT 
                    id, 
                    owner, 
                    text as content, 
                    "createdAt" as created_at, 
                    "updatedAt" as updated_at,
                    "order"
                FROM "Comment" 
                WHERE "threadId" = $1
                ORDER BY "order"
`

type GetCompletePdfModificationData6Row struct {
	ID        int64
	Owner     string
	Content   string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	Order     pgtype.Int4
}

func (q *Queries) GetCompletePdfModificationData6(ctx context.Context, threadid int64) ([]GetCompletePdfModificationData6Row, error) {
	rows, err := q.db.Query(ctx, getCompletePdfModificationData6, threadid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCompletePdfModificationData6Row
	for rows.Next() {
		var i GetCompletePdfModificationData6Row
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Order,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
