// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: document_get_user_documents.sql

package macrodb

import (
	"context"
)

const getUserDocumentIds = `-- name: GetUserDocumentIds :many
SELECT
                    d.id as document_id
                FROM
                    "Document" d
                WHERE
                    d.owner = $1 AND d."deletedAt" IS NULL AND d."fileType" = ANY($2::text[])
`

type GetUserDocumentIdsParams struct {
	Owner   string
	Column2 []string
}

func (q *Queries) GetUserDocumentIds(ctx context.Context, arg GetUserDocumentIdsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, getUserDocumentIds, arg.Owner, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var document_id string
		if err := rows.Scan(&document_id); err != nil {
			return nil, err
		}
		items = append(items, document_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserDocumentIds2 = `-- name: GetUserDocumentIds2 :many
SELECT
                d.id as document_id
            FROM
                "Document" d
            WHERE
                d.owner = $1 AND d."deletedAt" IS NULL
`

func (q *Queries) GetUserDocumentIds2(ctx context.Context, owner string) ([]string, error) {
	rows, err := q.db.Query(ctx, getUserDocumentIds2, owner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var document_id string
		if err := rows.Scan(&document_id); err != nil {
			return nil, err
		}
		items = append(items, document_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
