// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: docx_unzip.sql

package macrodb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getJobForDocxUpload = `-- name: GetJobForDocxUpload :one
SELECT "jobId" as job_id, "jobType" as job_type FROM "UploadJob" WHERE "documentId" = $1
`

type GetJobForDocxUploadRow struct {
	JobID   string
	JobType string
}

func (q *Queries) GetJobForDocxUpload(ctx context.Context, documentid pgtype.Text) (GetJobForDocxUploadRow, error) {
	row := q.db.QueryRow(ctx, getJobForDocxUpload, documentid)
	var i GetJobForDocxUploadRow
	err := row.Scan(&i.JobID, &i.JobType)
	return i, err
}

const updateUploadedStatus = `-- name: UpdateUploadedStatus :exec
UPDATE "Document"
        SET "uploaded" = true,
            "contentState" = CASE
                WHEN "contentState" = 'ready' AND "contentLocation" = 'converted_pdf'
                    THEN 'ready'
                ELSE 'pending'
            END,
            "contentLocation" = 'converted_pdf'
        WHERE id = $1
`

func (q *Queries) UpdateUploadedStatus(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, updateUploadedStatus, id)
	return err
}
