// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email.sql

package macrodb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkUserEmailLink = `-- name: CheckUserEmailLink :one
SELECT id FROM email_links
    WHERE macro_id = $1
`

func (q *Queries) CheckUserEmailLink(ctx context.Context, macroID string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, checkUserEmailLink, macroID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
