// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: history_delete_history.sql

package macrodb

import (
	"context"
)

const deleteUserHistory = `-- name: DeleteUserHistory :exec
DELETE FROM "UserHistory" WHERE "userId" = $1 AND "itemId" = $2 AND "itemType" = $3
`

type DeleteUserHistoryParams struct {
	UserId   string
	ItemId   string
	ItemType string
}

func (q *Queries) DeleteUserHistory(ctx context.Context, arg DeleteUserHistoryParams) error {
	_, err := q.db.Exec(ctx, deleteUserHistory, arg.UserId, arg.ItemId, arg.ItemType)
	return err
}
