// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: history_upsert_history.sql

package macrodb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertUserHistoryBatch = `-- name: InsertUserHistoryBatch :exec
INSERT INTO "UserHistory" ("userId", "itemId", "itemType", "createdAt", "updatedAt")
        SELECT unnest($1::text[]), unnest($2::text[]), unnest($3::text[]), unnest($4::timestamptz[]), unnest($5::timestamptz[])
        ON CONFLICT ("userId", "itemId", "itemType") DO UPDATE
        SET "updatedAt" = EXCLUDED."updatedAt"
`

type InsertUserHistoryBatchParams struct {
	Column1 []string
	Column2 []string
	Column3 []string
	Column4 []pgtype.Timestamptz
	Column5 []pgtype.Timestamptz
}

func (q *Queries) InsertUserHistoryBatch(ctx context.Context, arg InsertUserHistoryBatchParams) error {
	_, err := q.db.Exec(ctx, insertUserHistoryBatch,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
	)
	return err
}

const upsertItemLastAccessedTimestamp = `-- name: UpsertItemLastAccessedTimestamp :exec
INSERT INTO "ItemLastAccessed" ("item_id", "item_type", "last_accessed")
        VALUES ($1, $2, $3)
        ON CONFLICT ("item_id", "item_type") DO UPDATE
        SET "last_accessed" = $3
`

type UpsertItemLastAccessedTimestampParams struct {
	ItemID       string
	ItemType     string
	LastAccessed pgtype.Timestamp
}

func (q *Queries) UpsertItemLastAccessedTimestamp(ctx context.Context, arg UpsertItemLastAccessedTimestampParams) error {
	_, err := q.db.Exec(ctx, upsertItemLastAccessedTimestamp, arg.ItemID, arg.ItemType, arg.LastAccessed)
	return err
}

const upsertUserHistoryTimestamp = `-- name: UpsertUserHistoryTimestamp :exec
INSERT INTO "UserHistory" ("userId", "itemId", "itemType", "createdAt", "updatedAt")
        VALUES ($1, $2, $3, $4, $4)
        ON CONFLICT ("userId", "itemId", "itemType") DO UPDATE
        SET "updatedAt" = $4
`

type UpsertUserHistoryTimestampParams struct {
	UserId    string
	ItemId    string
	ItemType  string
	CreatedAt pgtype.Timestamp
}

func (q *Queries) UpsertUserHistoryTimestamp(ctx context.Context, arg UpsertUserHistoryTimestampParams) error {
	_, err := q.db.Exec(ctx, upsertUserHistoryTimestamp,
		arg.UserId,
		arg.ItemId,
		arg.ItemType,
		arg.CreatedAt,
	)
	return err
}
