// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: in_progress_user_link.sql

package macrodb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countExistingInProgressUserLinksForUser = `-- name: CountExistingInProgressUserLinksForUser :one
SELECT
                COUNT(id) as count
            FROM
                in_progress_user_link
            WHERE
                macro_user_id = $1
                AND created_at > $2
`

type CountExistingInProgressUserLinksForUserParams struct {
	MacroUserID pgtype.UUID
	CreatedAt   pgtype.Timestamp
}

func (q *Queries) CountExistingInProgressUserLinksForUser(ctx context.Context, arg CountExistingInProgressUserLinksForUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, countExistingInProgressUserLinksForUser, arg.MacroUserID, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createInProgressGoogleLink = `-- name: CreateInProgressGoogleLink :exec
INSERT INTO in_progress_user_link (
                id,
                macro_user_id,
                requested_google_scopes
            )
            VALUES ($1, $2, $3)
`

type CreateInProgressGoogleLinkParams struct {
	ID                    pgtype.UUID
	MacroUserID           pgtype.UUID
	RequestedGoogleScopes []string
}

func (q *Queries) CreateInProgressGoogleLink(ctx context.Context, arg CreateInProgressGoogleLinkParams) error {
	_, err := q.db.Exec(ctx, createInProgressGoogleLink, arg.ID, arg.MacroUserID, arg.RequestedGoogleScopes)
	return err
}

const createInProgressUserLink = `-- name: CreateInProgressUserLink :exec
INSERT INTO in_progress_user_link (id, macro_user_id)
            VALUES ($1, $2)
`

type CreateInProgressUserLinkParams struct {
	ID          pgtype.UUID
	MacroUserID pgtype.UUID
}

func (q *Queries) CreateInProgressUserLink(ctx context.Context, arg CreateInProgressUserLinkParams) error {
	_, err := q.db.Exec(ctx, createInProgressUserLink, arg.ID, arg.MacroUserID)
	return err
}

const deleteDayOldInProgressUserLinks = `-- name: DeleteDayOldInProgressUserLinks :exec
DELETE FROM
                in_progress_user_link
            WHERE
                created_at < $1
`

func (q *Queries) DeleteDayOldInProgressUserLinks(ctx context.Context, createdAt pgtype.Timestamp) error {
	_, err := q.db.Exec(ctx, deleteDayOldInProgressUserLinks, createdAt)
	return err
}

const deleteInProgressUserLink = `-- name: DeleteInProgressUserLink :exec
DELETE FROM
                in_progress_user_link
            WHERE
                id = $1
`

func (q *Queries) DeleteInProgressUserLink(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteInProgressUserLink, id)
	return err
}

const getInProgressUserLink = `-- name: GetInProgressUserLink :one
SELECT
                macro_user_id,
                linked_email,
                requested_google_scopes,
                granted_google_scopes
            FROM
                in_progress_user_link
            WHERE
                id = $1
`

type GetInProgressUserLinkRow struct {
	MacroUserID           pgtype.UUID
	LinkedEmail           pgtype.Text
	RequestedGoogleScopes []string
	GrantedGoogleScopes   []string
}

func (q *Queries) GetInProgressUserLink(ctx context.Context, id pgtype.UUID) (GetInProgressUserLinkRow, error) {
	row := q.db.QueryRow(ctx, getInProgressUserLink, id)
	var i GetInProgressUserLinkRow
	err := row.Scan(
		&i.MacroUserID,
		&i.LinkedEmail,
		&i.RequestedGoogleScopes,
		&i.GrantedGoogleScopes,
	)
	return i, err
}

const getMacroUserIdByLinkId = `-- name: GetMacroUserIdByLinkId :one
SELECT
                id,
                macro_user_id
            FROM
                in_progress_user_link
            WHERE
                id = $1
`

type GetMacroUserIdByLinkIdRow struct {
	ID          pgtype.UUID
	MacroUserID pgtype.UUID
}

func (q *Queries) GetMacroUserIdByLinkId(ctx context.Context, id pgtype.UUID) (GetMacroUserIdByLinkIdRow, error) {
	row := q.db.QueryRow(ctx, getMacroUserIdByLinkId, id)
	var i GetMacroUserIdByLinkIdRow
	err := row.Scan(&i.ID, &i.MacroUserID)
	return i, err
}

const setLinkedEmail = `-- name: SetLinkedEmail :exec
UPDATE in_progress_user_link
            SET linked_email = $1
            WHERE id = $2
`

type SetLinkedEmailParams struct {
	LinkedEmail pgtype.Text
	ID          pgtype.UUID
}

func (q *Queries) SetLinkedEmail(ctx context.Context, arg SetLinkedEmailParams) error {
	_, err := q.db.Exec(ctx, setLinkedEmail, arg.LinkedEmail, arg.ID)
	return err
}

const setLinkedGoogleGrant = `-- name: SetLinkedGoogleGrant :exec
UPDATE in_progress_user_link
            SET linked_email = $1,
                granted_google_scopes = $2
            WHERE id = $3
`

type SetLinkedGoogleGrantParams struct {
	LinkedEmail         pgtype.Text
	GrantedGoogleScopes []string
	ID                  pgtype.UUID
}

func (q *Queries) SetLinkedGoogleGrant(ctx context.Context, arg SetLinkedGoogleGrantParams) error {
	_, err := q.db.Exec(ctx, setLinkedGoogleGrant, arg.LinkedEmail, arg.GrantedGoogleScopes, arg.ID)
	return err
}
