// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: in_progress_email_link.sql

package macrodb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkExistingInProgressEmailLink = `-- name: CheckExistingInProgressEmailLink :one
SELECT
                macro_user_id,
                id
            FROM
                in_progress_email_link
            WHERE
                in_progress_email_link.email = $1
`

type CheckExistingInProgressEmailLinkRow struct {
	MacroUserID pgtype.UUID
	ID          pgtype.UUID
}

func (q *Queries) CheckExistingInProgressEmailLink(ctx context.Context, email string) (CheckExistingInProgressEmailLinkRow, error) {
	row := q.db.QueryRow(ctx, checkExistingInProgressEmailLink, email)
	var i CheckExistingInProgressEmailLinkRow
	err := row.Scan(&i.MacroUserID, &i.ID)
	return i, err
}

const deleteDayOldInProgressEmailLinks = `-- name: DeleteDayOldInProgressEmailLinks :exec
DELETE FROM
                in_progress_email_link
            WHERE
                created_at < $1
`

func (q *Queries) DeleteDayOldInProgressEmailLinks(ctx context.Context, createdAt pgtype.Timestamp) error {
	_, err := q.db.Exec(ctx, deleteDayOldInProgressEmailLinks, createdAt)
	return err
}

const deleteInProgressEmailLink = `-- name: DeleteInProgressEmailLink :exec
DELETE FROM
                in_progress_email_link
            WHERE
                id = $1
`

func (q *Queries) DeleteInProgressEmailLink(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteInProgressEmailLink, id)
	return err
}

const getInProgressEmailLink = `-- name: GetInProgressEmailLink :one
SELECT
                id,
                macro_user_id,
                email
            FROM
                in_progress_email_link
            WHERE
                id = $1
`

type GetInProgressEmailLinkRow struct {
	ID          pgtype.UUID
	MacroUserID pgtype.UUID
	Email       string
}

func (q *Queries) GetInProgressEmailLink(ctx context.Context, id pgtype.UUID) (GetInProgressEmailLinkRow, error) {
	row := q.db.QueryRow(ctx, getInProgressEmailLink, id)
	var i GetInProgressEmailLinkRow
	err := row.Scan(&i.ID, &i.MacroUserID, &i.Email)
	return i, err
}

const insertInProgressEmailLink = `-- name: InsertInProgressEmailLink :exec
INSERT INTO
                in_progress_email_link (id, macro_user_id, email, created_at)
            VALUES
                ($1, $2, $3, NOW())
`

type InsertInProgressEmailLinkParams struct {
	ID          pgtype.UUID
	MacroUserID pgtype.UUID
	Email       string
}

func (q *Queries) InsertInProgressEmailLink(ctx context.Context, arg InsertInProgressEmailLinkParams) error {
	_, err := q.db.Exec(ctx, insertInProgressEmailLink, arg.ID, arg.MacroUserID, arg.Email)
	return err
}
