// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: instructions_get.sql

package macrodb

import (
	"context"
)

const getInstructionsDocument = `-- name: GetInstructionsDocument :one
SELECT "documentId" as "document_id"
            FROM "InstructionsDocuments" id
            JOIN "Document" d ON d."id" = id."documentId"
            WHERE "userId" = $1 AND d."deletedAt" IS NULL
`

func (q *Queries) GetInstructionsDocument(ctx context.Context, userid string) (string, error) {
	row := q.db.QueryRow(ctx, getInstructionsDocument, userid)
	var document_id string
	err := row.Scan(&document_id)
	return document_id, err
}
