// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: item_access_get.sql

package macrodb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getOwnerAndDeleted = `-- name: GetOwnerAndDeleted :one
SELECT owner, "deletedAt" as deleted_at FROM "Document" WHERE id=$1
`

type GetOwnerAndDeletedRow struct {
	Owner     string
	DeletedAt pgtype.Timestamp
}

func (q *Queries) GetOwnerAndDeleted(ctx context.Context, id string) (GetOwnerAndDeletedRow, error) {
	row := q.db.QueryRow(ctx, getOwnerAndDeleted, id)
	var i GetOwnerAndDeletedRow
	err := row.Scan(&i.Owner, &i.DeletedAt)
	return i, err
}

const getOwnerAndDeleted2 = `-- name: GetOwnerAndDeleted2 :one
SELECT "userId" as user_id, "deletedAt" as deleted_at FROM "Chat" WHERE id=$1
`

type GetOwnerAndDeleted2Row struct {
	UserID    string
	DeletedAt pgtype.Timestamp
}

func (q *Queries) GetOwnerAndDeleted2(ctx context.Context, id string) (GetOwnerAndDeleted2Row, error) {
	row := q.db.QueryRow(ctx, getOwnerAndDeleted2, id)
	var i GetOwnerAndDeleted2Row
	err := row.Scan(&i.UserID, &i.DeletedAt)
	return i, err
}

const getOwnerAndDeleted3 = `-- name: GetOwnerAndDeleted3 :one
SELECT "userId" as user_id, "deletedAt" as deleted_at FROM "Project" WHERE id=$1
`

type GetOwnerAndDeleted3Row struct {
	UserID    string
	DeletedAt pgtype.Timestamp
}

func (q *Queries) GetOwnerAndDeleted3(ctx context.Context, id string) (GetOwnerAndDeleted3Row, error) {
	row := q.db.QueryRow(ctx, getOwnerAndDeleted3, id)
	var i GetOwnerAndDeleted3Row
	err := row.Scan(&i.UserID, &i.DeletedAt)
	return i, err
}
