// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: items_filter_document.sql

package macrodb

import (
	"context"
)

const filterDocumentsByFileTypes = `-- name: FilterDocumentsByFileTypes :many
SELECT
            d.id
        FROM
            "Document" d
        WHERE
            d."id" = ANY($1::text[])
            AND d."fileType" = ANY($2::text[])
`

type FilterDocumentsByFileTypesParams struct {
	Column1 []string
	Column2 []string
}

func (q *Queries) FilterDocumentsByFileTypes(ctx context.Context, arg FilterDocumentsByFileTypesParams) ([]string, error) {
	rows, err := q.db.Query(ctx, filterDocumentsByFileTypes, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
