// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: item_access_get_accessible_items.sql

package macrodb

import (
	"context"
)

const accessibleChats = `-- name: AccessibleChats :many
WITH user_source_ids AS (
            SELECT cp.channel_id::text as source_id FROM comms_channel_participants cp
                WHERE cp.user_id = $1 AND cp.left_at IS NULL
            UNION ALL
            SELECT t.team_id::text FROM team_user t
                WHERE t.user_id = $1
            UNION ALL
            SELECT $1
        )
        SELECT DISTINCT ea.entity_id::text as "item_id"
        FROM entity_access ea
        JOIN user_source_ids us ON us.source_id = ea.source_id
        JOIN "Chat" c ON c.id = ea.entity_id::text
        WHERE ea.entity_type = 'chat'
            AND c."deletedAt" IS NULL
            AND (NOT $2::bool OR c."userId" != $1)
`

type AccessibleChatsParams struct {
	UserId  string
	Column2 bool
}

func (q *Queries) AccessibleChats(ctx context.Context, arg AccessibleChatsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, accessibleChats, arg.UserId, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var item_id string
		if err := rows.Scan(&item_id); err != nil {
			return nil, err
		}
		items = append(items, item_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const accessibleDocuments = `-- name: AccessibleDocuments :many
WITH user_source_ids AS (
            SELECT cp.channel_id::text as source_id FROM comms_channel_participants cp
                WHERE cp.user_id = $1 AND cp.left_at IS NULL
            UNION ALL
            SELECT t.team_id::text FROM team_user t
                WHERE t.user_id = $1
            UNION ALL
            SELECT $1
        )
        SELECT DISTINCT ea.entity_id::text as "item_id"
        FROM entity_access ea
        JOIN user_source_ids us ON us.source_id = ea.source_id
        JOIN "Document" d ON d.id = ea.entity_id::text
        WHERE ea.entity_type = 'document'
            AND d."deletedAt" IS NULL
            AND (NOT $2::bool OR d.owner != $1)
`

type AccessibleDocumentsParams struct {
	Owner   string
	Column2 bool
}

func (q *Queries) AccessibleDocuments(ctx context.Context, arg AccessibleDocumentsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, accessibleDocuments, arg.Owner, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var item_id string
		if err := rows.Scan(&item_id); err != nil {
			return nil, err
		}
		items = append(items, item_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const accessibleProjects = `-- name: AccessibleProjects :many
WITH user_source_ids AS (
            SELECT cp.channel_id::text as source_id FROM comms_channel_participants cp
                WHERE cp.user_id = $1 AND cp.left_at IS NULL
            UNION ALL
            SELECT t.team_id::text FROM team_user t
                WHERE t.user_id = $1
            UNION ALL
            SELECT $1
        )
        SELECT DISTINCT ea.entity_id::text as "item_id"
        FROM entity_access ea
        JOIN user_source_ids us ON us.source_id = ea.source_id
        JOIN "Project" p ON p.id = ea.entity_id::text
        WHERE ea.entity_type = 'project'
            AND p."deletedAt" IS NULL
            AND (NOT $2::bool OR p."userId" != $1)
`

type AccessibleProjectsParams struct {
	UserId  string
	Column2 bool
}

func (q *Queries) AccessibleProjects(ctx context.Context, arg AccessibleProjectsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, accessibleProjects, arg.UserId, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var item_id string
		if err := rows.Scan(&item_id); err != nil {
			return nil, err
		}
		items = append(items, item_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
