// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: job_upload_job.sql

package macrodb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const updateUploadJob = `-- name: UpdateUploadJob :exec
UPDATE "UploadJob" SET "documentId" = $1 WHERE "jobId" = $2
`

type UpdateUploadJobParams struct {
	DocumentId pgtype.Text
	JobId      string
}

func (q *Queries) UpdateUploadJob(ctx context.Context, arg UpdateUploadJobParams) error {
	_, err := q.db.Exec(ctx, updateUploadJob, arg.DocumentId, arg.JobId)
	return err
}
