// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: macro_user_email_verification.sql

package macrodb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getMacroUserEmailVerification = `-- name: GetMacroUserEmailVerification :one
SELECT "is_verified"
        FROM "macro_user_email_verification"
        WHERE "email" = $1
`

func (q *Queries) GetMacroUserEmailVerification(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, getMacroUserEmailVerification, email)
	var is_verified bool
	err := row.Scan(&is_verified)
	return is_verified, err
}

const upsertMacroUserEmailVerification = `-- name: UpsertMacroUserEmailVerification :exec
INSERT INTO "macro_user_email_verification" ("macro_user_id", "email", "is_verified")
            VALUES ($1, $2, $3)
        ON CONFLICT ("email") DO UPDATE SET "macro_user_id" = $1, "is_verified" = $3
`

type UpsertMacroUserEmailVerificationParams struct {
	MacroUserID pgtype.UUID
	Email       string
	IsVerified  bool
}

func (q *Queries) UpsertMacroUserEmailVerification(ctx context.Context, arg UpsertMacroUserEmailVerificationParams) error {
	_, err := q.db.Exec(ctx, upsertMacroUserEmailVerification, arg.MacroUserID, arg.Email, arg.IsVerified)
	return err
}
