// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: macro_user.sql

package macrodb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkEmailExists = `-- name: CheckEmailExists :one
SELECT id
        FROM "User"
        WHERE email = $1
`

func (q *Queries) CheckEmailExists(ctx context.Context, email string) (string, error) {
	row := q.db.QueryRow(ctx, checkEmailExists, email)
	var id string
	err := row.Scan(&id)
	return id, err
}

const checkUsernameExists = `-- name: CheckUsernameExists :one
SELECT id
        FROM macro_user
        WHERE username = $1
`

func (q *Queries) CheckUsernameExists(ctx context.Context, username string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, checkUsernameExists, username)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createMacroUser = `-- name: CreateMacroUser :exec
INSERT INTO macro_user (id, username, stripe_customer_id, email)
        VALUES ($1, $2, $3, $4)
        ON CONFLICT ("id") DO NOTHING
`

type CreateMacroUserParams struct {
	ID               pgtype.UUID
	Username         string
	StripeCustomerID string
	Email            string
}

func (q *Queries) CreateMacroUser(ctx context.Context, arg CreateMacroUserParams) error {
	_, err := q.db.Exec(ctx, createMacroUser,
		arg.ID,
		arg.Username,
		arg.StripeCustomerID,
		arg.Email,
	)
	return err
}

const deleteMacroUser = `-- name: DeleteMacroUser :exec
DELETE FROM macro_user
        WHERE id = $1
`

func (q *Queries) DeleteMacroUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMacroUser, id)
	return err
}

const getMacroUser = `-- name: GetMacroUser :one
SELECT id, username, stripe_customer_id
        FROM macro_user
        WHERE id = $1
`

type GetMacroUserRow struct {
	ID               pgtype.UUID
	Username         string
	StripeCustomerID string
}

func (q *Queries) GetMacroUser(ctx context.Context, id pgtype.UUID) (GetMacroUserRow, error) {
	row := q.db.QueryRow(ctx, getMacroUser, id)
	var i GetMacroUserRow
	err := row.Scan(&i.ID, &i.Username, &i.StripeCustomerID)
	return i, err
}
