// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notification.sql

package macrodb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getBasicCloudStorageDocumentsMetadata = `-- name: GetBasicCloudStorageDocumentsMetadata :many
SELECT
            d.id as "document_id",
            d.owner,
            d.name as "document_name",
            d."fileType" as "file_type",
            dst.sub_type as "sub_type"
        FROM
            "Document" d
        LEFT JOIN document_sub_type dst ON dst.document_id = d.id
        WHERE d."id" = ANY($1::text[])
`

type GetBasicCloudStorageDocumentsMetadataRow struct {
	DocumentID   string
	Owner        string
	DocumentName string
	FileType     pgtype.Text
	SubType      NullDocumentSubTypeValue
}

func (q *Queries) GetBasicCloudStorageDocumentsMetadata(ctx context.Context, dollar_1 []string) ([]GetBasicCloudStorageDocumentsMetadataRow, error) {
	rows, err := q.db.Query(ctx, getBasicCloudStorageDocumentsMetadata, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBasicCloudStorageDocumentsMetadataRow
	for rows.Next() {
		var i GetBasicCloudStorageDocumentsMetadataRow
		if err := rows.Scan(
			&i.DocumentID,
			&i.Owner,
			&i.DocumentName,
			&i.FileType,
			&i.SubType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBasicCloudStorageItemMetadata = `-- name: GetBasicCloudStorageItemMetadata :one
SELECT
                    d.id as "document_id",
                    d.owner,
                    d.name as "document_name",
                    d."fileType" as "file_type",
                    dst.sub_type as "sub_type"
                FROM
                    "Document" d
                LEFT JOIN document_sub_type dst ON dst.document_id = d.id
                WHERE d.id = $1
                LIMIT 1
`

type GetBasicCloudStorageItemMetadataRow struct {
	DocumentID   string
	Owner        string
	DocumentName string
	FileType     pgtype.Text
	SubType      NullDocumentSubTypeValue
}

func (q *Queries) GetBasicCloudStorageItemMetadata(ctx context.Context, id string) (GetBasicCloudStorageItemMetadataRow, error) {
	row := q.db.QueryRow(ctx, getBasicCloudStorageItemMetadata, id)
	var i GetBasicCloudStorageItemMetadataRow
	err := row.Scan(
		&i.DocumentID,
		&i.Owner,
		&i.DocumentName,
		&i.FileType,
		&i.SubType,
	)
	return i, err
}
