// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organization_get_organization.sql

package macrodb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAllowListOnly = `-- name: GetAllowListOnly :one
SELECT "allowListOnly" as allow_list_only
        FROM "Organization"
        WHERE id = $1
`

func (q *Queries) GetAllowListOnly(ctx context.Context, id int32) (pgtype.Bool, error) {
	row := q.db.QueryRow(ctx, getAllowListOnly, id)
	var allow_list_only pgtype.Bool
	err := row.Scan(&allow_list_only)
	return allow_list_only, err
}

const getOrganizationName = `-- name: GetOrganizationName :one
SELECT
            name
        FROM
            "Organization"
        WHERE id = $1
`

func (q *Queries) GetOrganizationName(ctx context.Context, id int32) (string, error) {
	row := q.db.QueryRow(ctx, getOrganizationName, id)
	var name string
	err := row.Scan(&name)
	return name, err
}
