// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organization_remove_organization_default_share_permission.sql

package macrodb

import (
	"context"
)

const removeOrganizationDefaultSharePermission = `-- name: RemoveOrganizationDefaultSharePermission :exec
DELETE FROM "OrganizationDefaultSharePermission"
        WHERE "organization_id" = $1
`

func (q *Queries) RemoveOrganizationDefaultSharePermission(ctx context.Context, organizationID int32) error {
	_, err := q.db.Exec(ctx, removeOrganizationDefaultSharePermission, organizationID)
	return err
}
