// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organization_remove_organization_invitation.sql

package macrodb

import (
	"context"
)

const revokeOrganizationInvitationForUser = `-- name: RevokeOrganizationInvitationForUser :exec
DELETE FROM "OrganizationInvitation" WHERE organization_id = $1 AND email = $2
`

type RevokeOrganizationInvitationForUserParams struct {
	OrganizationID int32
	Email          string
}

func (q *Queries) RevokeOrganizationInvitationForUser(ctx context.Context, arg RevokeOrganizationInvitationForUserParams) error {
	_, err := q.db.Exec(ctx, revokeOrganizationInvitationForUser, arg.OrganizationID, arg.Email)
	return err
}

const revokeOrganizationInvitationForUser2 = `-- name: RevokeOrganizationInvitationForUser2 :exec
DELETE FROM "OrganizationEmailMatches" WHERE "organizationId" = $1 AND email = $2
`

type RevokeOrganizationInvitationForUser2Params struct {
	OrganizationId int32
	Email          string
}

func (q *Queries) RevokeOrganizationInvitationForUser2(ctx context.Context, arg RevokeOrganizationInvitationForUser2Params) error {
	_, err := q.db.Exec(ctx, revokeOrganizationInvitationForUser2, arg.OrganizationId, arg.Email)
	return err
}
