// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organization_create_organization_retention_policy.sql

package macrodb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrganizationRetentionPolicy = `-- name: CreateOrganizationRetentionPolicy :exec
INSERT INTO "OrganizationRetentionPolicy" (organization_id, retention_days)
    VALUES ($1, $2)
`

type CreateOrganizationRetentionPolicyParams struct {
	OrganizationID int32
	RetentionDays  pgtype.Int4
}

func (q *Queries) CreateOrganizationRetentionPolicy(ctx context.Context, arg CreateOrganizationRetentionPolicyParams) error {
	_, err := q.db.Exec(ctx, createOrganizationRetentionPolicy, arg.OrganizationID, arg.RetentionDays)
	return err
}
