// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organization.sql

package macrodb

import (
	"context"
)

const deleteOrganizationInvitation = `-- name: DeleteOrganizationInvitation :exec
DELETE FROM "OrganizationInvitation"
        WHERE email = $1
`

func (q *Queries) DeleteOrganizationInvitation(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, deleteOrganizationInvitation, email)
	return err
}
