// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organization_remove_organization_retention_policy.sql

package macrodb

import (
	"context"
)

const removeOrganizationRetentionPolicy = `-- name: RemoveOrganizationRetentionPolicy :exec
DELETE FROM "OrganizationRetentionPolicy"
        WHERE "organization_id" = $1
`

func (q *Queries) RemoveOrganizationRetentionPolicy(ctx context.Context, organizationID int32) error {
	_, err := q.db.Exec(ctx, removeOrganizationRetentionPolicy, organizationID)
	return err
}
