// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects_get_project_get_project_by_id.sql

package macrodb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getProjectForSearch = `-- name: GetProjectForSearch :one
SELECT
                p.id,
                p.name,
                p."userId" as user_id,
                p."parentId" as parent_id,
                p."createdAt"::timestamptz as created_at,
                p."updatedAt"::timestamptz as updated_at,
                p."deletedAt"::timestamptz as deleted_at
            FROM "Project" p
            WHERE id = $1
`

type GetProjectForSearchRow struct {
	ID        string
	Name      string
	UserID    string
	ParentID  pgtype.Text
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

func (q *Queries) GetProjectForSearch(ctx context.Context, id string) (GetProjectForSearchRow, error) {
	row := q.db.QueryRow(ctx, getProjectForSearch, id)
	var i GetProjectForSearchRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UserID,
		&i.ParentID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
