// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects_delete.sql

package macrodb

import (
	"context"
)

const deleteProjectsBulkTsx = `-- name: DeleteProjectsBulkTsx :exec
DELETE FROM "SharePermission"
            WHERE id IN (
                SELECT "sharePermissionId"
                FROM "ProjectPermission"
                WHERE "projectId" = ANY($1::text[])
            )
`

func (q *Queries) DeleteProjectsBulkTsx(ctx context.Context, dollar_1 []string) error {
	_, err := q.db.Exec(ctx, deleteProjectsBulkTsx, dollar_1)
	return err
}

const deleteProjectsBulkTsx2 = `-- name: DeleteProjectsBulkTsx2 :exec
DELETE FROM "Project"
        WHERE "id" = ANY($1::text[])
`

func (q *Queries) DeleteProjectsBulkTsx2(ctx context.Context, dollar_1 []string) error {
	_, err := q.db.Exec(ctx, deleteProjectsBulkTsx2, dollar_1)
	return err
}
