// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects_get_project_get_sub_items.sql

package macrodb

import (
	"context"
)

const bulkGetAllSubProjectIds = `-- name: BulkGetAllSubProjectIds :many
WITH RECURSIVE project_hierarchy AS (
            SELECT
                p.id
            FROM "Project" p
            WHERE p."id" = ANY($1::text[]) AND p."deletedAt" IS NULL
            UNION ALL
            SELECT
                sub_p.id
            FROM "Project" sub_p
            INNER JOIN project_hierarchy ph ON sub_p."parentId" = ph.id
            WHERE sub_p."deletedAt" IS NULL
        )
        SELECT
            ph.id as "id"
        FROM project_hierarchy ph
`

func (q *Queries) BulkGetAllSubProjectIds(ctx context.Context, dollar_1 []string) ([]string, error) {
	rows, err := q.db.Query(ctx, bulkGetAllSubProjectIds, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
