// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects_get_project_history.sql

package macrodb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getProjectHistoryInfo = `-- name: GetProjectHistoryInfo :many
SELECT
            p."id" as "item_id",
            p."createdAt" as "created_at",
            p."updatedAt" as "updated_at",
            p."deletedAt" as "deleted_at",
            p."parentId" as "parent_project_id",
            uh."updatedAt" as "viewed_at",
            p."userId" as "user_id",
            p."name"
        FROM
            "Project" p
        LEFT JOIN
            "UserHistory" uh ON uh."itemId" = p."id"
                AND uh."userId" = $1
                AND uh."itemType" = 'project'
        WHERE
            p."id" = ANY($2::text[])
        ORDER BY
            p."updatedAt" DESC
`

type GetProjectHistoryInfoParams struct {
	UserId  string
	Column2 []string
}

type GetProjectHistoryInfoRow struct {
	ItemID          string
	CreatedAt       pgtype.Timestamp
	UpdatedAt       pgtype.Timestamp
	DeletedAt       pgtype.Timestamp
	ParentProjectID pgtype.Text
	ViewedAt        pgtype.Timestamp
	UserID          string
	Name            string
}

func (q *Queries) GetProjectHistoryInfo(ctx context.Context, arg GetProjectHistoryInfoParams) ([]GetProjectHistoryInfoRow, error) {
	rows, err := q.db.Query(ctx, getProjectHistoryInfo, arg.UserId, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProjectHistoryInfoRow
	for rows.Next() {
		var i GetProjectHistoryInfoRow
		if err := rows.Scan(
			&i.ItemID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ParentProjectID,
			&i.ViewedAt,
			&i.UserID,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
