// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects_get_projects.sql

package macrodb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAllProjectIdsWithUsersPaginated = `-- name: GetAllProjectIdsWithUsersPaginated :many
SELECT
            id,
            "userId" as user_id
        FROM
            "Project"
        WHERE
            "deletedAt" IS NULL
        ORDER BY
            "createdAt" DESC
        LIMIT $1 OFFSET $2
`

type GetAllProjectIdsWithUsersPaginatedParams struct {
	Limit  int32
	Offset int32
}

type GetAllProjectIdsWithUsersPaginatedRow struct {
	ID     string
	UserID string
}

func (q *Queries) GetAllProjectIdsWithUsersPaginated(ctx context.Context, arg GetAllProjectIdsWithUsersPaginatedParams) ([]GetAllProjectIdsWithUsersPaginatedRow, error) {
	rows, err := q.db.Query(ctx, getAllProjectIdsWithUsersPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllProjectIdsWithUsersPaginatedRow
	for rows.Next() {
		var i GetAllProjectIdsWithUsersPaginatedRow
		if err := rows.Scan(&i.ID, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProjectsForSearchBackfill = `-- name: GetProjectsForSearchBackfill :many
SELECT
                p.id as project_id,
                p."updatedAt"::timestamptz as updated_at
            FROM "Project" p
            WHERE p."deletedAt" IS NULL
                AND (
                    $2::timestamptz IS NULL
                    OR (p."updatedAt", p.id) > ($2, $3)
                )
                AND ($4::timestamptz IS NULL OR p."updatedAt" >= $4)
                AND ($5::timestamptz IS NULL OR p."updatedAt" <= $5)
            ORDER BY p."updatedAt" ASC, p.id ASC
            LIMIT $1
`

type GetProjectsForSearchBackfillParams struct {
	Limit     int32
	Column2   pgtype.Timestamptz
	UpdatedAt pgtype.Timestamp
	Column4   pgtype.Timestamptz
	Column5   pgtype.Timestamptz
}

type GetProjectsForSearchBackfillRow struct {
	ProjectID string
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) GetProjectsForSearchBackfill(ctx context.Context, arg GetProjectsForSearchBackfillParams) ([]GetProjectsForSearchBackfillRow, error) {
	rows, err := q.db.Query(ctx, getProjectsForSearchBackfill,
		arg.Limit,
		arg.Column2,
		arg.UpdatedAt,
		arg.Column4,
		arg.Column5,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProjectsForSearchBackfillRow
	for rows.Next() {
		var i GetProjectsForSearchBackfillRow
		if err := rows.Scan(&i.ProjectID, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProjectsToDelete = `-- name: GetProjectsToDelete :many
SELECT p.id as project_id, p."userId" as user_id
            FROM "Project" p
            WHERE p."deletedAt" IS NOT NULL AND p."deletedAt" <= $1
`

type GetProjectsToDeleteRow struct {
	ProjectID string
	UserID    string
}

func (q *Queries) GetProjectsToDelete(ctx context.Context, deletedat pgtype.Timestamp) ([]GetProjectsToDeleteRow, error) {
	rows, err := q.db.Query(ctx, getProjectsToDelete, deletedat)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProjectsToDeleteRow
	for rows.Next() {
		var i GetProjectsToDeleteRow
		if err := rows.Scan(&i.ProjectID, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubProjectIds = `-- name: GetSubProjectIds :many
SELECT
                p.id
            FROM
                "Project" p
            WHERE
                p."parentId" = ANY($1::text[])
`

func (q *Queries) GetSubProjectIds(ctx context.Context, dollar_1 []string) ([]string, error) {
	rows, err := q.db.Query(ctx, getSubProjectIds, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
