// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: share_permission_access_level_chat_tests.sql

package macrodb

import (
	"context"
)

const configureTeamLinkAccess = `-- name: ConfigureTeamLinkAccess :exec
INSERT INTO team (id, name, owner_id)
        VALUES
            ('dddddddd-dddd-dddd-dddd-000000000001', 'Chat owner team', 'user-1'),
            ('dddddddd-dddd-dddd-dddd-000000000002', 'Other team', 'user-2')
`

func (q *Queries) ConfigureTeamLinkAccess(ctx context.Context) error {
	_, err := q.db.Exec(ctx, configureTeamLinkAccess)
	return err
}

const configureTeamLinkAccess2 = `-- name: ConfigureTeamLinkAccess2 :exec
INSERT INTO team_user (user_id, team_id, team_role)
        VALUES
            ('user-1', 'dddddddd-dddd-dddd-dddd-000000000001', 'owner'),
            ('user-3', 'dddddddd-dddd-dddd-dddd-000000000001', 'member'),
            ('user-2', 'dddddddd-dddd-dddd-dddd-000000000002', 'owner'),
            ('user-public-access-only', 'dddddddd-dddd-dddd-dddd-000000000002', 'member')
`

func (q *Queries) ConfigureTeamLinkAccess2(ctx context.Context) error {
	_, err := q.db.Exec(ctx, configureTeamLinkAccess2)
	return err
}

const configureTeamLinkAccess3 = `-- name: ConfigureTeamLinkAccess3 :exec
UPDATE "SharePermission"
        SET "linkShare" = 'TEAM', "linkShareAccessLevel" = 'comment'
        WHERE id = 'sp-public-edit'
`

func (q *Queries) ConfigureTeamLinkAccess3(ctx context.Context) error {
	_, err := q.db.Exec(ctx, configureTeamLinkAccess3)
	return err
}

const configureTeamLinkAccess4 = `-- name: ConfigureTeamLinkAccess4 :exec
INSERT INTO entity_access (
            entity_id,
            entity_type,
            source_id,
            source_type,
            access_level
        )
        VALUES (
            'cccccccc-cccc-cccc-cccc-000000000001',
            'chat',
            'user-3',
            'user',
            'view'
        )
`

func (q *Queries) ConfigureTeamLinkAccess4(ctx context.Context) error {
	_, err := q.db.Exec(ctx, configureTeamLinkAccess4)
	return err
}
