// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: share_permission_channel_permission_get.sql

package macrodb

import (
	"context"
)

const getChannelSharePermissionsByChannelId = `-- name: GetChannelSharePermissionsByChannelId :many
SELECT
            channel_id,
            share_permission_id,
            access_level as "access_level"
        FROM
            "ChannelSharePermission"
        WHERE
            channel_id = $1
`

func (q *Queries) GetChannelSharePermissionsByChannelId(ctx context.Context, channelID string) ([]ChannelSharePermission, error) {
	rows, err := q.db.Query(ctx, getChannelSharePermissionsByChannelId, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChannelSharePermission
	for rows.Next() {
		var i ChannelSharePermission
		if err := rows.Scan(&i.ChannelID, &i.SharePermissionID, &i.AccessLevel); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
