// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: share_permission_channel_permission_create.sql

package macrodb

import (
	"context"
)

const insertChannelSharePermission = `-- name: InsertChannelSharePermission :exec
INSERT INTO "ChannelSharePermission" ("share_permission_id", "channel_id", "access_level")
            VALUES ($1, $2, $3)
`

type InsertChannelSharePermissionParams struct {
	SharePermissionID string
	ChannelID         string
	AccessLevel       AccessLevel
}

func (q *Queries) InsertChannelSharePermission(ctx context.Context, arg InsertChannelSharePermissionParams) error {
	_, err := q.db.Exec(ctx, insertChannelSharePermission, arg.SharePermissionID, arg.ChannelID, arg.AccessLevel)
	return err
}
