// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: team_get.sql

package macrodb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserTeams = `-- name: GetUserTeams :many
SELECT
                t.id,
                t.name,
                t.owner_id
            FROM team t
            JOIN team_user tu ON t.id = tu.team_id
            WHERE tu.user_id = $1
`

type GetUserTeamsRow struct {
	ID      pgtype.UUID
	Name    string
	OwnerID string
}

func (q *Queries) GetUserTeams(ctx context.Context, userID string) ([]GetUserTeamsRow, error) {
	rows, err := q.db.Query(ctx, getUserTeams, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserTeamsRow
	for rows.Next() {
		var i GetUserTeamsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.OwnerID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
