// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_update_user_id.sql

package macrodb

import (
	"context"
)

const getLegacyUsers = `-- name: GetLegacyUsers :many
SELECT
            u.id AS user_id,
            u.email,
            COUNT(d.id) AS document_count
        FROM
            "User" u
        LEFT JOIN
            "Document" d ON u.id = d.owner AND d."fileType" IS DISTINCT FROM 'docx'
        WHERE
            u.id NOT LIKE 'macro|%'
        GROUP BY
            u.id, u.email
        ORDER BY
            document_count DESC
`

type GetLegacyUsersRow struct {
	UserID        string
	Email         string
	DocumentCount int64
}

func (q *Queries) GetLegacyUsers(ctx context.Context) ([]GetLegacyUsersRow, error) {
	rows, err := q.db.Query(ctx, getLegacyUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLegacyUsersRow
	for rows.Next() {
		var i GetLegacyUsersRow
		if err := rows.Scan(&i.UserID, &i.Email, &i.DocumentCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLegacyUserId = `-- name: UpdateLegacyUserId :exec
UPDATE "User"
            SET id = $1
            WHERE id = $2
`

type UpdateLegacyUserIdParams struct {
	ID   string
	ID_2 string
}

func (q *Queries) UpdateLegacyUserId(ctx context.Context, arg UpdateLegacyUserIdParams) error {
	_, err := q.db.Exec(ctx, updateLegacyUserId, arg.ID, arg.ID_2)
	return err
}
