// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_get.sql

package macrodb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getMacroUserIdByEmail = `-- name: GetMacroUserIdByEmail :one
SELECT "macro_user_id"
        FROM "User"
        WHERE "email" = $1
`

func (q *Queries) GetMacroUserIdByEmail(ctx context.Context, email string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getMacroUserIdByEmail, email)
	var macro_user_id pgtype.UUID
	err := row.Scan(&macro_user_id)
	return macro_user_id, err
}

const getStripeCustomerIdByUserId = `-- name: GetStripeCustomerIdByUserId :one
SELECT "stripeCustomerId" as "stripe_customer_id"
        FROM "User"
        WHERE "id" = $1
`

func (q *Queries) GetStripeCustomerIdByUserId(ctx context.Context, id string) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getStripeCustomerIdByUserId, id)
	var stripe_customer_id pgtype.Text
	err := row.Scan(&stripe_customer_id)
	return stripe_customer_id, err
}

const getUserEmails = `-- name: GetUserEmails :one
SELECT COUNT(*) as "count"
            FROM "User" u
`

func (q *Queries) GetUserEmails(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getUserEmails)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUserEmails2 = `-- name: GetUserEmails2 :many
SELECT
            u.email
        FROM
            "User" u
        LIMIT $1 OFFSET $2
`

type GetUserEmails2Params struct {
	Limit  int32
	Offset int32
}

func (q *Queries) GetUserEmails2(ctx context.Context, arg GetUserEmails2Params) ([]string, error) {
	rows, err := q.db.Query(ctx, getUserEmails2, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var email string
		if err := rows.Scan(&email); err != nil {
			return nil, err
		}
		items = append(items, email)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserIdAndStripeCustomerIdByEmail = `-- name: GetUserIdAndStripeCustomerIdByEmail :one
SELECT "id", "stripeCustomerId" as "stripe_customer_id"
        FROM "User"
        WHERE "email" = $1
`

type GetUserIdAndStripeCustomerIdByEmailRow struct {
	ID               string
	StripeCustomerID pgtype.Text
}

func (q *Queries) GetUserIdAndStripeCustomerIdByEmail(ctx context.Context, email string) (GetUserIdAndStripeCustomerIdByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserIdAndStripeCustomerIdByEmail, email)
	var i GetUserIdAndStripeCustomerIdByEmailRow
	err := row.Scan(&i.ID, &i.StripeCustomerID)
	return i, err
}

const getUserIdByEmail = `-- name: GetUserIdByEmail :one
SELECT "id"
        FROM "User"
        WHERE "email" = $1
`

func (q *Queries) GetUserIdByEmail(ctx context.Context, email string) (string, error) {
	row := q.db.QueryRow(ctx, getUserIdByEmail, email)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getUserInfoByEmail = `-- name: GetUserInfoByEmail :one
SELECT 
            id,
            email,
            "organizationId" as "organization_id",
            macro_user_id as "macro_user_id"
        FROM "User"
        WHERE "email" = $1
`

type GetUserInfoByEmailRow struct {
	ID             string
	Email          string
	OrganizationID pgtype.Int4
	MacroUserID    pgtype.UUID
}

func (q *Queries) GetUserInfoByEmail(ctx context.Context, email string) (GetUserInfoByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserInfoByEmail, email)
	var i GetUserInfoByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.OrganizationID,
		&i.MacroUserID,
	)
	return i, err
}

const getUserMacroIdByEmail = `-- name: GetUserMacroIdByEmail :one
SELECT "macro_user_id" as "macro_user_id"
        FROM "User"
        WHERE "email" = $1
`

func (q *Queries) GetUserMacroIdByEmail(ctx context.Context, email string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getUserMacroIdByEmail, email)
	var macro_user_id pgtype.UUID
	err := row.Scan(&macro_user_id)
	return macro_user_id, err
}

const getUserMacroUserIdAndIdByEmail = `-- name: GetUserMacroUserIdAndIdByEmail :one
SELECT "macro_user_id" as "macro_user_id", "id"
        FROM "User"
        WHERE "email" = $1
`

type GetUserMacroUserIdAndIdByEmailRow struct {
	MacroUserID pgtype.UUID
	ID          string
}

func (q *Queries) GetUserMacroUserIdAndIdByEmail(ctx context.Context, email string) (GetUserMacroUserIdAndIdByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserMacroUserIdAndIdByEmail, email)
	var i GetUserMacroUserIdAndIdByEmailRow
	err := row.Scan(&i.MacroUserID, &i.ID)
	return i, err
}

const getUserProfile = `-- name: GetUserProfile :one
SELECT 
            id,
            email,
            "organizationId" as "organization_id"
        FROM "User"
        WHERE "id" = $1
`

type GetUserProfileRow struct {
	ID             string
	Email          string
	OrganizationID pgtype.Int4
}

func (q *Queries) GetUserProfile(ctx context.Context, id string) (GetUserProfileRow, error) {
	row := q.db.QueryRow(ctx, getUserProfile, id)
	var i GetUserProfileRow
	err := row.Scan(&i.ID, &i.Email, &i.OrganizationID)
	return i, err
}

const getUserProfileByFusionauthUserIdAndEmail = `-- name: GetUserProfileByFusionauthUserIdAndEmail :one
SELECT id, "organizationId" as "organization_id"
        FROM "User"
        WHERE "macro_user_id" = $1
        AND LOWER(email) = LOWER($2)
`

type GetUserProfileByFusionauthUserIdAndEmailParams struct {
	MacroUserID pgtype.UUID
	Lower       string
}

type GetUserProfileByFusionauthUserIdAndEmailRow struct {
	ID             string
	OrganizationID pgtype.Int4
}

func (q *Queries) GetUserProfileByFusionauthUserIdAndEmail(ctx context.Context, arg GetUserProfileByFusionauthUserIdAndEmailParams) (GetUserProfileByFusionauthUserIdAndEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserProfileByFusionauthUserIdAndEmail, arg.MacroUserID, arg.Lower)
	var i GetUserProfileByFusionauthUserIdAndEmailRow
	err := row.Scan(&i.ID, &i.OrganizationID)
	return i, err
}

const getUserProfilesByFusionauthUserId = `-- name: GetUserProfilesByFusionauthUserId :many
SELECT id
        FROM "User"
        WHERE "macro_user_id" = $1
`

func (q *Queries) GetUserProfilesByFusionauthUserId(ctx context.Context, macroUserID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, getUserProfilesByFusionauthUserId, macroUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
