// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_onboarding_status.sql

package macrodb

import (
	"context"
)

const getOnboardingStatus = `-- name: GetOnboardingStatus :one
SELECT "hasOnboardingDocuments"::boolean
        FROM "User"
        WHERE id = $1
`

func (q *Queries) GetOnboardingStatus(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRow(ctx, getOnboardingStatus, id)
	var hasOnboardingDocuments bool
	err := row.Scan(&hasOnboardingDocuments)
	return hasOnboardingDocuments, err
}

const setOnboardingStatus = `-- name: SetOnboardingStatus :exec
UPDATE "User"
        SET "hasOnboardingDocuments" = $1
        WHERE id = $2
`

type SetOnboardingStatusParams struct {
	HasOnboardingDocuments bool
	ID                     string
}

func (q *Queries) SetOnboardingStatus(ctx context.Context, arg SetOnboardingStatusParams) error {
	_, err := q.db.Exec(ctx, setOnboardingStatus, arg.HasOnboardingDocuments, arg.ID)
	return err
}
