// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_exists.sql

package macrodb

import (
	"context"
)

const getUsersThatDoNotExist = `-- name: GetUsersThatDoNotExist :many
SELECT "id"
        FROM "User"
        WHERE "id" = ANY($1::text[])
`

func (q *Queries) GetUsersThatDoNotExist(ctx context.Context, dollar_1 []string) ([]string, error) {
	rows, err := q.db.Query(ctx, getUsersThatDoNotExist, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
