// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_create_invite_user.sql

package macrodb

import (
	"context"
)

const inviteUser = `-- name: InviteUser :exec
INSERT INTO "OrganizationInvitation" ("organization_id", "email")
        VALUES ($1, $2)
`

type InviteUserParams struct {
	OrganizationID int32
	Email          string
}

func (q *Queries) InviteUser(ctx context.Context, arg InviteUserParams) error {
	_, err := q.db.Exec(ctx, inviteUser, arg.OrganizationID, arg.Email)
	return err
}

const inviteUser2 = `-- name: InviteUser2 :exec
INSERT INTO "OrganizationEmailMatches" ("organizationId", "email")
            VALUES ($1, $2)
            ON CONFLICT ("email") DO NOTHING
`

type InviteUser2Params struct {
	OrganizationId int32
	Email          string
}

func (q *Queries) InviteUser2(ctx context.Context, arg InviteUser2Params) error {
	_, err := q.db.Exec(ctx, inviteUser2, arg.OrganizationId, arg.Email)
	return err
}
