// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_delete_user_dss_items_delete_projects.sql

package macrodb

import (
	"context"
)

const deleteUserProjects = `-- name: DeleteUserProjects :many
SELECT id FROM "Project" WHERE "userId" = $1
`

func (q *Queries) DeleteUserProjects(ctx context.Context, userid string) ([]string, error) {
	rows, err := q.db.Query(ctx, deleteUserProjects, userid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteUserProjects2 = `-- name: DeleteUserProjects2 :exec
DELETE FROM "SharePermission" sp
        USING "ProjectPermission" pp 
        WHERE pp."sharePermissionId" = sp.id
        AND pp."projectId" = ANY($1::text[])
`

func (q *Queries) DeleteUserProjects2(ctx context.Context, dollar_1 []string) error {
	_, err := q.db.Exec(ctx, deleteUserProjects2, dollar_1)
	return err
}

const deleteUserProjects3 = `-- name: DeleteUserProjects3 :exec
DELETE FROM "Project" 
        WHERE "id" = ANY($1::text[])
`

func (q *Queries) DeleteUserProjects3(ctx context.Context, dollar_1 []string) error {
	_, err := q.db.Exec(ctx, deleteUserProjects3, dollar_1)
	return err
}
