// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_remove_remove_user_role.sql

package macrodb

import (
	"context"
)

const removeUserRole = `-- name: RemoveUserRole :exec
DELETE FROM "RolesOnUsers" WHERE "userId" = $1 AND "roleId" = $2
`

type RemoveUserRoleParams struct {
	UserId string
	RoleId string
}

func (q *Queries) RemoveUserRole(ctx context.Context, arg RemoveUserRoleParams) error {
	_, err := q.db.Exec(ctx, removeUserRole, arg.UserId, arg.RoleId)
	return err
}
