// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_permissions.sql

package macrodb

import (
	"context"
)

const getAllPermissions = `-- name: GetAllPermissions :many
SELECT 
            id,
            description 
        FROM "Permission"
`

func (q *Queries) GetAllPermissions(ctx context.Context) ([]Permission, error) {
	rows, err := q.db.Query(ctx, getAllPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Permission
	for rows.Next() {
		var i Permission
		if err := rows.Scan(&i.ID, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserPermissions2 = `-- name: GetUserPermissions2 :many
SELECT
        rop."permissionId" as permission_id
        FROM "User" u
        JOIN "RolesOnUsers" ru ON ru."userId" = u.id
        JOIN "RolesOnPermissions" rop ON rop."roleId" = ru."roleId"
        WHERE u.id = $1
`

func (q *Queries) GetUserPermissions2(ctx context.Context, id string) ([]string, error) {
	rows, err := q.db.Query(ctx, getUserPermissions2, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var permission_id string
		if err := rows.Scan(&permission_id); err != nil {
			return nil, err
		}
		items = append(items, permission_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
