// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_get_get_user_organization.sql

package macrodb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserOrganization2 = `-- name: GetUserOrganization2 :one
SELECT "organizationId" as organization_id FROM "User" WHERE id = $1
`

func (q *Queries) GetUserOrganization2(ctx context.Context, id string) (pgtype.Int4, error) {
	row := q.db.QueryRow(ctx, getUserOrganization2, id)
	var organization_id pgtype.Int4
	err := row.Scan(&organization_id)
	return organization_id, err
}
