// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_create_user.sql

package macrodb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO "macro_user" ("id", "username", "stripe_customer_id", "email", "has_trialed")
        VALUES ($1, $2, $3, $4, $5)
        RETURNING id
`

type CreateUserParams struct {
	ID               pgtype.UUID
	Username         string
	StripeCustomerID string
	Email            string
	HasTrialed       bool
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.StripeCustomerID,
		arg.Email,
		arg.HasTrialed,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createUser2 = `-- name: CreateUser2 :exec
INSERT INTO "macro_user_email_verification" ("macro_user_id", "email", "is_verified")
        VALUES ($1, $2, $3)
`

type CreateUser2Params struct {
	MacroUserID pgtype.UUID
	Email       string
	IsVerified  bool
}

func (q *Queries) CreateUser2(ctx context.Context, arg CreateUser2Params) error {
	_, err := q.db.Exec(ctx, createUser2, arg.MacroUserID, arg.Email, arg.IsVerified)
	return err
}

const createUser3 = `-- name: CreateUser3 :one
INSERT INTO "User" ("id", "email", "stripeCustomerId", "organizationId", "macro_user_id")
        VALUES ($1, $2, $3, $4, $5)
        RETURNING id
`

type CreateUser3Params struct {
	ID               string
	Email            string
	StripeCustomerId pgtype.Text
	OrganizationId   pgtype.Int4
	MacroUserID      pgtype.UUID
}

func (q *Queries) CreateUser3(ctx context.Context, arg CreateUser3Params) (string, error) {
	row := q.db.QueryRow(ctx, createUser3,
		arg.ID,
		arg.Email,
		arg.StripeCustomerId,
		arg.OrganizationId,
		arg.MacroUserID,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const createUser4 = `-- name: CreateUser4 :exec
INSERT INTO "RolesOnUsers" ("userId", "roleId")
            VALUES ($1, $2)
`

type CreateUser4Params struct {
	UserId string
	RoleId string
}

func (q *Queries) CreateUser4(ctx context.Context, arg CreateUser4Params) error {
	_, err := q.db.Exec(ctx, createUser4, arg.UserId, arg.RoleId)
	return err
}

const createUserProfile = `-- name: CreateUserProfile :one
INSERT INTO "User" ("id", "email", "organizationId", "macro_user_id")
        VALUES ($1, $2, $3, $4)
        RETURNING id
`

type CreateUserProfileParams struct {
	ID             string
	Email          string
	OrganizationId pgtype.Int4
	MacroUserID    pgtype.UUID
}

func (q *Queries) CreateUserProfile(ctx context.Context, arg CreateUserProfileParams) (string, error) {
	row := q.db.QueryRow(ctx, createUserProfile,
		arg.ID,
		arg.Email,
		arg.OrganizationId,
		arg.MacroUserID,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}
