// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_get_permissions.sql

package macrodb

import (
	"context"
)

const getUserPermissions = `-- name: GetUserPermissions :many
SELECT
          rp."roleId" AS role_id,
          rp."permissionId" AS permission_id
        FROM
          "User" u
        INNER JOIN
          "RolesOnUsers" ru ON u.id = ru."userId"
        INNER JOIN
          "RolesOnPermissions" rp ON ru."roleId" = rp."roleId"
        WHERE
          u.id = $1
`

type GetUserPermissionsRow struct {
	RoleID       string
	PermissionID string
}

func (q *Queries) GetUserPermissions(ctx context.Context, id string) ([]GetUserPermissionsRow, error) {
	rows, err := q.db.Query(ctx, getUserPermissions, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserPermissionsRow
	for rows.Next() {
		var i GetUserPermissionsRow
		if err := rows.Scan(&i.RoleID, &i.PermissionID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
