// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_get_user_name.sql

package macrodb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserName = `-- name: GetUserName :one
SELECT macro_user_id, first_name, last_name FROM macro_user_info WHERE macro_user_id = $1
`

type GetUserNameRow struct {
	MacroUserID pgtype.UUID
	FirstName   pgtype.Text
	LastName    pgtype.Text
}

func (q *Queries) GetUserName(ctx context.Context, macroUserID pgtype.UUID) (GetUserNameRow, error) {
	row := q.db.QueryRow(ctx, getUserName, macroUserID)
	var i GetUserNameRow
	err := row.Scan(&i.MacroUserID, &i.FirstName, &i.LastName)
	return i, err
}

const getUserNames = `-- name: GetUserNames :many
SELECT 
                u.id as user_profile_id, 
                mui.first_name, 
                mui.last_name
            FROM macro_user_info mui
            JOIN "User" u ON mui.macro_user_id = u.macro_user_id
            WHERE u."id" = ANY($1::text[])
`

type GetUserNamesRow struct {
	UserProfileID string
	FirstName     pgtype.Text
	LastName      pgtype.Text
}

func (q *Queries) GetUserNames(ctx context.Context, dollar_1 []string) ([]GetUserNamesRow, error) {
	rows, err := q.db.Query(ctx, getUserNames, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserNamesRow
	for rows.Next() {
		var i GetUserNamesRow
		if err := rows.Scan(&i.UserProfileID, &i.FirstName, &i.LastName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserNamesWithEmail = `-- name: GetUserNamesWithEmail :many
WITH requested_ids AS (
            SELECT DISTINCT id
            FROM (SELECT unnest($2::text[]) AS id) AS requested
        )
        SELECT
            req.id::text as "user_profile_id",
            CASE
                WHEN NULLIF(mui.first_name, 'N/A') IS NOT NULL
                  OR NULLIF(mui.last_name, 'N/A') IS NOT NULL
                THEN NULLIF(mui.first_name, 'N/A')
                ELSE SPLIT_PART(contact.name, ' ', 1)
            END::text as "first_name",
            CASE
                WHEN NULLIF(mui.first_name, 'N/A') IS NOT NULL
                  OR NULLIF(mui.last_name, 'N/A') IS NOT NULL
                THEN NULLIF(mui.last_name, 'N/A')
                ELSE CASE
                    WHEN POSITION(' ' IN contact.name) > 0
                    THEN NULLIF(TRIM(SUBSTRING(contact.name FROM POSITION(' ' IN contact.name) + 1)), '')
                    ELSE NULL
                END
            END::text as "last_name"
        FROM requested_ids req
        LEFT JOIN "User" u ON u.id = req.id
        LEFT JOIN macro_user_info mui ON mui.macro_user_id = u.macro_user_id
        LEFT JOIN LATERAL (
            SELECT ec.name
            FROM email_links li
            JOIN email_contacts ec
                ON ec.link_id = li.id
                AND ec.email_address = REPLACE(req.id, 'macro|', '')
                AND ec.name IS NOT NULL
            WHERE li.macro_id = $1
              AND NULLIF(mui.first_name, 'N/A') IS NULL
              AND NULLIF(mui.last_name, 'N/A') IS NULL
            LIMIT 1
        ) contact ON TRUE
        WHERE u.id IS NOT NULL OR contact.name IS NOT NULL
`

type GetUserNamesWithEmailParams struct {
	MacroID string
	Column2 []string
}

type GetUserNamesWithEmailRow struct {
	UserProfileID string
	FirstName     string
	LastName      string
}

func (q *Queries) GetUserNamesWithEmail(ctx context.Context, arg GetUserNamesWithEmailParams) ([]GetUserNamesWithEmailRow, error) {
	rows, err := q.db.Query(ctx, getUserNamesWithEmail, arg.MacroID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserNamesWithEmailRow
	for rows.Next() {
		var i GetUserNamesWithEmailRow
		if err := rows.Scan(&i.UserProfileID, &i.FirstName, &i.LastName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
