// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_get_invited.sql

package macrodb

import (
	"context"
)

const getInvitedUsersByOrganization = `-- name: GetInvitedUsersByOrganization :many
SELECT
            oi.email
        FROM "OrganizationInvitation" oi
        WHERE oi.organization_id = $1
`

func (q *Queries) GetInvitedUsersByOrganization(ctx context.Context, organizationID int32) ([]string, error) {
	rows, err := q.db.Query(ctx, getInvitedUsersByOrganization, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var email string
		if err := rows.Scan(&email); err != nil {
			return nil, err
		}
		items = append(items, email)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
