// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_count.sql

package macrodb

import (
	"context"
)

const countUserItems = `-- name: CountUserItems :one
SELECT COUNT(*) as "count"
            FROM "Document" d
            WHERE owner = $1 AND d."deletedAt" IS NULL
`

func (q *Queries) CountUserItems(ctx context.Context, owner string) (int64, error) {
	row := q.db.QueryRow(ctx, countUserItems, owner)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserItems2 = `-- name: CountUserItems2 :one
SELECT COUNT(*) as "count"
            FROM "Chat" c
            WHERE c."userId" = $1 and c."deletedAt" IS NULL
`

func (q *Queries) CountUserItems2(ctx context.Context, userid string) (int64, error) {
	row := q.db.QueryRow(ctx, countUserItems2, userid)
	var count int64
	err := row.Scan(&count)
	return count, err
}
