// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_document_view_location_upsert.sql

package macrodb

import (
	"context"
)

const upsertUserDocumentViewLocation = `-- name: UpsertUserDocumentViewLocation :exec
INSERT INTO "UserDocumentViewLocation" (user_id, document_id, location)
        VALUES ($1, $2, $3)
        ON CONFLICT (user_id, document_id) 
        DO UPDATE SET location = EXCLUDED.location, updated_at = NOW()
`

type UpsertUserDocumentViewLocationParams struct {
	UserID     string
	DocumentID string
	Location   string
}

func (q *Queries) UpsertUserDocumentViewLocation(ctx context.Context, arg UpsertUserDocumentViewLocationParams) error {
	_, err := q.db.Exec(ctx, upsertUserDocumentViewLocation, arg.UserID, arg.DocumentID, arg.Location)
	return err
}
