// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_get_all.sql

package macrodb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAllUserIdsStripeCustomerIdWithNullMacroUserId = `-- name: GetAllUserIdsStripeCustomerIdWithNullMacroUserId :many
SELECT
                u.id,
                u."stripeCustomerId" as "stripe_customer_id"
            FROM "User" u
            WHERE u."macro_user_id" IS NULL
                AND u.id > $1
            ORDER BY u.id ASC
            LIMIT $2
`

type GetAllUserIdsStripeCustomerIdWithNullMacroUserIdParams struct {
	ID    string
	Limit int32
}

type GetAllUserIdsStripeCustomerIdWithNullMacroUserIdRow struct {
	ID               string
	StripeCustomerID pgtype.Text
}

func (q *Queries) GetAllUserIdsStripeCustomerIdWithNullMacroUserId(ctx context.Context, arg GetAllUserIdsStripeCustomerIdWithNullMacroUserIdParams) ([]GetAllUserIdsStripeCustomerIdWithNullMacroUserIdRow, error) {
	rows, err := q.db.Query(ctx, getAllUserIdsStripeCustomerIdWithNullMacroUserId, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllUserIdsStripeCustomerIdWithNullMacroUserIdRow
	for rows.Next() {
		var i GetAllUserIdsStripeCustomerIdWithNullMacroUserIdRow
		if err := rows.Scan(&i.ID, &i.StripeCustomerID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllUserIdsStripeCustomerIdWithNullMacroUserId2 = `-- name: GetAllUserIdsStripeCustomerIdWithNullMacroUserId2 :many
SELECT
                u.id,
                u."stripeCustomerId" as "stripe_customer_id"
            FROM "User" u
            WHERE u."macro_user_id" IS NULL
            ORDER BY u.id ASC
            LIMIT $1
`

type GetAllUserIdsStripeCustomerIdWithNullMacroUserId2Row struct {
	ID               string
	StripeCustomerID pgtype.Text
}

func (q *Queries) GetAllUserIdsStripeCustomerIdWithNullMacroUserId2(ctx context.Context, limit int32) ([]GetAllUserIdsStripeCustomerIdWithNullMacroUserId2Row, error) {
	rows, err := q.db.Query(ctx, getAllUserIdsStripeCustomerIdWithNullMacroUserId2, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllUserIdsStripeCustomerIdWithNullMacroUserId2Row
	for rows.Next() {
		var i GetAllUserIdsStripeCustomerIdWithNullMacroUserId2Row
		if err := rows.Scan(&i.ID, &i.StripeCustomerID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExistingUsers = `-- name: GetExistingUsers :many
SELECT
            u.id
        FROM "User" u
        WHERE u."id" = ANY($1::text[])
`

func (q *Queries) GetExistingUsers(ctx context.Context, dollar_1 []string) ([]string, error) {
	rows, err := q.db.Query(ctx, getExistingUsers, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserIdsByOrganization = `-- name: GetUserIdsByOrganization :one
SELECT COUNT(*) as "count" FROM "User" WHERE "organizationId" = $1
`

func (q *Queries) GetUserIdsByOrganization(ctx context.Context, organizationid pgtype.Int4) (int64, error) {
	row := q.db.QueryRow(ctx, getUserIdsByOrganization, organizationid)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUserIdsByOrganization2 = `-- name: GetUserIdsByOrganization2 :many
SELECT
            u.id as user_id
        FROM "User" u
        WHERE u."organizationId" = $1
        LIMIT $2
        OFFSET $3
`

type GetUserIdsByOrganization2Params struct {
	OrganizationId pgtype.Int4
	Limit          int32
	Offset         int32
}

func (q *Queries) GetUserIdsByOrganization2(ctx context.Context, arg GetUserIdsByOrganization2Params) ([]string, error) {
	rows, err := q.db.Query(ctx, getUserIdsByOrganization2, arg.OrganizationId, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var user_id string
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersByOrganization = `-- name: GetUsersByOrganization :many
SELECT
            u.id as user_id,
            u.email as user_email,
            array_agg(DISTINCT rop."permissionId")::text[] AS permissions
        FROM "User" u
        LEFT JOIN "RolesOnUsers" rou ON rou."userId" = u.id
        LEFT JOIN "Role" r ON r.id = rou."roleId"
        LEFT JOIN "RolesOnPermissions" rop ON rop."roleId" = r.id
        WHERE u."organizationId" = $1
        GROUP BY u.id
        LIMIT $2
        OFFSET $3
`

type GetUsersByOrganizationParams struct {
	OrganizationId pgtype.Int4
	Limit          int32
	Offset         int32
}

type GetUsersByOrganizationRow struct {
	UserID      string
	UserEmail   string
	Permissions []string
}

func (q *Queries) GetUsersByOrganization(ctx context.Context, arg GetUsersByOrganizationParams) ([]GetUsersByOrganizationRow, error) {
	rows, err := q.db.Query(ctx, getUsersByOrganization, arg.OrganizationId, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsersByOrganizationRow
	for rows.Next() {
		var i GetUsersByOrganizationRow
		if err := rows.Scan(&i.UserID, &i.UserEmail, &i.Permissions); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
