// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_get_get_user_by_email.sql

package macrodb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserByEmail2 = `-- name: GetUserByEmail2 :one
SELECT "id" as user_id, "organizationId" as "organization_id" FROM "User" WHERE "email" = $1
`

type GetUserByEmail2Row struct {
	UserID         string
	OrganizationID pgtype.Int4
}

func (q *Queries) GetUserByEmail2(ctx context.Context, email string) (GetUserByEmail2Row, error) {
	row := q.db.QueryRow(ctx, getUserByEmail2, email)
	var i GetUserByEmail2Row
	err := row.Scan(&i.UserID, &i.OrganizationID)
	return i, err
}
