// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_update_profile_picture.sql

package macrodb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getProfilePictures = `-- name: GetProfilePictures :many
SELECT 
            u.id as user_profile_id, 
            mu.id as macro_user_id
        FROM macro_user mu
        JOIN "User" u ON mu.id = u.macro_user_id
        WHERE u."id" = ANY($1::text[])
`

type GetProfilePicturesRow struct {
	UserProfileID string
	MacroUserID   pgtype.UUID
}

func (q *Queries) GetProfilePictures(ctx context.Context, dollar_1 []string) ([]GetProfilePicturesRow, error) {
	rows, err := q.db.Query(ctx, getProfilePictures, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProfilePicturesRow
	for rows.Next() {
		var i GetProfilePicturesRow
		if err := rows.Scan(&i.UserProfileID, &i.MacroUserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProfilePictures2 = `-- name: GetProfilePictures2 :many
SELECT macro_user_id, profile_picture as "profile_picture", profile_picture_hash FROM macro_user_info
        WHERE "macro_user_id" = ANY($1::uuid[]) and profile_picture IS NOT NULL
`

type GetProfilePictures2Row struct {
	MacroUserID        pgtype.UUID
	ProfilePicture     pgtype.Text
	ProfilePictureHash pgtype.Text
}

func (q *Queries) GetProfilePictures2(ctx context.Context, dollar_1 []pgtype.UUID) ([]GetProfilePictures2Row, error) {
	rows, err := q.db.Query(ctx, getProfilePictures2, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProfilePictures2Row
	for rows.Next() {
		var i GetProfilePictures2Row
		if err := rows.Scan(&i.MacroUserID, &i.ProfilePicture, &i.ProfilePictureHash); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProfilePicture = `-- name: UpdateProfilePicture :exec
INSERT INTO macro_user_info (macro_user_id, profile_picture, profile_picture_hash)
        VALUES ($1, $2, $3)
        ON CONFLICT (macro_user_id)
        DO UPDATE SET 
            profile_picture = EXCLUDED.profile_picture,
            profile_picture_hash = EXCLUDED.profile_picture_hash
`

type UpdateProfilePictureParams struct {
	MacroUserID        pgtype.UUID
	ProfilePicture     pgtype.Text
	ProfilePictureHash pgtype.Text
}

func (q *Queries) UpdateProfilePicture(ctx context.Context, arg UpdateProfilePictureParams) error {
	_, err := q.db.Exec(ctx, updateProfilePicture, arg.MacroUserID, arg.ProfilePicture, arg.ProfilePictureHash)
	return err
}
