// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_organization.sql

package macrodb

import (
	"context"
)

const getOrganizationRolesForUser = `-- name: GetOrganizationRolesForUser :many
SELECT "roleId" as id
        FROM "RolesOnOrganizations"
        WHERE "organizationId" = $1
`

func (q *Queries) GetOrganizationRolesForUser(ctx context.Context, organizationid int32) ([]string, error) {
	rows, err := q.db.Query(ctx, getOrganizationRolesForUser, organizationid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrganizationRolesForUser2 = `-- name: GetOrganizationRolesForUser2 :one
SELECT "organizationId" as id
        FROM "OrganizationIT"
        WHERE "email" = $1
`

func (q *Queries) GetOrganizationRolesForUser2(ctx context.Context, email string) (int32, error) {
	row := q.db.QueryRow(ctx, getOrganizationRolesForUser2, email)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const getOrganizationRolesForUser3 = `-- name: GetOrganizationRolesForUser3 :one
SELECT "organizationId" as id
        FROM "OrganizationBilling"
        WHERE "email" = $1
`

func (q *Queries) GetOrganizationRolesForUser3(ctx context.Context, email string) (int32, error) {
	row := q.db.QueryRow(ctx, getOrganizationRolesForUser3, email)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const matchUserToOrganization = `-- name: MatchUserToOrganization :one
SELECT "organizationId" as organization_id
        FROM "OrganizationEmailMatches"
        WHERE "email" = ANY($1::text[])
`

func (q *Queries) MatchUserToOrganization(ctx context.Context, dollar_1 []string) (int32, error) {
	row := q.db.QueryRow(ctx, matchUserToOrganization, dollar_1)
	var organization_id int32
	err := row.Scan(&organization_id)
	return organization_id, err
}
