-- Queries ported from crates/comms_db_client/src/channels/

-- name: InsertChannel :one
-- Covers both create_channel (uuid generated by caller) and seed_channel
-- (caller supplies the id) -- the SQL is identical.
INSERT INTO comms_channels (id, name, owner_id, org_id, team_id, channel_type)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id;

-- name: AddChannelParticipant :exec
-- Covers the owner/member inserts inside create_channel/seed_channel as well
-- as participants::add_participant (role comes from the caller).
INSERT INTO comms_channel_participants (channel_id, role, user_id)
VALUES ($1, $2, $3);

-- name: CheckChannelsForUser :many
-- Channels from the given list the user is an active participant of.
SELECT c.id
FROM comms_channels c
INNER JOIN comms_channel_participants cp ON cp.channel_id = c.id
WHERE cp.user_id = $1 AND cp.left_at IS NULL
AND c.id = ANY(sqlc.arg(channel_ids)::uuid[]);

-- name: GetUserChannelIDs :many
WITH user_channels AS (
    SELECT DISTINCT c.id, c.created_at
    FROM comms_channels c
    INNER JOIN comms_channel_participants cp ON cp.channel_id = c.id
    WHERE cp.user_id = $1 AND cp.left_at IS NULL
)
SELECT id
FROM user_channels
ORDER BY created_at DESC;

-- name: GetAllChannelIDsPaginated :many
SELECT
    id AS channel_id
FROM comms_channels
ORDER BY created_at ASC
LIMIT $1
OFFSET $2;
