// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attachments_provider.sql

package emaildb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteMessageAttachments = `-- name: DeleteMessageAttachments :exec
DELETE FROM email_attachments WHERE message_id = $1
`

func (q *Queries) DeleteMessageAttachments(ctx context.Context, messageID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMessageAttachments, messageID)
	return err
}

const fetchAttachmentById = `-- name: FetchAttachmentById :one
SELECT 
            a.id, a.message_id, a.provider_attachment_id, 
            a.filename, a.mime_type, a.size_bytes, 
            a.content_id, eas.sfs_id as "sfs_id", a.created_at, m.provider_id as "message_provider_id"
        FROM email_attachments a
        JOIN email_messages m ON a.message_id = m.id
        LEFT JOIN email_attachments_sfs eas ON a.id = eas.attachment_id
        WHERE a.id = $1 AND m.link_id = $2
`

type FetchAttachmentByIdParams struct {
	ID     pgtype.UUID
	LinkID pgtype.UUID
}

type FetchAttachmentByIdRow struct {
	ID                   pgtype.UUID
	MessageID            pgtype.UUID
	ProviderAttachmentID pgtype.Text
	Filename             pgtype.Text
	MimeType             pgtype.Text
	SizeBytes            pgtype.Int8
	ContentID            pgtype.Text
	SfsID                pgtype.UUID
	CreatedAt            pgtype.Timestamptz
	MessageProviderID    pgtype.Text
}

func (q *Queries) FetchAttachmentById(ctx context.Context, arg FetchAttachmentByIdParams) (FetchAttachmentByIdRow, error) {
	row := q.db.QueryRow(ctx, fetchAttachmentById, arg.ID, arg.LinkID)
	var i FetchAttachmentByIdRow
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.ProviderAttachmentID,
		&i.Filename,
		&i.MimeType,
		&i.SizeBytes,
		&i.ContentID,
		&i.SfsID,
		&i.CreatedAt,
		&i.MessageProviderID,
	)
	return i, err
}

const fetchDbAttachmentsInBulk = `-- name: FetchDbAttachmentsInBulk :many
SELECT ea.id, ea.message_id, ea.provider_attachment_id, ea.filename, ea.mime_type, ea.size_bytes, ea.content_id, eas.sfs_id as "sfs_id", ea.created_at
        FROM email_attachments ea
        LEFT JOIN email_attachments_sfs eas ON ea.id = eas.attachment_id
        WHERE ea."message_id" = ANY($1::uuid[])
        ORDER BY ea.message_id, ea.filename NULLS LAST
`

type FetchDbAttachmentsInBulkRow struct {
	ID                   pgtype.UUID
	MessageID            pgtype.UUID
	ProviderAttachmentID pgtype.Text
	Filename             pgtype.Text
	MimeType             pgtype.Text
	SizeBytes            pgtype.Int8
	ContentID            pgtype.Text
	SfsID                pgtype.UUID
	CreatedAt            pgtype.Timestamptz
}

func (q *Queries) FetchDbAttachmentsInBulk(ctx context.Context, dollar_1 []pgtype.UUID) ([]FetchDbAttachmentsInBulkRow, error) {
	rows, err := q.db.Query(ctx, fetchDbAttachmentsInBulk, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FetchDbAttachmentsInBulkRow
	for rows.Next() {
		var i FetchDbAttachmentsInBulkRow
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.ProviderAttachmentID,
			&i.Filename,
			&i.MimeType,
			&i.SizeBytes,
			&i.ContentID,
			&i.SfsID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAttachmentsByThreadIds = `-- name: GetAttachmentsByThreadIds :many
SELECT 
            a.id,
            a.message_id,
            a.provider_attachment_id,
            a.filename,
            a.mime_type,
            a.size_bytes,
            a.content_id,
            eas.sfs_id as "sfs_id",
            a.created_at,
            m.thread_id
        FROM 
            email_attachments a
        JOIN
            email_messages m ON a.message_id = m.id
        LEFT JOIN
            email_attachments_sfs eas ON a.id = eas.attachment_id
        WHERE
            m."thread_id" = ANY($1::uuid[])
        ORDER BY 
            a.created_at ASC
`

type GetAttachmentsByThreadIdsRow struct {
	ID                   pgtype.UUID
	MessageID            pgtype.UUID
	ProviderAttachmentID pgtype.Text
	Filename             pgtype.Text
	MimeType             pgtype.Text
	SizeBytes            pgtype.Int8
	ContentID            pgtype.Text
	SfsID                pgtype.UUID
	CreatedAt            pgtype.Timestamptz
	ThreadID             pgtype.UUID
}

func (q *Queries) GetAttachmentsByThreadIds(ctx context.Context, dollar_1 []pgtype.UUID) ([]GetAttachmentsByThreadIdsRow, error) {
	rows, err := q.db.Query(ctx, getAttachmentsByThreadIds, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAttachmentsByThreadIdsRow
	for rows.Next() {
		var i GetAttachmentsByThreadIdsRow
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.ProviderAttachmentID,
			&i.Filename,
			&i.MimeType,
			&i.SizeBytes,
			&i.ContentID,
			&i.SfsID,
			&i.CreatedAt,
			&i.ThreadID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDocumentIdByAttId = `-- name: GetDocumentIdByAttId :one
SELECT document_id
        FROM document_email de
        INNER JOIN "Document" d on de.document_id = d.id
        INNER JOIN email_attachments ea on de.email_attachment_id = ea.id
        INNER JOIN email_messages em on ea.message_id = em.id
        WHERE email_attachment_id = $1 AND d."deletedAt" IS NULL
`

func (q *Queries) GetDocumentIdByAttId(ctx context.Context, emailAttachmentID pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getDocumentIdByAttId, emailAttachmentID)
	var document_id string
	err := row.Scan(&document_id)
	return document_id, err
}

const getDocumentIdByAttIdAndLink = `-- name: GetDocumentIdByAttIdAndLink :one
SELECT document_id
        FROM document_email de
        INNER JOIN "Document" d on de.document_id = d.id
        INNER JOIN email_attachments ea on de.email_attachment_id = ea.id
        INNER JOIN email_messages em on ea.message_id = em.id
        WHERE em.link_id = $1 AND email_attachment_id = $2 AND d."deletedAt" IS NULL
`

type GetDocumentIdByAttIdAndLinkParams struct {
	LinkID            pgtype.UUID
	EmailAttachmentID pgtype.UUID
}

func (q *Queries) GetDocumentIdByAttIdAndLink(ctx context.Context, arg GetDocumentIdByAttIdAndLinkParams) (string, error) {
	row := q.db.QueryRow(ctx, getDocumentIdByAttIdAndLink, arg.LinkID, arg.EmailAttachmentID)
	var document_id string
	err := row.Scan(&document_id)
	return document_id, err
}

const getThreadIdForAttachment = `-- name: GetThreadIdForAttachment :one
SELECT et.id as thread_id, et.link_id
        FROM email_attachments ea
        INNER JOIN email_messages em ON ea.message_id = em.id
        INNER JOIN email_threads et ON em.thread_id = et.id
        WHERE ea.id = $1
`

type GetThreadIdForAttachmentRow struct {
	ThreadID pgtype.UUID
	LinkID   pgtype.UUID
}

func (q *Queries) GetThreadIdForAttachment(ctx context.Context, id pgtype.UUID) (GetThreadIdForAttachmentRow, error) {
	row := q.db.QueryRow(ctx, getThreadIdForAttachment, id)
	var i GetThreadIdForAttachmentRow
	err := row.Scan(&i.ThreadID, &i.LinkID)
	return i, err
}

const insertAttachments = `-- name: InsertAttachments :many
SELECT ea.id, ea.message_id, ea.provider_attachment_id, ea.filename, ea.mime_type, ea.size_bytes, ea.content_id, eas.sfs_id as "sfs_id", ea.created_at
        FROM email_attachments ea LEFT JOIN email_attachments_sfs eas on ea.id = eas.attachment_id
        WHERE message_id = $1
`

type InsertAttachmentsRow struct {
	ID                   pgtype.UUID
	MessageID            pgtype.UUID
	ProviderAttachmentID pgtype.Text
	Filename             pgtype.Text
	MimeType             pgtype.Text
	SizeBytes            pgtype.Int8
	ContentID            pgtype.Text
	SfsID                pgtype.UUID
	CreatedAt            pgtype.Timestamptz
}

func (q *Queries) InsertAttachments(ctx context.Context, messageID pgtype.UUID) ([]InsertAttachmentsRow, error) {
	rows, err := q.db.Query(ctx, insertAttachments, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InsertAttachmentsRow
	for rows.Next() {
		var i InsertAttachmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.MessageID,
			&i.ProviderAttachmentID,
			&i.Filename,
			&i.MimeType,
			&i.SizeBytes,
			&i.ContentID,
			&i.SfsID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAttachments2 = `-- name: InsertAttachments2 :exec
DELETE FROM email_attachments
            WHERE "id" = ANY($1::uuid[])
`

func (q *Queries) InsertAttachments2(ctx context.Context, dollar_1 []pgtype.UUID) error {
	_, err := q.db.Exec(ctx, insertAttachments2, dollar_1)
	return err
}

const insertAttachments3 = `-- name: InsertAttachments3 :exec
WITH input_rows (
            id, message_id, provider_attachment_id, filename, mime_type, size_bytes, content_id
        ) AS (
           SELECT unnest($1::uuid[]), unnest($2::uuid[]), unnest($3::text[]), unnest($4::varchar[]), unnest($5::varchar[]), unnest($6::bigint[]), unnest($7::varchar[])
        )
        INSERT INTO email_attachments (
            id, message_id, provider_attachment_id, filename, mime_type, size_bytes, content_id
        )
        SELECT id, message_id, provider_attachment_id, filename, mime_type, size_bytes, content_id
        FROM input_rows
        ON CONFLICT (message_id, provider_attachment_id)
        DO NOTHING
`

type InsertAttachments3Params struct {
	Column1 []pgtype.UUID
	Column2 []pgtype.UUID
	Column3 []string
	Column4 []string
	Column5 []string
	Column6 []int64
	Column7 []string
}

func (q *Queries) InsertAttachments3(ctx context.Context, arg InsertAttachments3Params) error {
	_, err := q.db.Exec(ctx, insertAttachments3,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
	)
	return err
}

const syncThreadCalendarFlag = `-- name: SyncThreadCalendarFlag :one
SELECT thread_id FROM email_messages WHERE id = $1
`

func (q *Queries) SyncThreadCalendarFlag(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, syncThreadCalendarFlag, id)
	var thread_id pgtype.UUID
	err := row.Scan(&thread_id)
	return thread_id, err
}
