// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attachments_sfs.sql

package emaildb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteAttachmentSfs = `-- name: DeleteAttachmentSfs :exec
DELETE FROM email_attachments_sfs
        WHERE id = $1
`

func (q *Queries) DeleteAttachmentSfs(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAttachmentSfs, id)
	return err
}

const insertAttachmentSfs = `-- name: InsertAttachmentSfs :exec
INSERT INTO email_attachments_sfs (id, attachment_id, sfs_id)
        SELECT $1, $2, $3
        WHERE $2::uuid IS NULL
           OR EXISTS (SELECT 1 FROM email_attachments WHERE id = $2)
`

type InsertAttachmentSfsParams struct {
	ID           pgtype.UUID
	AttachmentID pgtype.UUID
	SfsID        pgtype.UUID
}

func (q *Queries) InsertAttachmentSfs(ctx context.Context, arg InsertAttachmentSfsParams) error {
	_, err := q.db.Exec(ctx, insertAttachmentSfs, arg.ID, arg.AttachmentID, arg.SfsID)
	return err
}
