// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: backfill_job_insert.sql

package emaildb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBackfillJob = `-- name: CreateBackfillJob :one
INSERT INTO email_backfill_jobs (id, link_id, fusionauth_user_id, threads_requested_limit, status, is_recovery)
        VALUES ($1, $2, $3, $4, 'Init', $5)
        ON CONFLICT (link_id) WHERE status IN ('Init', 'InProgress') DO NOTHING
        RETURNING
            id,
            link_id,
            fusionauth_user_id,
            threads_requested_limit,
            total_threads,
            threads_retrieved_count,
            status as "status",
            created_at,
            updated_at
`

type CreateBackfillJobParams struct {
	ID                    pgtype.UUID
	LinkID                pgtype.UUID
	FusionauthUserID      string
	ThreadsRequestedLimit pgtype.Int4
	IsRecovery            bool
}

type CreateBackfillJobRow struct {
	ID                    pgtype.UUID
	LinkID                pgtype.UUID
	FusionauthUserID      string
	ThreadsRequestedLimit pgtype.Int4
	TotalThreads          int32
	ThreadsRetrievedCount int32
	Status                EmailBackfillJobStatus
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}

func (q *Queries) CreateBackfillJob(ctx context.Context, arg CreateBackfillJobParams) (CreateBackfillJobRow, error) {
	row := q.db.QueryRow(ctx, createBackfillJob,
		arg.ID,
		arg.LinkID,
		arg.FusionauthUserID,
		arg.ThreadsRequestedLimit,
		arg.IsRecovery,
	)
	var i CreateBackfillJobRow
	err := row.Scan(
		&i.ID,
		&i.LinkID,
		&i.FusionauthUserID,
		&i.ThreadsRequestedLimit,
		&i.TotalThreads,
		&i.ThreadsRetrievedCount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
