// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: backfill_job_update.sql

package emaildb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelActiveJobsByLinkId = `-- name: CancelActiveJobsByLinkId :exec
UPDATE email_backfill_jobs
        SET status = $1::email_backfill_job_status, updated_at = now()
        WHERE link_id = $2
        AND status IN ('Init', 'InProgress')
`

type CancelActiveJobsByLinkIdParams struct {
	Column1 EmailBackfillJobStatus
	LinkID  pgtype.UUID
}

func (q *Queries) CancelActiveJobsByLinkId(ctx context.Context, arg CancelActiveJobsByLinkIdParams) error {
	_, err := q.db.Exec(ctx, cancelActiveJobsByLinkId, arg.Column1, arg.LinkID)
	return err
}

const claimCompletionEffects = `-- name: ClaimCompletionEffects :one
UPDATE email_backfill_completion_outbox
        SET effects_lease_token = $2,
            effects_lease_expires_at = now() + interval '2 minutes'
        WHERE backfill_job_id = $1
          AND completed_at IS NULL
          AND (
              effects_lease_token IS NULL
              OR effects_lease_expires_at < now()
          )
        RETURNING effects_lease_token AS "effects_lease_token"
`

type ClaimCompletionEffectsParams struct {
	BackfillJobID     pgtype.UUID
	EffectsLeaseToken pgtype.UUID
}

func (q *Queries) ClaimCompletionEffects(ctx context.Context, arg ClaimCompletionEffectsParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, claimCompletionEffects, arg.BackfillJobID, arg.EffectsLeaseToken)
	var effects_lease_token pgtype.UUID
	err := row.Scan(&effects_lease_token)
	return effects_lease_token, err
}

const claimInitLease = `-- name: ClaimInitLease :one
UPDATE email_backfill_jobs
        SET init_lease_token = $2,
            init_lease_expires_at = now() + interval '2 minutes',
            updated_at = now()
        WHERE id = $1
          AND status = 'Init'
          AND initialized_at IS NULL
          AND (
              init_lease_expires_at IS NULL
              OR init_lease_expires_at < now()
          )
        RETURNING init_lease_token AS "init_lease_token"
`

type ClaimInitLeaseParams struct {
	ID             pgtype.UUID
	InitLeaseToken pgtype.UUID
}

func (q *Queries) ClaimInitLease(ctx context.Context, arg ClaimInitLeaseParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, claimInitLease, arg.ID, arg.InitLeaseToken)
	var init_lease_token pgtype.UUID
	err := row.Scan(&init_lease_token)
	return init_lease_token, err
}

const claimInitLease2 = `-- name: ClaimInitLease2 :one
SELECT status::text AS "status", initialized_at
        FROM email_backfill_jobs
        WHERE id = $1
`

type ClaimInitLease2Row struct {
	Status        string
	InitializedAt pgtype.Timestamptz
}

func (q *Queries) ClaimInitLease2(ctx context.Context, id pgtype.UUID) (ClaimInitLease2Row, error) {
	row := q.db.QueryRow(ctx, claimInitLease2, id)
	var i ClaimInitLease2Row
	err := row.Scan(&i.Status, &i.InitializedAt)
	return i, err
}

const completeBackfillJob = `-- name: CompleteBackfillJob :exec
UPDATE email_backfill_jobs
        SET status = 'Complete',
            initialized_at = COALESCE(initialized_at, now()),
            init_lease_token = NULL,
            init_lease_expires_at = NULL,
            updated_at = now()
        WHERE id = $1
          AND (
              (
                  status = 'Init'
                  AND $2::uuid IS NOT NULL
                  AND init_lease_token = $2
                  AND init_lease_expires_at > now()
              )
              OR (
                  status = 'InProgress'
                  AND $2::uuid IS NULL
              )
          )
`

type CompleteBackfillJobParams struct {
	ID      pgtype.UUID
	Column2 pgtype.UUID
}

func (q *Queries) CompleteBackfillJob(ctx context.Context, arg CompleteBackfillJobParams) error {
	_, err := q.db.Exec(ctx, completeBackfillJob, arg.ID, arg.Column2)
	return err
}

const completeBackfillJob2 = `-- name: CompleteBackfillJob2 :one
SELECT status::text AS "status"
            FROM email_backfill_jobs
            WHERE id = $1
`

func (q *Queries) CompleteBackfillJob2(ctx context.Context, id pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, completeBackfillJob2, id)
	var status string
	err := row.Scan(&status)
	return status, err
}

const completeBackfillJob3 = `-- name: CompleteBackfillJob3 :exec
INSERT INTO email_backfill_completion_outbox (id, backfill_job_id)
        VALUES ($1, $2)
        ON CONFLICT (backfill_job_id) DO NOTHING
`

type CompleteBackfillJob3Params struct {
	ID            pgtype.UUID
	BackfillJobID pgtype.UUID
}

func (q *Queries) CompleteBackfillJob3(ctx context.Context, arg CompleteBackfillJob3Params) error {
	_, err := q.db.Exec(ctx, completeBackfillJob3, arg.ID, arg.BackfillJobID)
	return err
}

const completionEffectsPending = `-- name: CompletionEffectsPending :one
SELECT (completed_at IS NULL)::bool AS "pending"
        FROM email_backfill_completion_outbox
        WHERE backfill_job_id = $1
`

func (q *Queries) CompletionEffectsPending(ctx context.Context, backfillJobID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, completionEffectsPending, backfillJobID)
	var pending bool
	err := row.Scan(&pending)
	return pending, err
}

const failBackfillJob = `-- name: FailBackfillJob :exec
UPDATE email_backfill_jobs
        SET status = 'Failed',
            updated_at = now()
        WHERE id = $1
          AND status IN ('Init', 'InProgress')
`

func (q *Queries) FailBackfillJob(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, failBackfillJob, id)
	return err
}

const finalizeInitialization = `-- name: FinalizeInitialization :exec
INSERT INTO email_backfill_init_outbox (id, backfill_job_id)
        VALUES ($1, $2)
        ON CONFLICT (backfill_job_id) DO NOTHING
`

type FinalizeInitializationParams struct {
	ID            pgtype.UUID
	BackfillJobID pgtype.UUID
}

func (q *Queries) FinalizeInitialization(ctx context.Context, arg FinalizeInitializationParams) error {
	_, err := q.db.Exec(ctx, finalizeInitialization, arg.ID, arg.BackfillJobID)
	return err
}

const finalizeInitialization2 = `-- name: FinalizeInitialization2 :exec
UPDATE email_backfill_jobs
        SET status = 'InProgress',
            initialized_at = now(),
            init_lease_token = NULL,
            init_lease_expires_at = NULL,
            updated_at = now()
        WHERE id = $1
          AND status = 'Init'
          AND init_lease_token = $2
          AND init_lease_expires_at > now()
`

type FinalizeInitialization2Params struct {
	ID             pgtype.UUID
	InitLeaseToken pgtype.UUID
}

func (q *Queries) FinalizeInitialization2(ctx context.Context, arg FinalizeInitialization2Params) error {
	_, err := q.db.Exec(ctx, finalizeInitialization2, arg.ID, arg.InitLeaseToken)
	return err
}

const markCompletionEffectsComplete = `-- name: MarkCompletionEffectsComplete :exec
UPDATE email_backfill_completion_outbox
        SET completed_at = now()
        WHERE backfill_job_id = $1
          AND completed_at IS NULL
          AND effects_lease_token = $2
          AND effects_lease_expires_at > now()
`

type MarkCompletionEffectsCompleteParams struct {
	BackfillJobID     pgtype.UUID
	EffectsLeaseToken pgtype.UUID
}

func (q *Queries) MarkCompletionEffectsComplete(ctx context.Context, arg MarkCompletionEffectsCompleteParams) error {
	_, err := q.db.Exec(ctx, markCompletionEffectsComplete, arg.BackfillJobID, arg.EffectsLeaseToken)
	return err
}

const releaseCompletionEffects = `-- name: ReleaseCompletionEffects :exec
UPDATE email_backfill_completion_outbox
        SET effects_lease_token = NULL,
            effects_lease_expires_at = NULL
        WHERE backfill_job_id = $1
          AND completed_at IS NULL
          AND effects_lease_token = $2
`

type ReleaseCompletionEffectsParams struct {
	BackfillJobID     pgtype.UUID
	EffectsLeaseToken pgtype.UUID
}

func (q *Queries) ReleaseCompletionEffects(ctx context.Context, arg ReleaseCompletionEffectsParams) error {
	_, err := q.db.Exec(ctx, releaseCompletionEffects, arg.BackfillJobID, arg.EffectsLeaseToken)
	return err
}

const releaseInitLease = `-- name: ReleaseInitLease :exec
UPDATE email_backfill_jobs
        SET init_lease_token = NULL,
            init_lease_expires_at = NULL,
            updated_at = now()
        WHERE id = $1
          AND status = 'Init'
          AND init_lease_token = $2
`

type ReleaseInitLeaseParams struct {
	ID             pgtype.UUID
	InitLeaseToken pgtype.UUID
}

func (q *Queries) ReleaseInitLease(ctx context.Context, arg ReleaseInitLeaseParams) error {
	_, err := q.db.Exec(ctx, releaseInitLease, arg.ID, arg.InitLeaseToken)
	return err
}

const renewCompletionEffects = `-- name: RenewCompletionEffects :exec
UPDATE email_backfill_completion_outbox
        SET effects_lease_expires_at = now() + interval '2 minutes'
        WHERE backfill_job_id = $1
          AND completed_at IS NULL
          AND effects_lease_token = $2
          AND effects_lease_expires_at > now()
`

type RenewCompletionEffectsParams struct {
	BackfillJobID     pgtype.UUID
	EffectsLeaseToken pgtype.UUID
}

func (q *Queries) RenewCompletionEffects(ctx context.Context, arg RenewCompletionEffectsParams) error {
	_, err := q.db.Exec(ctx, renewCompletionEffects, arg.BackfillJobID, arg.EffectsLeaseToken)
	return err
}

const renewInitLease = `-- name: RenewInitLease :exec
UPDATE email_backfill_jobs
        SET init_lease_expires_at = now() + interval '2 minutes',
            updated_at = now()
        WHERE id = $1
          AND status = 'Init'
          AND init_lease_token = $2
          AND init_lease_expires_at > now()
`

type RenewInitLeaseParams struct {
	ID             pgtype.UUID
	InitLeaseToken pgtype.UUID
}

func (q *Queries) RenewInitLease(ctx context.Context, arg RenewInitLeaseParams) error {
	_, err := q.db.Exec(ctx, renewInitLease, arg.ID, arg.InitLeaseToken)
	return err
}

const updateBackfillJobStatus = `-- name: UpdateBackfillJobStatus :exec
UPDATE email_backfill_jobs
        SET status = $1::email_backfill_job_status, updated_at = now()
        WHERE id = $2
`

type UpdateBackfillJobStatusParams struct {
	Column1 EmailBackfillJobStatus
	ID      pgtype.UUID
}

func (q *Queries) UpdateBackfillJobStatus(ctx context.Context, arg UpdateBackfillJobStatusParams) error {
	_, err := q.db.Exec(ctx, updateBackfillJobStatus, arg.Column1, arg.ID)
	return err
}

const updateJobThreadsRetrievedCount = `-- name: UpdateJobThreadsRetrievedCount :exec
UPDATE email_backfill_jobs
        SET threads_retrieved_count = threads_retrieved_count + $1, updated_at = now()
        WHERE id = $2
`

type UpdateJobThreadsRetrievedCountParams struct {
	ThreadsRetrievedCount int32
	ID                    pgtype.UUID
}

func (q *Queries) UpdateJobThreadsRetrievedCount(ctx context.Context, arg UpdateJobThreadsRetrievedCountParams) error {
	_, err := q.db.Exec(ctx, updateJobThreadsRetrievedCount, arg.ThreadsRetrievedCount, arg.ID)
	return err
}

const updateJobTotalThreads = `-- name: UpdateJobTotalThreads :exec
UPDATE email_backfill_jobs
        SET total_threads = $1, updated_at = now()
        WHERE id = $2
`

type UpdateJobTotalThreadsParams struct {
	TotalThreads int32
	ID           pgtype.UUID
}

func (q *Queries) UpdateJobTotalThreads(ctx context.Context, arg UpdateJobTotalThreadsParams) error {
	_, err := q.db.Exec(ctx, updateJobTotalThreads, arg.TotalThreads, arg.ID)
	return err
}
