// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: backfill_job_get.sql

package emaildb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getActiveBackfillJob = `-- name: GetActiveBackfillJob :one
SELECT
            id,
            link_id,
            fusionauth_user_id,
            threads_requested_limit,
            total_threads,
            threads_retrieved_count,
            status as "status",
            created_at,
            updated_at
        FROM email_backfill_jobs
        WHERE link_id = $1 AND status IN ('Init', 'InProgress')
`

type GetActiveBackfillJobRow struct {
	ID                    pgtype.UUID
	LinkID                pgtype.UUID
	FusionauthUserID      string
	ThreadsRequestedLimit pgtype.Int4
	TotalThreads          int32
	ThreadsRetrievedCount int32
	Status                EmailBackfillJobStatus
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}

func (q *Queries) GetActiveBackfillJob(ctx context.Context, linkID pgtype.UUID) (GetActiveBackfillJobRow, error) {
	row := q.db.QueryRow(ctx, getActiveBackfillJob, linkID)
	var i GetActiveBackfillJobRow
	err := row.Scan(
		&i.ID,
		&i.LinkID,
		&i.FusionauthUserID,
		&i.ThreadsRequestedLimit,
		&i.TotalThreads,
		&i.ThreadsRetrievedCount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAllJobsByFusionauthUserId = `-- name: GetAllJobsByFusionauthUserId :many
SELECT
            id,
            link_id,
            fusionauth_user_id,
            threads_requested_limit,
            total_threads,
            threads_retrieved_count,
            status as "status",
            created_at,
            updated_at
        FROM email_backfill_jobs
        WHERE fusionauth_user_id = $1
        ORDER BY created_at DESC
        LIMIT 100
`

type GetAllJobsByFusionauthUserIdRow struct {
	ID                    pgtype.UUID
	LinkID                pgtype.UUID
	FusionauthUserID      string
	ThreadsRequestedLimit pgtype.Int4
	TotalThreads          int32
	ThreadsRetrievedCount int32
	Status                EmailBackfillJobStatus
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}

func (q *Queries) GetAllJobsByFusionauthUserId(ctx context.Context, fusionauthUserID string) ([]GetAllJobsByFusionauthUserIdRow, error) {
	rows, err := q.db.Query(ctx, getAllJobsByFusionauthUserId, fusionauthUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllJobsByFusionauthUserIdRow
	for rows.Next() {
		var i GetAllJobsByFusionauthUserIdRow
		if err := rows.Scan(
			&i.ID,
			&i.LinkID,
			&i.FusionauthUserID,
			&i.ThreadsRequestedLimit,
			&i.TotalThreads,
			&i.ThreadsRetrievedCount,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBackfillJob = `-- name: GetBackfillJob :one
SELECT
            id,
            link_id,
            fusionauth_user_id,
            threads_requested_limit,
            total_threads,
            threads_retrieved_count,
            status as "status",
            created_at,
            updated_at
        FROM email_backfill_jobs
        WHERE id = $1
`

type GetBackfillJobRow struct {
	ID                    pgtype.UUID
	LinkID                pgtype.UUID
	FusionauthUserID      string
	ThreadsRequestedLimit pgtype.Int4
	TotalThreads          int32
	ThreadsRetrievedCount int32
	Status                EmailBackfillJobStatus
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}

func (q *Queries) GetBackfillJob(ctx context.Context, id pgtype.UUID) (GetBackfillJobRow, error) {
	row := q.db.QueryRow(ctx, getBackfillJob, id)
	var i GetBackfillJobRow
	err := row.Scan(
		&i.ID,
		&i.LinkID,
		&i.FusionauthUserID,
		&i.ThreadsRequestedLimit,
		&i.TotalThreads,
		&i.ThreadsRetrievedCount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBackfillJobWithLinkId = `-- name: GetBackfillJobWithLinkId :one
SELECT
            id,
            link_id,
            fusionauth_user_id,
            threads_requested_limit,
            total_threads,
            threads_retrieved_count,
            status as "status",
            created_at,
            updated_at
        FROM email_backfill_jobs
        WHERE id = $1
        AND link_id = $2
`

type GetBackfillJobWithLinkIdParams struct {
	ID     pgtype.UUID
	LinkID pgtype.UUID
}

type GetBackfillJobWithLinkIdRow struct {
	ID                    pgtype.UUID
	LinkID                pgtype.UUID
	FusionauthUserID      string
	ThreadsRequestedLimit pgtype.Int4
	TotalThreads          int32
	ThreadsRetrievedCount int32
	Status                EmailBackfillJobStatus
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}

func (q *Queries) GetBackfillJobWithLinkId(ctx context.Context, arg GetBackfillJobWithLinkIdParams) (GetBackfillJobWithLinkIdRow, error) {
	row := q.db.QueryRow(ctx, getBackfillJobWithLinkId, arg.ID, arg.LinkID)
	var i GetBackfillJobWithLinkIdRow
	err := row.Scan(
		&i.ID,
		&i.LinkID,
		&i.FusionauthUserID,
		&i.ThreadsRequestedLimit,
		&i.TotalThreads,
		&i.ThreadsRetrievedCount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestBackfillJobByLinkId = `-- name: GetLatestBackfillJobByLinkId :one
SELECT
            id,
            link_id,
            fusionauth_user_id,
            threads_requested_limit,
            total_threads,
            threads_retrieved_count,
            status as "status",
            created_at,
            updated_at
        FROM email_backfill_jobs
        WHERE link_id = $1
        ORDER BY created_at DESC
        LIMIT 1
`

type GetLatestBackfillJobByLinkIdRow struct {
	ID                    pgtype.UUID
	LinkID                pgtype.UUID
	FusionauthUserID      string
	ThreadsRequestedLimit pgtype.Int4
	TotalThreads          int32
	ThreadsRetrievedCount int32
	Status                EmailBackfillJobStatus
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}

func (q *Queries) GetLatestBackfillJobByLinkId(ctx context.Context, linkID pgtype.UUID) (GetLatestBackfillJobByLinkIdRow, error) {
	row := q.db.QueryRow(ctx, getLatestBackfillJobByLinkId, linkID)
	var i GetLatestBackfillJobByLinkIdRow
	err := row.Scan(
		&i.ID,
		&i.LinkID,
		&i.FusionauthUserID,
		&i.ThreadsRequestedLimit,
		&i.TotalThreads,
		&i.ThreadsRetrievedCount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
