// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contacts_delete.sql

package emaildb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteMessageRecipients = `-- name: DeleteMessageRecipients :exec
DELETE FROM email_message_recipients WHERE message_id = $1
`

func (q *Queries) DeleteMessageRecipients(ctx context.Context, messageID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMessageRecipients, messageID)
	return err
}
