// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contacts_upsert_message.sql

package emaildb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const fetchContactsByEmails = `-- name: FetchContactsByEmails :many
SELECT id, email_address
        FROM email_contacts
        WHERE link_id = $1 AND "email_address" = ANY($2::varchar(320)[])
`

type FetchContactsByEmailsParams struct {
	LinkID  pgtype.UUID
	Column2 []string
}

type FetchContactsByEmailsRow struct {
	ID           pgtype.UUID
	EmailAddress string
}

func (q *Queries) FetchContactsByEmails(ctx context.Context, arg FetchContactsByEmailsParams) ([]FetchContactsByEmailsRow, error) {
	rows, err := q.db.Query(ctx, fetchContactsByEmails, arg.LinkID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FetchContactsByEmailsRow
	for rows.Next() {
		var i FetchContactsByEmailsRow
		if err := rows.Scan(&i.ID, &i.EmailAddress); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertNewContacts = `-- name: InsertNewContacts :many
INSERT INTO email_contacts (id, link_id, email_address, name)
        SELECT unnest($1::uuid[]), unnest($2::uuid[]), unnest($3::text[]), unnest($4::text[])
        ON CONFLICT (link_id, email_address) DO NOTHING
        RETURNING id, email_address
`

type InsertNewContactsParams struct {
	Column1 []pgtype.UUID
	Column2 []pgtype.UUID
	Column3 []string
	Column4 []string
}

type InsertNewContactsRow struct {
	ID           pgtype.UUID
	EmailAddress string
}

func (q *Queries) InsertNewContacts(ctx context.Context, arg InsertNewContactsParams) ([]InsertNewContactsRow, error) {
	rows, err := q.db.Query(ctx, insertNewContacts,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InsertNewContactsRow
	for rows.Next() {
		var i InsertNewContactsRow
		if err := rows.Scan(&i.ID, &i.EmailAddress); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMissingContactNames = `-- name: UpdateMissingContactNames :exec
UPDATE email_contacts
        SET name = data.name, updated_at = now()
        FROM (SELECT unnest($1::uuid[]) as id, unnest($2::text[]) as name) as data
        WHERE email_contacts.id = data.id
          AND email_contacts.name IS NULL
`

type UpdateMissingContactNamesParams struct {
	Column1 []pgtype.UUID
	Column2 []string
}

func (q *Queries) UpdateMissingContactNames(ctx context.Context, arg UpdateMissingContactNamesParams) error {
	_, err := q.db.Exec(ctx, updateMissingContactNames, arg.Column1, arg.Column2)
	return err
}

const upsertMessageRecipients = `-- name: UpsertMessageRecipients :exec
DELETE FROM email_message_recipients
        WHERE message_id = $1
          AND (contact_id, recipient_type) NOT IN (
              SELECT contact_id, recipient_type
              FROM (SELECT unnest($2::uuid[]) AS contact_id, unnest($3::email_recipient_type[]) AS recipient_type) AS t
          )
`

type UpsertMessageRecipientsParams struct {
	MessageID pgtype.UUID
	Column2   []pgtype.UUID
	Column3   []EmailRecipientType
}

func (q *Queries) UpsertMessageRecipients(ctx context.Context, arg UpsertMessageRecipientsParams) error {
	_, err := q.db.Exec(ctx, upsertMessageRecipients, arg.MessageID, arg.Column2, arg.Column3)
	return err
}

const upsertMessageRecipients2 = `-- name: UpsertMessageRecipients2 :exec
INSERT INTO email_message_recipients (message_id, contact_id, name, recipient_type)
        SELECT unnest($1::uuid[]), unnest($2::uuid[]), unnest($3::text[]), unnest($4::email_recipient_type[])
        ON CONFLICT (message_id, contact_id, recipient_type) DO NOTHING
`

type UpsertMessageRecipients2Params struct {
	Column1 []pgtype.UUID
	Column2 []pgtype.UUID
	Column3 []string
	Column4 []EmailRecipientType
}

func (q *Queries) UpsertMessageRecipients2(ctx context.Context, arg UpsertMessageRecipients2Params) error {
	_, err := q.db.Exec(ctx, upsertMessageRecipients2,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	return err
}
