// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: crm_cleanup_candidates.sql

package emaildb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimCandidate = `-- name: ClaimCandidate :exec
DELETE FROM crm_cleanup_candidates
        WHERE link_id = $1 AND contact_email = $2
`

type ClaimCandidateParams struct {
	LinkID       pgtype.UUID
	ContactEmail string
}

func (q *Queries) ClaimCandidate(ctx context.Context, arg ClaimCandidateParams) error {
	_, err := q.db.Exec(ctx, claimCandidate, arg.LinkID, arg.ContactEmail)
	return err
}

const claimCandidates = `-- name: ClaimCandidates :exec
DELETE FROM crm_cleanup_candidates c
        USING (SELECT unnest($1::uuid[]) AS link_id, unnest($2::text[]) AS contact_email) AS p
        WHERE c.link_id = p.link_id AND c.contact_email = p.contact_email
`

type ClaimCandidatesParams struct {
	Column1 []pgtype.UUID
	Column2 []string
}

func (q *Queries) ClaimCandidates(ctx context.Context, arg ClaimCandidatesParams) error {
	_, err := q.db.Exec(ctx, claimCandidates, arg.Column1, arg.Column2)
	return err
}

const getMaxIdAndCount = `-- name: GetMaxIdAndCount :one
SELECT MAX(id)::int8 as "max_id", COUNT(*) as "count"
        FROM crm_cleanup_candidates
`

type GetMaxIdAndCountRow struct {
	MaxID int64
	Count int64
}

func (q *Queries) GetMaxIdAndCount(ctx context.Context) (GetMaxIdAndCountRow, error) {
	row := q.db.QueryRow(ctx, getMaxIdAndCount)
	var i GetMaxIdAndCountRow
	err := row.Scan(&i.MaxID, &i.Count)
	return i, err
}

const insertCandidates = `-- name: InsertCandidates :exec
INSERT INTO crm_cleanup_candidates (link_id, contact_email)
        SELECT $1, unnest($2::text[])
        ON CONFLICT (link_id, contact_email) DO UPDATE SET created_at = now()
`

type InsertCandidatesParams struct {
	LinkID  pgtype.UUID
	Column2 []string
}

func (q *Queries) InsertCandidates(ctx context.Context, arg InsertCandidatesParams) error {
	_, err := q.db.Exec(ctx, insertCandidates, arg.LinkID, arg.Column2)
	return err
}

const listCandidatesPage = `-- name: ListCandidatesPage :many
SELECT id, link_id, contact_email, created_at
        FROM crm_cleanup_candidates
        WHERE id > $1 AND id <= $2
        ORDER BY id
        LIMIT $3
`

type ListCandidatesPageParams struct {
	ID    int64
	ID_2  int64
	Limit int32
}

func (q *Queries) ListCandidatesPage(ctx context.Context, arg ListCandidatesPageParams) ([]CrmCleanupCandidate, error) {
	rows, err := q.db.Query(ctx, listCandidatesPage, arg.ID, arg.ID_2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CrmCleanupCandidate
	for rows.Next() {
		var i CrmCleanupCandidate
		if err := rows.Scan(
			&i.ID,
			&i.LinkID,
			&i.ContactEmail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
