// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: histories.sql

package emaildb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const fetchHistoryIdForLink = `-- name: FetchHistoryIdForLink :one
SELECT gh.history_id
        FROM email_links l
        LEFT JOIN email_gmail_histories gh ON l.id = gh.link_id
        WHERE l.email_address = $1 AND l.provider = $2
`

type FetchHistoryIdForLinkParams struct {
	EmailAddress string
	Provider     EmailUserProviderEnum
}

func (q *Queries) FetchHistoryIdForLink(ctx context.Context, arg FetchHistoryIdForLinkParams) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, fetchHistoryIdForLink, arg.EmailAddress, arg.Provider)
	var history_id pgtype.Text
	err := row.Scan(&history_id)
	return history_id, err
}

const upsertGmailHistory = `-- name: UpsertGmailHistory :exec
INSERT INTO email_gmail_histories (link_id, history_id, updated_at)
        VALUES ($1, $2, NOW())
        ON CONFLICT (link_id)
        DO UPDATE SET
            history_id = EXCLUDED.history_id,
            updated_at = NOW()
`

type UpsertGmailHistoryParams struct {
	LinkID    pgtype.UUID
	HistoryID string
}

func (q *Queries) UpsertGmailHistory(ctx context.Context, arg UpsertGmailHistoryParams) error {
	_, err := q.db.Exec(ctx, upsertGmailHistory, arg.LinkID, arg.HistoryID)
	return err
}
