// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: labels_delete.sql

package emaildb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteAllMessageLabels = `-- name: DeleteAllMessageLabels :exec
DELETE FROM email_message_labels
        WHERE message_id = $1
`

func (q *Queries) DeleteAllMessageLabels(ctx context.Context, messageID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllMessageLabels, messageID)
	return err
}

const deleteDbMessageLabels = `-- name: DeleteDbMessageLabels :exec
DELETE FROM email_message_labels
        WHERE message_id = $1
        AND label_id IN (
            SELECT id FROM email_labels
            WHERE link_id = $2 AND "provider_label_id" = ANY($3::text[])
        )
`

type DeleteDbMessageLabelsParams struct {
	MessageID pgtype.UUID
	LinkID    pgtype.UUID
	Column3   []string
}

func (q *Queries) DeleteDbMessageLabels(ctx context.Context, arg DeleteDbMessageLabelsParams) error {
	_, err := q.db.Exec(ctx, deleteDbMessageLabels, arg.MessageID, arg.LinkID, arg.Column3)
	return err
}

const deleteLabelById = `-- name: DeleteLabelById :exec
DELETE FROM email_message_labels
        WHERE label_id = $1
`

func (q *Queries) DeleteLabelById(ctx context.Context, labelID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteLabelById, labelID)
	return err
}

const deleteLabelById2 = `-- name: DeleteLabelById2 :exec
DELETE FROM email_labels
        WHERE id = $1 AND link_id = $2
`

type DeleteLabelById2Params struct {
	ID     pgtype.UUID
	LinkID pgtype.UUID
}

func (q *Queries) DeleteLabelById2(ctx context.Context, arg DeleteLabelById2Params) error {
	_, err := q.db.Exec(ctx, deleteLabelById2, arg.ID, arg.LinkID)
	return err
}

const deleteLabelsByProviderIds = `-- name: DeleteLabelsByProviderIds :exec
DELETE FROM email_message_labels
        WHERE label_id IN (
            SELECT id FROM email_labels
            WHERE link_id = $1 AND "provider_label_id" = ANY($2::text[])
        )
`

type DeleteLabelsByProviderIdsParams struct {
	LinkID  pgtype.UUID
	Column2 []string
}

func (q *Queries) DeleteLabelsByProviderIds(ctx context.Context, arg DeleteLabelsByProviderIdsParams) error {
	_, err := q.db.Exec(ctx, deleteLabelsByProviderIds, arg.LinkID, arg.Column2)
	return err
}

const deleteLabelsByProviderIds2 = `-- name: DeleteLabelsByProviderIds2 :exec
DELETE FROM email_labels
        WHERE link_id = $1 AND "provider_label_id" = ANY($2::text[])
`

type DeleteLabelsByProviderIds2Params struct {
	LinkID  pgtype.UUID
	Column2 []string
}

func (q *Queries) DeleteLabelsByProviderIds2(ctx context.Context, arg DeleteLabelsByProviderIds2Params) error {
	_, err := q.db.Exec(ctx, deleteLabelsByProviderIds2, arg.LinkID, arg.Column2)
	return err
}

const deleteMessageLabelsBatch = `-- name: DeleteMessageLabelsBatch :exec
DELETE FROM email_message_labels
        WHERE 
            "message_id" = ANY($1::uuid[]) 
            AND label_id = (
                SELECT id FROM email_labels
                WHERE link_id = $2 AND provider_label_id = $3
            )
`

type DeleteMessageLabelsBatchParams struct {
	Column1         []pgtype.UUID
	LinkID          pgtype.UUID
	ProviderLabelID string
}

func (q *Queries) DeleteMessageLabelsBatch(ctx context.Context, arg DeleteMessageLabelsBatchParams) error {
	_, err := q.db.Exec(ctx, deleteMessageLabelsBatch, arg.Column1, arg.LinkID, arg.ProviderLabelID)
	return err
}
