// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: labels_insert.sql

package emaildb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertLabel = `-- name: InsertLabel :one
INSERT INTO email_labels (
            id,
            link_id,
            provider_label_id,
            name,
            message_list_visibility,
            label_list_visibility,
            type
        )
        VALUES ($1, $2, $3, $4, $5, $6, $7)
        ON CONFLICT (link_id, provider_label_id) DO UPDATE
        SET
            name = EXCLUDED.name,
            message_list_visibility = EXCLUDED.message_list_visibility,
            label_list_visibility = EXCLUDED.label_list_visibility,
            type = EXCLUDED.type
        RETURNING 
            id,
            link_id,
            provider_label_id,
            name,
            created_at,
            message_list_visibility as "message_list_visibility",
            label_list_visibility as "label_list_visibility",
            type as "type_"
`

type InsertLabelParams struct {
	ID                    pgtype.UUID
	LinkID                pgtype.UUID
	ProviderLabelID       string
	Name                  string
	MessageListVisibility EmailMessageListVisibilityEnum
	LabelListVisibility   EmailLabelListVisibilityEnum
	Type                  EmailLabelTypeEnum
}

func (q *Queries) InsertLabel(ctx context.Context, arg InsertLabelParams) (EmailLabel, error) {
	row := q.db.QueryRow(ctx, insertLabel,
		arg.ID,
		arg.LinkID,
		arg.ProviderLabelID,
		arg.Name,
		arg.MessageListVisibility,
		arg.LabelListVisibility,
		arg.Type,
	)
	var i EmailLabel
	err := row.Scan(
		&i.ID,
		&i.LinkID,
		&i.ProviderLabelID,
		&i.Name,
		&i.CreatedAt,
		&i.MessageListVisibility,
		&i.LabelListVisibility,
		&i.Type,
	)
	return i, err
}

const insertMessageLabel = `-- name: InsertMessageLabel :one
WITH label_lookup AS (
            SELECT id FROM email_labels
            WHERE link_id = $2 AND provider_label_id = $3
        )
        INSERT INTO email_message_labels (message_id, label_id)
        SELECT $1, id FROM label_lookup
        ON CONFLICT (message_id, label_id) DO NOTHING
        RETURNING (SELECT COUNT(*) FROM label_lookup) AS label_found
`

type InsertMessageLabelParams struct {
	MessageID       pgtype.UUID
	LinkID          pgtype.UUID
	ProviderLabelID string
}

func (q *Queries) InsertMessageLabel(ctx context.Context, arg InsertMessageLabelParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertMessageLabel, arg.MessageID, arg.LinkID, arg.ProviderLabelID)
	var label_found int64
	err := row.Scan(&label_found)
	return label_found, err
}

const insertMessageLabels = `-- name: InsertMessageLabels :many
SELECT id, provider_label_id
        FROM email_labels
        WHERE link_id = $1 AND "provider_label_id" = ANY($2::text[])
`

type InsertMessageLabelsParams struct {
	LinkID  pgtype.UUID
	Column2 []string
}

type InsertMessageLabelsRow struct {
	ID              pgtype.UUID
	ProviderLabelID string
}

func (q *Queries) InsertMessageLabels(ctx context.Context, arg InsertMessageLabelsParams) ([]InsertMessageLabelsRow, error) {
	rows, err := q.db.Query(ctx, insertMessageLabels, arg.LinkID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InsertMessageLabelsRow
	for rows.Next() {
		var i InsertMessageLabelsRow
		if err := rows.Scan(&i.ID, &i.ProviderLabelID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertMessageLabels2 = `-- name: InsertMessageLabels2 :exec
DELETE FROM email_message_labels
        WHERE message_id = $1
        AND label_id NOT IN (
            SELECT UNNEST($2::uuid[])
        )
`

type InsertMessageLabels2Params struct {
	MessageID pgtype.UUID
	Column2   []pgtype.UUID
}

func (q *Queries) InsertMessageLabels2(ctx context.Context, arg InsertMessageLabels2Params) error {
	_, err := q.db.Exec(ctx, insertMessageLabels2, arg.MessageID, arg.Column2)
	return err
}

const insertMessageLabels3 = `-- name: InsertMessageLabels3 :exec
INSERT INTO email_message_labels (message_id, label_id)
        SELECT unnest($1::uuid[]), unnest($2::uuid[])
        ON CONFLICT (message_id, label_id) DO NOTHING
`

type InsertMessageLabels3Params struct {
	Column1 []pgtype.UUID
	Column2 []pgtype.UUID
}

func (q *Queries) InsertMessageLabels3(ctx context.Context, arg InsertMessageLabels3Params) error {
	_, err := q.db.Exec(ctx, insertMessageLabels3, arg.Column1, arg.Column2)
	return err
}

const insertMessageLabelsBatch = `-- name: InsertMessageLabelsBatch :exec
INSERT INTO email_message_labels (message_id, label_id)
        SELECT
            unnested_message_id,
            l.id
        FROM (SELECT unnest($1::uuid[]) AS unnested_message_id) AS t
        CROSS JOIN
            email_labels l
        WHERE
            l.link_id = $2 AND l.provider_label_id = $3
        ON CONFLICT (message_id, label_id) DO NOTHING
`

type InsertMessageLabelsBatchParams struct {
	Column1         []pgtype.UUID
	LinkID          pgtype.UUID
	ProviderLabelID string
}

func (q *Queries) InsertMessageLabelsBatch(ctx context.Context, arg InsertMessageLabelsBatchParams) error {
	_, err := q.db.Exec(ctx, insertMessageLabelsBatch, arg.Column1, arg.LinkID, arg.ProviderLabelID)
	return err
}

const insertOrUpdateLabels = `-- name: InsertOrUpdateLabels :exec
WITH input_rows (
            id,
            link_id,
            provider_label_id,
            name,
            message_list_visibility,
            label_list_visibility,
            type
        ) AS (
           SELECT unnest($1::uuid[]), unnest($2::uuid[]), unnest($3::text[]), unnest($4::text[]), unnest($5::email_message_list_visibility_enum[]), unnest($6::email_label_list_visibility_enum[]), unnest($7::email_label_type_enum[])
        )
        INSERT INTO email_labels (
            id,
            link_id,
            provider_label_id,
            name,
            message_list_visibility,
            label_list_visibility,
            type
        )
        SELECT
            id,
            link_id,
            provider_label_id,
            name,
            message_list_visibility,
            label_list_visibility,
            type
        FROM input_rows
        ON CONFLICT (link_id, provider_label_id) DO UPDATE
        SET
            name = EXCLUDED.name,
            message_list_visibility = EXCLUDED.message_list_visibility,
            label_list_visibility = EXCLUDED.label_list_visibility,
            type = EXCLUDED.type
`

type InsertOrUpdateLabelsParams struct {
	Column1 []pgtype.UUID
	Column2 []pgtype.UUID
	Column3 []string
	Column4 []string
	Column5 []EmailMessageListVisibilityEnum
	Column6 []EmailLabelListVisibilityEnum
	Column7 []EmailLabelTypeEnum
}

func (q *Queries) InsertOrUpdateLabels(ctx context.Context, arg InsertOrUpdateLabelsParams) error {
	_, err := q.db.Exec(ctx, insertOrUpdateLabels,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.Column7,
	)
	return err
}
