// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: labels_get.sql

package emaildb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const fetchLabelById = `-- name: FetchLabelById :one
SELECT 
            id, 
            link_id, 
            provider_label_id, 
            name, 
            created_at,
            message_list_visibility as "message_list_visibility",
            label_list_visibility as "label_list_visibility",
            type as "type_"
        FROM email_labels
        WHERE id = $1 AND link_id = $2
`

type FetchLabelByIdParams struct {
	ID     pgtype.UUID
	LinkID pgtype.UUID
}

func (q *Queries) FetchLabelById(ctx context.Context, arg FetchLabelByIdParams) (EmailLabel, error) {
	row := q.db.QueryRow(ctx, fetchLabelById, arg.ID, arg.LinkID)
	var i EmailLabel
	err := row.Scan(
		&i.ID,
		&i.LinkID,
		&i.ProviderLabelID,
		&i.Name,
		&i.CreatedAt,
		&i.MessageListVisibility,
		&i.LabelListVisibility,
		&i.Type,
	)
	return i, err
}

const fetchLabelsByLinkId = `-- name: FetchLabelsByLinkId :many
SELECT 
            id, 
            link_id, 
            provider_label_id, 
            name, 
            created_at,
            message_list_visibility as "message_list_visibility",
            label_list_visibility as "label_list_visibility",
            type as "type_"
        FROM email_labels
        WHERE link_id = $1
        ORDER BY name
`

func (q *Queries) FetchLabelsByLinkId(ctx context.Context, linkID pgtype.UUID) ([]EmailLabel, error) {
	rows, err := q.db.Query(ctx, fetchLabelsByLinkId, linkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EmailLabel
	for rows.Next() {
		var i EmailLabel
		if err := rows.Scan(
			&i.ID,
			&i.LinkID,
			&i.ProviderLabelID,
			&i.Name,
			&i.CreatedAt,
			&i.MessageListVisibility,
			&i.LabelListVisibility,
			&i.Type,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fetchMessageLabel = `-- name: FetchMessageLabel :one
SELECT ml.message_id, ml.label_id
        FROM email_message_labels ml
        JOIN email_labels l ON ml.label_id = l.id
        WHERE ml.message_id = $1
        AND l.provider_label_id = $2
        AND l.link_id = $3
`

type FetchMessageLabelParams struct {
	MessageID       pgtype.UUID
	ProviderLabelID string
	LinkID          pgtype.UUID
}

func (q *Queries) FetchMessageLabel(ctx context.Context, arg FetchMessageLabelParams) (EmailMessageLabel, error) {
	row := q.db.QueryRow(ctx, fetchMessageLabel, arg.MessageID, arg.ProviderLabelID, arg.LinkID)
	var i EmailMessageLabel
	err := row.Scan(&i.MessageID, &i.LabelID)
	return i, err
}

const fetchMessageLabels = `-- name: FetchMessageLabels :many
SELECT
            l.id,
            l.link_id,
            l.provider_label_id,
            l.name,
            l.created_at,
            l.message_list_visibility as "message_list_visibility",
            l.label_list_visibility as "label_list_visibility",
            l.type as "type_"
        FROM email_message_labels ml
        JOIN email_labels l ON ml.label_id = l.id
        WHERE ml.message_id = $1
        ORDER BY l.name
`

func (q *Queries) FetchMessageLabels(ctx context.Context, messageID pgtype.UUID) ([]EmailLabel, error) {
	rows, err := q.db.Query(ctx, fetchMessageLabels, messageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EmailLabel
	for rows.Next() {
		var i EmailLabel
		if err := rows.Scan(
			&i.ID,
			&i.LinkID,
			&i.ProviderLabelID,
			&i.Name,
			&i.CreatedAt,
			&i.MessageListVisibility,
			&i.LabelListVisibility,
			&i.Type,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fetchMessageLabelsInBulk = `-- name: FetchMessageLabelsInBulk :many
SELECT
            ml.message_id,
            l.id,
            l.link_id,
            l.provider_label_id,
            l.name,
            l.created_at,
            l.message_list_visibility as "message_list_visibility",
            l.label_list_visibility as "label_list_visibility",
            l.type as "type_"
        FROM email_message_labels ml
        JOIN email_labels l ON ml.label_id = l.id
        WHERE
            ml."message_id" = ANY($1::uuid[])
        ORDER BY ml.message_id
`

type FetchMessageLabelsInBulkRow struct {
	MessageID             pgtype.UUID
	ID                    pgtype.UUID
	LinkID                pgtype.UUID
	ProviderLabelID       string
	Name                  string
	CreatedAt             pgtype.Timestamptz
	MessageListVisibility EmailMessageListVisibilityEnum
	LabelListVisibility   EmailLabelListVisibilityEnum
	Type                  EmailLabelTypeEnum
}

func (q *Queries) FetchMessageLabelsInBulk(ctx context.Context, dollar_1 []pgtype.UUID) ([]FetchMessageLabelsInBulkRow, error) {
	rows, err := q.db.Query(ctx, fetchMessageLabelsInBulk, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FetchMessageLabelsInBulkRow
	for rows.Next() {
		var i FetchMessageLabelsInBulkRow
		if err := rows.Scan(
			&i.MessageID,
			&i.ID,
			&i.LinkID,
			&i.ProviderLabelID,
			&i.Name,
			&i.CreatedAt,
			&i.MessageListVisibility,
			&i.LabelListVisibility,
			&i.Type,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findMissingProviderLabels = `-- name: FindMissingProviderLabels :many
SELECT provider_label_id
        FROM email_labels
        WHERE link_id = $1 AND "provider_label_id" = ANY($2::text[])
`

type FindMissingProviderLabelsParams struct {
	LinkID  pgtype.UUID
	Column2 []string
}

func (q *Queries) FindMissingProviderLabels(ctx context.Context, arg FindMissingProviderLabelsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, findMissingProviderLabels, arg.LinkID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var provider_label_id string
		if err := rows.Scan(&provider_label_id); err != nil {
			return nil, err
		}
		items = append(items, provider_label_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
