// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: links_delete.sql

package emaildb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteLinkById = `-- name: DeleteLinkById :exec
DELETE FROM email_links
        WHERE id = $1
`

func (q *Queries) DeleteLinkById(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteLinkById, id)
	return err
}
