// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: links_update.sql

package emaildb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearLinkNeedsReauth = `-- name: ClearLinkNeedsReauth :exec
UPDATE email_links
        SET needs_reauth = false,
            last_sync_error_at = NULL,
            updated_at = NOW()
        WHERE id = $1 AND needs_reauth = true
`

func (q *Queries) ClearLinkNeedsReauth(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearLinkNeedsReauth, id)
	return err
}

const setLinkNeedsReauth = `-- name: SetLinkNeedsReauth :one
WITH prev AS (
            SELECT needs_reauth FROM email_links WHERE id = $1 FOR UPDATE
        )
        UPDATE email_links e
        SET needs_reauth = true,
            last_sync_error_at = NOW(),
            updated_at = NOW()
        FROM prev
        WHERE e.id = $1
        RETURNING (NOT prev.needs_reauth) AS "did_transition"
`

func (q *Queries) SetLinkNeedsReauth(ctx context.Context, id pgtype.UUID) (pgtype.Bool, error) {
	row := q.db.QueryRow(ctx, setLinkNeedsReauth, id)
	var did_transition pgtype.Bool
	err := row.Scan(&did_transition)
	return did_transition, err
}

const updateLinkFusionauthUserId = `-- name: UpdateLinkFusionauthUserId :exec
UPDATE email_links
        SET fusionauth_user_id = $2, updated_at = NOW()
        WHERE id = $1
`

type UpdateLinkFusionauthUserIdParams struct {
	ID               pgtype.UUID
	FusionauthUserID string
}

func (q *Queries) UpdateLinkFusionauthUserId(ctx context.Context, arg UpdateLinkFusionauthUserIdParams) error {
	_, err := q.db.Exec(ctx, updateLinkFusionauthUserId, arg.ID, arg.FusionauthUserID)
	return err
}

const updateLinkSyncStatus = `-- name: UpdateLinkSyncStatus :exec
UPDATE email_links
        SET is_sync_active = $2, updated_at = NOW()
        WHERE id = $1 AND is_sync_active IS DISTINCT FROM $2
`

type UpdateLinkSyncStatusParams struct {
	ID           pgtype.UUID
	IsSyncActive bool
}

func (q *Queries) UpdateLinkSyncStatus(ctx context.Context, arg UpdateLinkSyncStatusParams) error {
	_, err := q.db.Exec(ctx, updateLinkSyncStatus, arg.ID, arg.IsSyncActive)
	return err
}
