// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: links_insert.sql

package emaildb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const upsertLink = `-- name: UpsertLink :one
INSERT INTO email_links (id, macro_id, fusionauth_user_id, email_address, provider, is_sync_active)
        VALUES ($1, $2, $3, $4, $5, $6)
        ON CONFLICT (fusionauth_user_id, email_address, provider)
        DO UPDATE SET
            is_sync_active = EXCLUDED.is_sync_active,
            needs_reauth = false,
            last_sync_error_at = NULL,
            updated_at = NOW()
        RETURNING id, is_primary
`

type UpsertLinkParams struct {
	ID               pgtype.UUID
	MacroID          string
	FusionauthUserID string
	EmailAddress     string
	Provider         EmailUserProviderEnum
	IsSyncActive     bool
}

type UpsertLinkRow struct {
	ID        pgtype.UUID
	IsPrimary bool
}

func (q *Queries) UpsertLink(ctx context.Context, arg UpsertLinkParams) (UpsertLinkRow, error) {
	row := q.db.QueryRow(ctx, upsertLink,
		arg.ID,
		arg.MacroID,
		arg.FusionauthUserID,
		arg.EmailAddress,
		arg.Provider,
		arg.IsSyncActive,
	)
	var i UpsertLinkRow
	err := row.Scan(&i.ID, &i.IsPrimary)
	return i, err
}

const upsertLink2 = `-- name: UpsertLink2 :exec
INSERT INTO email_settings (link_id) -- default settings for new links
        VALUES ($1)
        ON CONFLICT (link_id)
        DO NOTHING
`

func (q *Queries) UpsertLink2(ctx context.Context, linkID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, upsertLink2, linkID)
	return err
}
