// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages_get_parsed_search.sql

package emaildb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getParsedSearchMessageById = `-- name: GetParsedSearchMessageById :one
SELECT
            m.id, m.provider_id, m.global_id, m.link_id, m.thread_id, m.provider_thread_id, m.provider_history_id,
            m.replying_to_id, m.internal_date_ts, m.snippet, m.size_estimate, m.subject, m.from_name,
            m.from_contact_id, m.sent_at, m.has_attachments, m.is_read, m.is_starred, m.is_sent, m.is_draft,
            m.body_text as body_text,
            m.body_html_sanitized as body_html_sanitized,
            NULL::TEXT as body_macro,
            m.headers_jsonb, m.created_at, m.updated_at
        FROM email_messages m
        JOIN email_links l ON m.link_id = l.id
        WHERE m.id = $1
`

type GetParsedSearchMessageByIdRow struct {
	ID                pgtype.UUID
	ProviderID        pgtype.Text
	GlobalID          pgtype.Text
	LinkID            pgtype.UUID
	ThreadID          pgtype.UUID
	ProviderThreadID  pgtype.Text
	ProviderHistoryID pgtype.Text
	ReplyingToID      pgtype.UUID
	InternalDateTs    pgtype.Timestamptz
	Snippet           pgtype.Text
	SizeEstimate      pgtype.Int8
	Subject           pgtype.Text
	FromName          pgtype.Text
	FromContactID     pgtype.UUID
	SentAt            pgtype.Timestamptz
	HasAttachments    bool
	IsRead            bool
	IsStarred         bool
	IsSent            bool
	IsDraft           bool
	BodyText          pgtype.Text
	BodyHtmlSanitized pgtype.Text
	BodyMacro         pgtype.Text
	HeadersJsonb      []byte
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

func (q *Queries) GetParsedSearchMessageById(ctx context.Context, id pgtype.UUID) (GetParsedSearchMessageByIdRow, error) {
	row := q.db.QueryRow(ctx, getParsedSearchMessageById, id)
	var i GetParsedSearchMessageByIdRow
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.GlobalID,
		&i.LinkID,
		&i.ThreadID,
		&i.ProviderThreadID,
		&i.ProviderHistoryID,
		&i.ReplyingToID,
		&i.InternalDateTs,
		&i.Snippet,
		&i.SizeEstimate,
		&i.Subject,
		&i.FromName,
		&i.FromContactID,
		&i.SentAt,
		&i.HasAttachments,
		&i.IsRead,
		&i.IsStarred,
		&i.IsSent,
		&i.IsDraft,
		&i.BodyText,
		&i.BodyHtmlSanitized,
		&i.BodyMacro,
		&i.HeadersJsonb,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getParsedSearchMessagesByThreadIds = `-- name: GetParsedSearchMessagesByThreadIds :many
SELECT
            id,
            provider_id,
            global_id,
            thread_id,
            provider_thread_id,
            replying_to_id,
            link_id,
            provider_history_id,
            internal_date_ts,
            snippet,
            size_estimate,
            subject,
            from_name,
            from_contact_id,
            sent_at,
            has_attachments,
            is_read,
            is_starred,
            is_sent,
            is_draft,
            headers_jsonb,
            created_at,
            updated_at,
            body_text as body_text,
            body_html_sanitized as body_html_sanitized,
            NULL::TEXT as body_macro
        FROM email_messages
        WHERE "thread_id" = ANY($1::uuid[])
        ORDER BY internal_date_ts DESC NULLS LAST
`

type GetParsedSearchMessagesByThreadIdsRow struct {
	ID                pgtype.UUID
	ProviderID        pgtype.Text
	GlobalID          pgtype.Text
	ThreadID          pgtype.UUID
	ProviderThreadID  pgtype.Text
	ReplyingToID      pgtype.UUID
	LinkID            pgtype.UUID
	ProviderHistoryID pgtype.Text
	InternalDateTs    pgtype.Timestamptz
	Snippet           pgtype.Text
	SizeEstimate      pgtype.Int8
	Subject           pgtype.Text
	FromName          pgtype.Text
	FromContactID     pgtype.UUID
	SentAt            pgtype.Timestamptz
	HasAttachments    bool
	IsRead            bool
	IsStarred         bool
	IsSent            bool
	IsDraft           bool
	HeadersJsonb      []byte
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	BodyText          pgtype.Text
	BodyHtmlSanitized pgtype.Text
	BodyMacro         pgtype.Text
}

func (q *Queries) GetParsedSearchMessagesByThreadIds(ctx context.Context, dollar_1 []pgtype.UUID) ([]GetParsedSearchMessagesByThreadIdsRow, error) {
	rows, err := q.db.Query(ctx, getParsedSearchMessagesByThreadIds, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetParsedSearchMessagesByThreadIdsRow
	for rows.Next() {
		var i GetParsedSearchMessagesByThreadIdsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.GlobalID,
			&i.ThreadID,
			&i.ProviderThreadID,
			&i.ReplyingToID,
			&i.LinkID,
			&i.ProviderHistoryID,
			&i.InternalDateTs,
			&i.Snippet,
			&i.SizeEstimate,
			&i.Subject,
			&i.FromName,
			&i.FromContactID,
			&i.SentAt,
			&i.HasAttachments,
			&i.IsRead,
			&i.IsStarred,
			&i.IsSent,
			&i.IsDraft,
			&i.HeadersJsonb,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BodyText,
			&i.BodyHtmlSanitized,
			&i.BodyMacro,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
