// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages_get_simple_messages.sql

package emaildb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getFirstSimpleMessageDraft = `-- name: GetFirstSimpleMessageDraft :one
SELECT
            m.id, m.provider_id, m.global_id, m.link_id, m.thread_id, m.provider_thread_id, m.provider_history_id,
            m.replying_to_id, m.internal_date_ts, m.snippet, m.size_estimate, m.subject, m.from_name,
            m.from_contact_id, m.sent_at, m.has_attachments, m.is_read, m.is_starred, m.is_sent, m.is_draft,
            NULL::TEXT as body_text,
            NULL::TEXT as body_html_sanitized,
            NULL::TEXT as body_macro,
            m.headers_jsonb, m.created_at, m.updated_at
        FROM email_messages m
        WHERE m.link_id = $1
          AND m.is_draft = true
          AND jsonb_path_exists(
              m.headers_jsonb,
              '$[*] ? (@."Macro-In-Reply-To" == $macro_uuid)'::jsonpath,
              jsonb_build_object('macro_uuid', $2::text)
          )
        ORDER BY m.created_at DESC
        LIMIT 1
`

type GetFirstSimpleMessageDraftParams struct {
	LinkID  pgtype.UUID
	Column2 string
}

type GetFirstSimpleMessageDraftRow struct {
	ID                pgtype.UUID
	ProviderID        pgtype.Text
	GlobalID          pgtype.Text
	LinkID            pgtype.UUID
	ThreadID          pgtype.UUID
	ProviderThreadID  pgtype.Text
	ProviderHistoryID pgtype.Text
	ReplyingToID      pgtype.UUID
	InternalDateTs    pgtype.Timestamptz
	Snippet           pgtype.Text
	SizeEstimate      pgtype.Int8
	Subject           pgtype.Text
	FromName          pgtype.Text
	FromContactID     pgtype.UUID
	SentAt            pgtype.Timestamptz
	HasAttachments    bool
	IsRead            bool
	IsStarred         bool
	IsSent            bool
	IsDraft           bool
	BodyText          pgtype.Text
	BodyHtmlSanitized pgtype.Text
	BodyMacro         pgtype.Text
	HeadersJsonb      []byte
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

func (q *Queries) GetFirstSimpleMessageDraft(ctx context.Context, arg GetFirstSimpleMessageDraftParams) (GetFirstSimpleMessageDraftRow, error) {
	row := q.db.QueryRow(ctx, getFirstSimpleMessageDraft, arg.LinkID, arg.Column2)
	var i GetFirstSimpleMessageDraftRow
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.GlobalID,
		&i.LinkID,
		&i.ThreadID,
		&i.ProviderThreadID,
		&i.ProviderHistoryID,
		&i.ReplyingToID,
		&i.InternalDateTs,
		&i.Snippet,
		&i.SizeEstimate,
		&i.Subject,
		&i.FromName,
		&i.FromContactID,
		&i.SentAt,
		&i.HasAttachments,
		&i.IsRead,
		&i.IsStarred,
		&i.IsSent,
		&i.IsDraft,
		&i.BodyText,
		&i.BodyHtmlSanitized,
		&i.BodyMacro,
		&i.HeadersJsonb,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSimpleMessage = `-- name: GetSimpleMessage :one
SELECT
            m.id, m.provider_id, m.global_id, m.link_id, m.thread_id, m.provider_thread_id, m.replying_to_id,
            m.provider_history_id, m.internal_date_ts, m.snippet, m.size_estimate, m.subject, m.from_name,
            m.from_contact_id, m.sent_at, m.has_attachments, m.is_read, m.is_starred, m.is_sent, m.is_draft,
            NULL::TEXT as body_text,
            NULL::TEXT as body_html_sanitized,
            NULL::TEXT as body_macro,
            m.headers_jsonb, m.created_at, m.updated_at
        FROM email_messages m
        JOIN email_links l ON m.link_id = l.id
        WHERE m.id = $1 AND l.fusionauth_user_id = $2
`

type GetSimpleMessageParams struct {
	ID               pgtype.UUID
	FusionauthUserID string
}

type GetSimpleMessageRow struct {
	ID                pgtype.UUID
	ProviderID        pgtype.Text
	GlobalID          pgtype.Text
	LinkID            pgtype.UUID
	ThreadID          pgtype.UUID
	ProviderThreadID  pgtype.Text
	ReplyingToID      pgtype.UUID
	ProviderHistoryID pgtype.Text
	InternalDateTs    pgtype.Timestamptz
	Snippet           pgtype.Text
	SizeEstimate      pgtype.Int8
	Subject           pgtype.Text
	FromName          pgtype.Text
	FromContactID     pgtype.UUID
	SentAt            pgtype.Timestamptz
	HasAttachments    bool
	IsRead            bool
	IsStarred         bool
	IsSent            bool
	IsDraft           bool
	BodyText          pgtype.Text
	BodyHtmlSanitized pgtype.Text
	BodyMacro         pgtype.Text
	HeadersJsonb      []byte
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

func (q *Queries) GetSimpleMessage(ctx context.Context, arg GetSimpleMessageParams) (GetSimpleMessageRow, error) {
	row := q.db.QueryRow(ctx, getSimpleMessage, arg.ID, arg.FusionauthUserID)
	var i GetSimpleMessageRow
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.GlobalID,
		&i.LinkID,
		&i.ThreadID,
		&i.ProviderThreadID,
		&i.ReplyingToID,
		&i.ProviderHistoryID,
		&i.InternalDateTs,
		&i.Snippet,
		&i.SizeEstimate,
		&i.Subject,
		&i.FromName,
		&i.FromContactID,
		&i.SentAt,
		&i.HasAttachments,
		&i.IsRead,
		&i.IsStarred,
		&i.IsSent,
		&i.IsDraft,
		&i.BodyText,
		&i.BodyHtmlSanitized,
		&i.BodyMacro,
		&i.HeadersJsonb,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSimpleMessageByProviderAndLink = `-- name: GetSimpleMessageByProviderAndLink :one
SELECT
            m.id, m.provider_id, m.global_id, m.link_id, m.thread_id, m.provider_thread_id, m.replying_to_id, 
            m.provider_history_id, m.internal_date_ts, m.snippet, m.size_estimate, m.subject, m.from_name,
            m.from_contact_id, m.sent_at, m.has_attachments, m.is_read, m.is_starred, m.is_sent, m.is_draft,
            NULL::TEXT as body_text,
            NULL::TEXT as body_html_sanitized,
            NULL::TEXT as body_macro,
            m.headers_jsonb, m.created_at, m.updated_at
        FROM email_messages m
        WHERE m.provider_id = $1 AND m.link_id = $2
`

type GetSimpleMessageByProviderAndLinkParams struct {
	ProviderID pgtype.Text
	LinkID     pgtype.UUID
}

type GetSimpleMessageByProviderAndLinkRow struct {
	ID                pgtype.UUID
	ProviderID        pgtype.Text
	GlobalID          pgtype.Text
	LinkID            pgtype.UUID
	ThreadID          pgtype.UUID
	ProviderThreadID  pgtype.Text
	ReplyingToID      pgtype.UUID
	ProviderHistoryID pgtype.Text
	InternalDateTs    pgtype.Timestamptz
	Snippet           pgtype.Text
	SizeEstimate      pgtype.Int8
	Subject           pgtype.Text
	FromName          pgtype.Text
	FromContactID     pgtype.UUID
	SentAt            pgtype.Timestamptz
	HasAttachments    bool
	IsRead            bool
	IsStarred         bool
	IsSent            bool
	IsDraft           bool
	BodyText          pgtype.Text
	BodyHtmlSanitized pgtype.Text
	BodyMacro         pgtype.Text
	HeadersJsonb      []byte
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

func (q *Queries) GetSimpleMessageByProviderAndLink(ctx context.Context, arg GetSimpleMessageByProviderAndLinkParams) (GetSimpleMessageByProviderAndLinkRow, error) {
	row := q.db.QueryRow(ctx, getSimpleMessageByProviderAndLink, arg.ProviderID, arg.LinkID)
	var i GetSimpleMessageByProviderAndLinkRow
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.GlobalID,
		&i.LinkID,
		&i.ThreadID,
		&i.ProviderThreadID,
		&i.ReplyingToID,
		&i.ProviderHistoryID,
		&i.InternalDateTs,
		&i.Snippet,
		&i.SizeEstimate,
		&i.Subject,
		&i.FromName,
		&i.FromContactID,
		&i.SentAt,
		&i.HasAttachments,
		&i.IsRead,
		&i.IsStarred,
		&i.IsSent,
		&i.IsDraft,
		&i.BodyText,
		&i.BodyHtmlSanitized,
		&i.BodyMacro,
		&i.HeadersJsonb,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSimpleMessagesBatch = `-- name: GetSimpleMessagesBatch :many
SELECT
            m.id, m.provider_id, m.global_id, m.link_id, m.thread_id, m.provider_thread_id, m.replying_to_id,
            m.provider_history_id, m.internal_date_ts, m.snippet, m.size_estimate, m.subject, m.from_name,
            m.from_contact_id, m.sent_at, m.has_attachments, m.is_read, m.is_starred, m.is_sent, m.is_draft,
            NULL::TEXT as body_text,
            NULL::TEXT as body_html_sanitized,
            NULL::TEXT as body_macro,
            m.headers_jsonb, m.created_at, m.updated_at
        FROM email_messages m
        JOIN email_links l ON m.link_id = l.id
        WHERE m."id" = ANY($1::uuid[]) AND l.fusionauth_user_id = $2
`

type GetSimpleMessagesBatchParams struct {
	Column1          []pgtype.UUID
	FusionauthUserID string
}

type GetSimpleMessagesBatchRow struct {
	ID                pgtype.UUID
	ProviderID        pgtype.Text
	GlobalID          pgtype.Text
	LinkID            pgtype.UUID
	ThreadID          pgtype.UUID
	ProviderThreadID  pgtype.Text
	ReplyingToID      pgtype.UUID
	ProviderHistoryID pgtype.Text
	InternalDateTs    pgtype.Timestamptz
	Snippet           pgtype.Text
	SizeEstimate      pgtype.Int8
	Subject           pgtype.Text
	FromName          pgtype.Text
	FromContactID     pgtype.UUID
	SentAt            pgtype.Timestamptz
	HasAttachments    bool
	IsRead            bool
	IsStarred         bool
	IsSent            bool
	IsDraft           bool
	BodyText          pgtype.Text
	BodyHtmlSanitized pgtype.Text
	BodyMacro         pgtype.Text
	HeadersJsonb      []byte
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

func (q *Queries) GetSimpleMessagesBatch(ctx context.Context, arg GetSimpleMessagesBatchParams) ([]GetSimpleMessagesBatchRow, error) {
	rows, err := q.db.Query(ctx, getSimpleMessagesBatch, arg.Column1, arg.FusionauthUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSimpleMessagesBatchRow
	for rows.Next() {
		var i GetSimpleMessagesBatchRow
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.GlobalID,
			&i.LinkID,
			&i.ThreadID,
			&i.ProviderThreadID,
			&i.ReplyingToID,
			&i.ProviderHistoryID,
			&i.InternalDateTs,
			&i.Snippet,
			&i.SizeEstimate,
			&i.Subject,
			&i.FromName,
			&i.FromContactID,
			&i.SentAt,
			&i.HasAttachments,
			&i.IsRead,
			&i.IsStarred,
			&i.IsSent,
			&i.IsDraft,
			&i.BodyText,
			&i.BodyHtmlSanitized,
			&i.BodyMacro,
			&i.HeadersJsonb,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSimpleMessagesForThread = `-- name: GetSimpleMessagesForThread :many
SELECT
            m.id,
            m.provider_id,
            m.global_id,
            m.link_id,
            m.thread_id,
            m.provider_thread_id,
            m.replying_to_id,
            m.provider_history_id,
            m.internal_date_ts,
            m.snippet,
            m.size_estimate,
            m.subject,
            m.from_name,
            m.from_contact_id,
            m.sent_at,
            m.has_attachments,
            m.is_read,
            m.is_starred,
            m.is_sent,
            m.is_draft,
            NULL::TEXT as body_text,
            NULL::TEXT as body_html_sanitized,
            NULL::TEXT as body_macro,
            m.headers_jsonb,
            m.created_at,
            m.updated_at
        FROM
            email_messages m
        WHERE
            m.thread_id = $1 AND m.link_id = $2
        ORDER BY
            m.internal_date_ts DESC NULLS LAST
`

type GetSimpleMessagesForThreadParams struct {
	ThreadID pgtype.UUID
	LinkID   pgtype.UUID
}

type GetSimpleMessagesForThreadRow struct {
	ID                pgtype.UUID
	ProviderID        pgtype.Text
	GlobalID          pgtype.Text
	LinkID            pgtype.UUID
	ThreadID          pgtype.UUID
	ProviderThreadID  pgtype.Text
	ReplyingToID      pgtype.UUID
	ProviderHistoryID pgtype.Text
	InternalDateTs    pgtype.Timestamptz
	Snippet           pgtype.Text
	SizeEstimate      pgtype.Int8
	Subject           pgtype.Text
	FromName          pgtype.Text
	FromContactID     pgtype.UUID
	SentAt            pgtype.Timestamptz
	HasAttachments    bool
	IsRead            bool
	IsStarred         bool
	IsSent            bool
	IsDraft           bool
	BodyText          pgtype.Text
	BodyHtmlSanitized pgtype.Text
	BodyMacro         pgtype.Text
	HeadersJsonb      []byte
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

func (q *Queries) GetSimpleMessagesForThread(ctx context.Context, arg GetSimpleMessagesForThreadParams) ([]GetSimpleMessagesForThreadRow, error) {
	rows, err := q.db.Query(ctx, getSimpleMessagesForThread, arg.ThreadID, arg.LinkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSimpleMessagesForThreadRow
	for rows.Next() {
		var i GetSimpleMessagesForThreadRow
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.GlobalID,
			&i.LinkID,
			&i.ThreadID,
			&i.ProviderThreadID,
			&i.ReplyingToID,
			&i.ProviderHistoryID,
			&i.InternalDateTs,
			&i.Snippet,
			&i.SizeEstimate,
			&i.Subject,
			&i.FromName,
			&i.FromContactID,
			&i.SentAt,
			&i.HasAttachments,
			&i.IsRead,
			&i.IsStarred,
			&i.IsSent,
			&i.IsDraft,
			&i.BodyText,
			&i.BodyHtmlSanitized,
			&i.BodyMacro,
			&i.HeadersJsonb,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
