// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages_scheduled_get.sql

package emaildb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const fetchScheduledMessagesInBulk = `-- name: FetchScheduledMessagesInBulk :many
SELECT link_id, message_id, send_time, sent, processing, actor_id
        FROM email_scheduled_messages
        WHERE "message_id" = ANY($1::uuid[]) AND sent = false
`

type FetchScheduledMessagesInBulkRow struct {
	LinkID     pgtype.UUID
	MessageID  pgtype.UUID
	SendTime   pgtype.Timestamptz
	Sent       bool
	Processing bool
	ActorID    pgtype.Text
}

func (q *Queries) FetchScheduledMessagesInBulk(ctx context.Context, dollar_1 []pgtype.UUID) ([]FetchScheduledMessagesInBulkRow, error) {
	rows, err := q.db.Query(ctx, fetchScheduledMessagesInBulk, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FetchScheduledMessagesInBulkRow
	for rows.Next() {
		var i FetchScheduledMessagesInBulkRow
		if err := rows.Scan(
			&i.LinkID,
			&i.MessageID,
			&i.SendTime,
			&i.Sent,
			&i.Processing,
			&i.ActorID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAndStartProcessingScheduledMessage = `-- name: GetAndStartProcessingScheduledMessage :one
WITH old AS (
            SELECT link_id, message_id, send_time, sent, processing, actor_id
            FROM email_scheduled_messages
            WHERE email_scheduled_messages.link_id = $1 AND email_scheduled_messages.message_id = $2
        ), updated AS (
            UPDATE email_scheduled_messages
            SET processing = true, updated_at = NOW()
            WHERE email_scheduled_messages.link_id = $1 AND email_scheduled_messages.message_id = $2
        )
        SELECT link_id, message_id, send_time, sent, processing, actor_id
        FROM old
`

type GetAndStartProcessingScheduledMessageParams struct {
	LinkID    pgtype.UUID
	MessageID pgtype.UUID
}

type GetAndStartProcessingScheduledMessageRow struct {
	LinkID     pgtype.UUID
	MessageID  pgtype.UUID
	SendTime   pgtype.Timestamptz
	Sent       bool
	Processing bool
	ActorID    pgtype.Text
}

func (q *Queries) GetAndStartProcessingScheduledMessage(ctx context.Context, arg GetAndStartProcessingScheduledMessageParams) (GetAndStartProcessingScheduledMessageRow, error) {
	row := q.db.QueryRow(ctx, getAndStartProcessingScheduledMessage, arg.LinkID, arg.MessageID)
	var i GetAndStartProcessingScheduledMessageRow
	err := row.Scan(
		&i.LinkID,
		&i.MessageID,
		&i.SendTime,
		&i.Sent,
		&i.Processing,
		&i.ActorID,
	)
	return i, err
}

const getScheduledDbMessagesByLinkId = `-- name: GetScheduledDbMessagesByLinkId :many
SELECT
            m.id,
            m.provider_id,
            m.global_id,
            m.thread_id,
            m.provider_thread_id,
            m.replying_to_id,
            m.link_id,
            m.provider_history_id,
            m.internal_date_ts,
            m.snippet,
            m.size_estimate,
            m.subject,
            m.from_name,
            m.from_contact_id,
            m.sent_at,
            m.has_attachments,
            m.is_read,
            m.is_starred,
            m.is_sent,
            m.is_draft,
            m.body_text,
            m.body_html_sanitized,
            m.body_macro,
            m.headers_jsonb,
            m.created_at,
            m.updated_at
        FROM email_messages m
        JOIN email_scheduled_messages sm ON m.id = sm.message_id
        WHERE m.link_id = $1 AND sm.sent = false
        ORDER BY m.created_at DESC
        LIMIT $2 OFFSET $3
`

type GetScheduledDbMessagesByLinkIdParams struct {
	LinkID pgtype.UUID
	Limit  int32
	Offset int32
}

type GetScheduledDbMessagesByLinkIdRow struct {
	ID                pgtype.UUID
	ProviderID        pgtype.Text
	GlobalID          pgtype.Text
	ThreadID          pgtype.UUID
	ProviderThreadID  pgtype.Text
	ReplyingToID      pgtype.UUID
	LinkID            pgtype.UUID
	ProviderHistoryID pgtype.Text
	InternalDateTs    pgtype.Timestamptz
	Snippet           pgtype.Text
	SizeEstimate      pgtype.Int8
	Subject           pgtype.Text
	FromName          pgtype.Text
	FromContactID     pgtype.UUID
	SentAt            pgtype.Timestamptz
	HasAttachments    bool
	IsRead            bool
	IsStarred         bool
	IsSent            bool
	IsDraft           bool
	BodyText          pgtype.Text
	BodyHtmlSanitized pgtype.Text
	BodyMacro         pgtype.Text
	HeadersJsonb      []byte
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

func (q *Queries) GetScheduledDbMessagesByLinkId(ctx context.Context, arg GetScheduledDbMessagesByLinkIdParams) ([]GetScheduledDbMessagesByLinkIdRow, error) {
	rows, err := q.db.Query(ctx, getScheduledDbMessagesByLinkId, arg.LinkID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetScheduledDbMessagesByLinkIdRow
	for rows.Next() {
		var i GetScheduledDbMessagesByLinkIdRow
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.GlobalID,
			&i.ThreadID,
			&i.ProviderThreadID,
			&i.ReplyingToID,
			&i.LinkID,
			&i.ProviderHistoryID,
			&i.InternalDateTs,
			&i.Snippet,
			&i.SizeEstimate,
			&i.Subject,
			&i.FromName,
			&i.FromContactID,
			&i.SentAt,
			&i.HasAttachments,
			&i.IsRead,
			&i.IsStarred,
			&i.IsSent,
			&i.IsDraft,
			&i.BodyText,
			&i.BodyHtmlSanitized,
			&i.BodyMacro,
			&i.HeadersJsonb,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getScheduledMessage = `-- name: GetScheduledMessage :one
SELECT link_id, message_id, send_time, sent, processing, actor_id
        FROM email_scheduled_messages
        WHERE link_id = $1 AND message_id = $2
`

type GetScheduledMessageParams struct {
	LinkID    pgtype.UUID
	MessageID pgtype.UUID
}

type GetScheduledMessageRow struct {
	LinkID     pgtype.UUID
	MessageID  pgtype.UUID
	SendTime   pgtype.Timestamptz
	Sent       bool
	Processing bool
	ActorID    pgtype.Text
}

func (q *Queries) GetScheduledMessage(ctx context.Context, arg GetScheduledMessageParams) (GetScheduledMessageRow, error) {
	row := q.db.QueryRow(ctx, getScheduledMessage, arg.LinkID, arg.MessageID)
	var i GetScheduledMessageRow
	err := row.Scan(
		&i.LinkID,
		&i.MessageID,
		&i.SendTime,
		&i.Sent,
		&i.Processing,
		&i.ActorID,
	)
	return i, err
}

const getScheduledMessageNoAuth = `-- name: GetScheduledMessageNoAuth :one
SELECT link_id, message_id, send_time, sent, processing, actor_id
        FROM email_scheduled_messages
        WHERE message_id = $1 and sent = false
`

type GetScheduledMessageNoAuthRow struct {
	LinkID     pgtype.UUID
	MessageID  pgtype.UUID
	SendTime   pgtype.Timestamptz
	Sent       bool
	Processing bool
	ActorID    pgtype.Text
}

func (q *Queries) GetScheduledMessageNoAuth(ctx context.Context, messageID pgtype.UUID) (GetScheduledMessageNoAuthRow, error) {
	row := q.db.QueryRow(ctx, getScheduledMessageNoAuth, messageID)
	var i GetScheduledMessageNoAuthRow
	err := row.Scan(
		&i.LinkID,
		&i.MessageID,
		&i.SendTime,
		&i.Sent,
		&i.Processing,
		&i.ActorID,
	)
	return i, err
}
