// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages_delete.sql

package emaildb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteDbMessage = `-- name: DeleteDbMessage :exec
DELETE FROM email_messages WHERE id = $1
`

func (q *Queries) DeleteDbMessage(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDbMessage, id)
	return err
}
