// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages_get.sql

package emaildb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const draftExistsWithId = `-- name: DraftExistsWithId :one
SELECT EXISTS(
                SELECT 1
                FROM email_messages
                WHERE id = $1 AND link_id = $2 AND is_draft = true
            ) as "exists"
`

type DraftExistsWithIdParams struct {
	ID     pgtype.UUID
	LinkID pgtype.UUID
}

func (q *Queries) DraftExistsWithId(ctx context.Context, arg DraftExistsWithIdParams) (bool, error) {
	row := q.db.QueryRow(ctx, draftExistsWithId, arg.ID, arg.LinkID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const fetchMessagesMetadata = `-- name: FetchMessagesMetadata :many
SELECT
            id,
            provider_id,
            global_id,
            thread_id,
            provider_thread_id,
            replying_to_id,
            link_id,
            provider_history_id,
            internal_date_ts,
            snippet,
            size_estimate,
            subject,
            from_name,
            from_contact_id,
            sent_at,
            has_attachments,
            is_read,
            is_starred,
            is_sent,
            is_draft,
            headers_jsonb,
            created_at,
            updated_at,
            -- No body attributes
            NULL::text as "body_text",
            NULL::text as "body_html_sanitized",
            NULL::text as "body_macro"
        FROM email_messages
        WHERE thread_id = $1
        ORDER BY internal_date_ts DESC NULLS LAST
`

type FetchMessagesMetadataRow struct {
	ID                pgtype.UUID
	ProviderID        pgtype.Text
	GlobalID          pgtype.Text
	ThreadID          pgtype.UUID
	ProviderThreadID  pgtype.Text
	ReplyingToID      pgtype.UUID
	LinkID            pgtype.UUID
	ProviderHistoryID pgtype.Text
	InternalDateTs    pgtype.Timestamptz
	Snippet           pgtype.Text
	SizeEstimate      pgtype.Int8
	Subject           pgtype.Text
	FromName          pgtype.Text
	FromContactID     pgtype.UUID
	SentAt            pgtype.Timestamptz
	HasAttachments    bool
	IsRead            bool
	IsStarred         bool
	IsSent            bool
	IsDraft           bool
	HeadersJsonb      []byte
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	BodyText          pgtype.Text
	BodyHtmlSanitized pgtype.Text
	BodyMacro         pgtype.Text
}

func (q *Queries) FetchMessagesMetadata(ctx context.Context, threadID pgtype.UUID) ([]FetchMessagesMetadataRow, error) {
	rows, err := q.db.Query(ctx, fetchMessagesMetadata, threadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FetchMessagesMetadataRow
	for rows.Next() {
		var i FetchMessagesMetadataRow
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.GlobalID,
			&i.ThreadID,
			&i.ProviderThreadID,
			&i.ReplyingToID,
			&i.LinkID,
			&i.ProviderHistoryID,
			&i.InternalDateTs,
			&i.Snippet,
			&i.SizeEstimate,
			&i.Subject,
			&i.FromName,
			&i.FromContactID,
			&i.SentAt,
			&i.HasAttachments,
			&i.IsRead,
			&i.IsStarred,
			&i.IsSent,
			&i.IsDraft,
			&i.HeadersJsonb,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BodyText,
			&i.BodyHtmlSanitized,
			&i.BodyMacro,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fetchMessagesWithLabels = `-- name: FetchMessagesWithLabels :many
SELECT
            id,
            provider_id,
            global_id,
            thread_id,
            provider_thread_id,
            replying_to_id,
            link_id,
            provider_history_id,
            internal_date_ts,
            snippet,
            size_estimate,
            subject,
            from_name,
            from_contact_id,
            sent_at,
            has_attachments,
            is_read,
            is_starred,
            is_sent,
            is_draft,
            headers_jsonb,
            created_at,
            updated_at,
            -- No body attributes
            NULL::text as "body_text",
            NULL::text as "body_html_sanitized",
            NULL::text as "body_macro"
        FROM email_messages
        WHERE thread_id = $1 and link_id = $2
        ORDER BY internal_date_ts DESC NULLS LAST
`

type FetchMessagesWithLabelsParams struct {
	ThreadID pgtype.UUID
	LinkID   pgtype.UUID
}

type FetchMessagesWithLabelsRow struct {
	ID                pgtype.UUID
	ProviderID        pgtype.Text
	GlobalID          pgtype.Text
	ThreadID          pgtype.UUID
	ProviderThreadID  pgtype.Text
	ReplyingToID      pgtype.UUID
	LinkID            pgtype.UUID
	ProviderHistoryID pgtype.Text
	InternalDateTs    pgtype.Timestamptz
	Snippet           pgtype.Text
	SizeEstimate      pgtype.Int8
	Subject           pgtype.Text
	FromName          pgtype.Text
	FromContactID     pgtype.UUID
	SentAt            pgtype.Timestamptz
	HasAttachments    bool
	IsRead            bool
	IsStarred         bool
	IsSent            bool
	IsDraft           bool
	HeadersJsonb      []byte
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	BodyText          pgtype.Text
	BodyHtmlSanitized pgtype.Text
	BodyMacro         pgtype.Text
}

func (q *Queries) FetchMessagesWithLabels(ctx context.Context, arg FetchMessagesWithLabelsParams) ([]FetchMessagesWithLabelsRow, error) {
	rows, err := q.db.Query(ctx, fetchMessagesWithLabels, arg.ThreadID, arg.LinkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FetchMessagesWithLabelsRow
	for rows.Next() {
		var i FetchMessagesWithLabelsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.GlobalID,
			&i.ThreadID,
			&i.ProviderThreadID,
			&i.ReplyingToID,
			&i.LinkID,
			&i.ProviderHistoryID,
			&i.InternalDateTs,
			&i.Snippet,
			&i.SizeEstimate,
			&i.Subject,
			&i.FromName,
			&i.FromContactID,
			&i.SentAt,
			&i.HasAttachments,
			&i.IsRead,
			&i.IsStarred,
			&i.IsSent,
			&i.IsDraft,
			&i.HeadersJsonb,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BodyText,
			&i.BodyHtmlSanitized,
			&i.BodyMacro,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const filterExistingProviderMessageIds = `-- name: FilterExistingProviderMessageIds :many
SELECT provider_id AS "provider_id"
        FROM email_messages
        WHERE link_id = $1 AND "provider_id" = ANY($2::text[])
`

type FilterExistingProviderMessageIdsParams struct {
	LinkID  pgtype.UUID
	Column2 []string
}

func (q *Queries) FilterExistingProviderMessageIds(ctx context.Context, arg FilterExistingProviderMessageIdsParams) ([]pgtype.Text, error) {
	rows, err := q.db.Query(ctx, filterExistingProviderMessageIds, arg.LinkID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Text
	for rows.Next() {
		var provider_id pgtype.Text
		if err := rows.Scan(&provider_id); err != nil {
			return nil, err
		}
		items = append(items, provider_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessageAndThreadIdByProviderId = `-- name: GetMessageAndThreadIdByProviderId :one
SELECT id, thread_id
        FROM email_messages
        WHERE link_id = $1 AND provider_id = $2
        LIMIT 1
`

type GetMessageAndThreadIdByProviderIdParams struct {
	LinkID     pgtype.UUID
	ProviderID pgtype.Text
}

type GetMessageAndThreadIdByProviderIdRow struct {
	ID       pgtype.UUID
	ThreadID pgtype.UUID
}

func (q *Queries) GetMessageAndThreadIdByProviderId(ctx context.Context, arg GetMessageAndThreadIdByProviderIdParams) (GetMessageAndThreadIdByProviderIdRow, error) {
	row := q.db.QueryRow(ctx, getMessageAndThreadIdByProviderId, arg.LinkID, arg.ProviderID)
	var i GetMessageAndThreadIdByProviderIdRow
	err := row.Scan(&i.ID, &i.ThreadID)
	return i, err
}

const getMessageIdByGlobalId = `-- name: GetMessageIdByGlobalId :one
SELECT id
        FROM email_messages
        WHERE link_id = $1 AND global_id = $2
`

type GetMessageIdByGlobalIdParams struct {
	LinkID   pgtype.UUID
	GlobalID pgtype.Text
}

func (q *Queries) GetMessageIdByGlobalId(ctx context.Context, arg GetMessageIdByGlobalIdParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getMessageIdByGlobalId, arg.LinkID, arg.GlobalID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getMessageSenderAndPrettySender = `-- name: GetMessageSenderAndPrettySender :many
SELECT
            m.id as "message_id",
            c.email_address as "sender",
            COALESCE(c.name, c.email_address) as "pretty_sender"
        FROM email_messages m
        LEFT JOIN email_contacts c ON c.id = m.from_contact_id
        WHERE m."id" = ANY($1::uuid[])
        AND m."link_id" = ANY($2::uuid[])
`

type GetMessageSenderAndPrettySenderParams struct {
	Column1 []pgtype.UUID
	Column2 []pgtype.UUID
}

type GetMessageSenderAndPrettySenderRow struct {
	MessageID    pgtype.UUID
	Sender       pgtype.Text
	PrettySender string
}

func (q *Queries) GetMessageSenderAndPrettySender(ctx context.Context, arg GetMessageSenderAndPrettySenderParams) ([]GetMessageSenderAndPrettySenderRow, error) {
	rows, err := q.db.Query(ctx, getMessageSenderAndPrettySender, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMessageSenderAndPrettySenderRow
	for rows.Next() {
		var i GetMessageSenderAndPrettySenderRow
		if err := rows.Scan(&i.MessageID, &i.Sender, &i.PrettySender); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessageThreadingHeaders = `-- name: GetMessageThreadingHeaders :one
SELECT 
          -- Use trim() to remove the leading/trailing angle brackets
          trim(jsonb_path_query_first(headers_jsonb, '$[*] ? (@.name like_regex "message-id" flag "i").value') #>> '{}', '<>') as "message_id",
          -- The references header can have multiple IDs, so we just return it raw
          (jsonb_path_query_first(headers_jsonb, '$[*] ? (@.name like_regex "references" flag "i").value') #>> '{}')::text as "references"
        FROM email_messages
        WHERE id = $1 AND link_id = $2
`

type GetMessageThreadingHeadersParams struct {
	ID     pgtype.UUID
	LinkID pgtype.UUID
}

type GetMessageThreadingHeadersRow struct {
	MessageID  []byte
	References string
}

func (q *Queries) GetMessageThreadingHeaders(ctx context.Context, arg GetMessageThreadingHeadersParams) (GetMessageThreadingHeadersRow, error) {
	row := q.db.QueryRow(ctx, getMessageThreadingHeaders, arg.ID, arg.LinkID)
	var i GetMessageThreadingHeadersRow
	err := row.Scan(&i.MessageID, &i.References)
	return i, err
}

const getMessageToSend = `-- name: GetMessageToSend :one
SELECT
            id,
            provider_id,
            global_id,
            thread_id,
            provider_thread_id,
            replying_to_id,
            link_id,
            provider_history_id,
            internal_date_ts,
            snippet,
            size_estimate,
            subject,
            from_name,
            from_contact_id,
            sent_at,
            has_attachments,
            is_read,
            is_starred,
            is_sent,
            is_draft,
            body_text,
            body_html_sanitized,
            body_macro,
            headers_jsonb,
            created_at,
            updated_at
        FROM email_messages
        WHERE id = $1 and link_id = $2
`

type GetMessageToSendParams struct {
	ID     pgtype.UUID
	LinkID pgtype.UUID
}

type GetMessageToSendRow struct {
	ID                pgtype.UUID
	ProviderID        pgtype.Text
	GlobalID          pgtype.Text
	ThreadID          pgtype.UUID
	ProviderThreadID  pgtype.Text
	ReplyingToID      pgtype.UUID
	LinkID            pgtype.UUID
	ProviderHistoryID pgtype.Text
	InternalDateTs    pgtype.Timestamptz
	Snippet           pgtype.Text
	SizeEstimate      pgtype.Int8
	Subject           pgtype.Text
	FromName          pgtype.Text
	FromContactID     pgtype.UUID
	SentAt            pgtype.Timestamptz
	HasAttachments    bool
	IsRead            bool
	IsStarred         bool
	IsSent            bool
	IsDraft           bool
	BodyText          pgtype.Text
	BodyHtmlSanitized pgtype.Text
	BodyMacro         pgtype.Text
	HeadersJsonb      []byte
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

func (q *Queries) GetMessageToSend(ctx context.Context, arg GetMessageToSendParams) (GetMessageToSendRow, error) {
	row := q.db.QueryRow(ctx, getMessageToSend, arg.ID, arg.LinkID)
	var i GetMessageToSendRow
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.GlobalID,
		&i.ThreadID,
		&i.ProviderThreadID,
		&i.ReplyingToID,
		&i.LinkID,
		&i.ProviderHistoryID,
		&i.InternalDateTs,
		&i.Snippet,
		&i.SizeEstimate,
		&i.Subject,
		&i.FromName,
		&i.FromContactID,
		&i.SentAt,
		&i.HasAttachments,
		&i.IsRead,
		&i.IsStarred,
		&i.IsSent,
		&i.IsDraft,
		&i.BodyText,
		&i.BodyHtmlSanitized,
		&i.BodyMacro,
		&i.HeadersJsonb,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const messageExistsByProviderId = `-- name: MessageExistsByProviderId :one
SELECT EXISTS(
            SELECT 1
            FROM email_messages
            WHERE provider_id = $1 AND link_id = $2
        ) AS "exists"
`

type MessageExistsByProviderIdParams struct {
	ProviderID pgtype.Text
	LinkID     pgtype.UUID
}

func (q *Queries) MessageExistsByProviderId(ctx context.Context, arg MessageExistsByProviderIdParams) (bool, error) {
	row := q.db.QueryRow(ctx, messageExistsByProviderId, arg.ProviderID, arg.LinkID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
