// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package emaildb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const fetchSettings = `-- name: FetchSettings :one
SELECT link_id, signature_on_replies_forwards, signature
        FROM email_settings
        WHERE link_id = $1
`

type FetchSettingsRow struct {
	LinkID                     pgtype.UUID
	SignatureOnRepliesForwards bool
	Signature                  pgtype.Text
}

func (q *Queries) FetchSettings(ctx context.Context, linkID pgtype.UUID) (FetchSettingsRow, error) {
	row := q.db.QueryRow(ctx, fetchSettings, linkID)
	var i FetchSettingsRow
	err := row.Scan(&i.LinkID, &i.SignatureOnRepliesForwards, &i.Signature)
	return i, err
}

const patchSettings = `-- name: PatchSettings :one
INSERT INTO email_settings (link_id, signature_on_replies_forwards, signature)
        VALUES ($1, COALESCE($2::bool, FALSE), $3)
        ON CONFLICT (link_id)
        DO UPDATE SET
            signature_on_replies_forwards = COALESCE($2::bool, email_settings.signature_on_replies_forwards),
            signature = COALESCE($3::text, email_settings.signature),
            updated_at = NOW()
        RETURNING link_id, signature_on_replies_forwards, signature
`

type PatchSettingsParams struct {
	LinkID    pgtype.UUID
	Column2   bool
	Signature pgtype.Text
}

type PatchSettingsRow struct {
	LinkID                     pgtype.UUID
	SignatureOnRepliesForwards bool
	Signature                  pgtype.Text
}

func (q *Queries) PatchSettings(ctx context.Context, arg PatchSettingsParams) (PatchSettingsRow, error) {
	row := q.db.QueryRow(ctx, patchSettings, arg.LinkID, arg.Column2, arg.Signature)
	var i PatchSettingsRow
	err := row.Scan(&i.LinkID, &i.SignatureOnRepliesForwards, &i.Signature)
	return i, err
}
