// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sfs_mappings.sql

package emaildb

import (
	"context"
)

const fetchSfsMapping = `-- name: FetchSfsMapping :one
SELECT destination
        FROM email_sfs_mappings
        WHERE source = $1
`

func (q *Queries) FetchSfsMapping(ctx context.Context, source string) (string, error) {
	row := q.db.QueryRow(ctx, fetchSfsMapping, source)
	var destination string
	err := row.Scan(&destination)
	return destination, err
}

const fetchSfsMappings = `-- name: FetchSfsMappings :many
SELECT source, destination
        FROM email_sfs_mappings
        WHERE "source" = ANY($1::text[])
`

type FetchSfsMappingsRow struct {
	Source      string
	Destination string
}

func (q *Queries) FetchSfsMappings(ctx context.Context, dollar_1 []string) ([]FetchSfsMappingsRow, error) {
	rows, err := q.db.Query(ctx, fetchSfsMappings, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FetchSfsMappingsRow
	for rows.Next() {
		var i FetchSfsMappingsRow
		if err := rows.Scan(&i.Source, &i.Destination); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertSfsMappings = `-- name: InsertSfsMappings :exec
INSERT INTO email_sfs_mappings (source, destination)
        SELECT unnest($1::text[]), unnest($2::text[])
        ON CONFLICT (source) DO NOTHING
`

type InsertSfsMappingsParams struct {
	Column1 []string
	Column2 []string
}

func (q *Queries) InsertSfsMappings(ctx context.Context, arg InsertSfsMappingsParams) error {
	_, err := q.db.Exec(ctx, insertSfsMappings, arg.Column1, arg.Column2)
	return err
}
