// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sync_tokens_get.sql

package emaildb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSyncTokensByLinkId = `-- name: GetSyncTokensByLinkId :one
SELECT link_id, contacts_sync_token, other_contacts_sync_token
        FROM email_sync_tokens
        WHERE link_id = $1
`

func (q *Queries) GetSyncTokensByLinkId(ctx context.Context, linkID pgtype.UUID) (EmailSyncToken, error) {
	row := q.db.QueryRow(ctx, getSyncTokensByLinkId, linkID)
	var i EmailSyncToken
	err := row.Scan(&i.LinkID, &i.ContactsSyncToken, &i.OtherContactsSyncToken)
	return i, err
}
