// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: threads_get.sql

package emaildb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAllThreadIdsPaginated = `-- name: GetAllThreadIdsPaginated :many
SELECT
            id as "thread_id"
        FROM
            email_threads
        ORDER BY
            created_at ASC
        LIMIT $1
        OFFSET $2
`

type GetAllThreadIdsPaginatedParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) GetAllThreadIdsPaginated(ctx context.Context, arg GetAllThreadIdsPaginatedParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, getAllThreadIdsPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var thread_id pgtype.UUID
		if err := rows.Scan(&thread_id); err != nil {
			return nil, err
		}
		items = append(items, thread_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestThreadIdsPaginated = `-- name: GetLatestThreadIdsPaginated :many
SELECT t.id
        FROM email_threads t
        JOIN email_links l ON t.link_id = l.id
        WHERE l.fusionauth_user_id = $1
        ORDER BY t.latest_inbound_message_ts DESC NULLS LAST
        LIMIT $2 OFFSET $3
`

type GetLatestThreadIdsPaginatedParams struct {
	FusionauthUserID string
	Limit            int32
	Offset           int32
}

func (q *Queries) GetLatestThreadIdsPaginated(ctx context.Context, arg GetLatestThreadIdsPaginatedParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, getLatestThreadIdsPaginated, arg.FusionauthUserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMacroIdFromThreadId = `-- name: GetMacroIdFromThreadId :one
SELECT l.macro_id
        FROM email_threads t
        JOIN email_links l ON t.link_id = l.id
        WHERE t.id = $1
`

func (q *Queries) GetMacroIdFromThreadId(ctx context.Context, id pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getMacroIdFromThreadId, id)
	var macro_id string
	err := row.Scan(&macro_id)
	return macro_id, err
}

const getOutboundThreadsByThreadIds = `-- name: GetOutboundThreadsByThreadIds :many
SELECT l.macro_id, t.id as thread_id
        FROM (SELECT unnest($1::text[]) AS macro_id, unnest($2::uuid[]) AS thread_id) AS inp
        JOIN email_links l ON l.macro_id = inp.macro_id
        JOIN email_threads t ON t.link_id = l.id AND t.id = inp.thread_id
        WHERE t.latest_outbound_message_ts IS NOT NULL
`

type GetOutboundThreadsByThreadIdsParams struct {
	Column1 []string
	Column2 []pgtype.UUID
}

type GetOutboundThreadsByThreadIdsRow struct {
	MacroID  string
	ThreadID pgtype.UUID
}

func (q *Queries) GetOutboundThreadsByThreadIds(ctx context.Context, arg GetOutboundThreadsByThreadIdsParams) ([]GetOutboundThreadsByThreadIdsRow, error) {
	rows, err := q.db.Query(ctx, getOutboundThreadsByThreadIds, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOutboundThreadsByThreadIdsRow
	for rows.Next() {
		var i GetOutboundThreadsByThreadIdsRow
		if err := rows.Scan(&i.MacroID, &i.ThreadID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPaginatedThreadIdsWithMacroUserId = `-- name: GetPaginatedThreadIdsWithMacroUserId :many
SELECT t.id, l.macro_id
        FROM email_threads t
        JOIN email_links l ON t.link_id = l.id
        ORDER BY t.latest_inbound_message_ts DESC NULLS LAST
        LIMIT $1 OFFSET $2
`

type GetPaginatedThreadIdsWithMacroUserIdParams struct {
	Limit  int32
	Offset int32
}

type GetPaginatedThreadIdsWithMacroUserIdRow struct {
	ID      pgtype.UUID
	MacroID string
}

func (q *Queries) GetPaginatedThreadIdsWithMacroUserId(ctx context.Context, arg GetPaginatedThreadIdsWithMacroUserIdParams) ([]GetPaginatedThreadIdsWithMacroUserIdRow, error) {
	rows, err := q.db.Query(ctx, getPaginatedThreadIdsWithMacroUserId, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPaginatedThreadIdsWithMacroUserIdRow
	for rows.Next() {
		var i GetPaginatedThreadIdsWithMacroUserIdRow
		if err := rows.Scan(&i.ID, &i.MacroID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPaginatedThreadIdsWithMacroUserIdSince = `-- name: GetPaginatedThreadIdsWithMacroUserIdSince :many
SELECT t.id, l.macro_id
        FROM email_threads t
        JOIN email_links l ON t.link_id = l.id
        WHERE t.updated_at >= $3
        ORDER BY t.latest_inbound_message_ts DESC NULLS LAST
        LIMIT $1 OFFSET $2
`

type GetPaginatedThreadIdsWithMacroUserIdSinceParams struct {
	Limit     int32
	Offset    int32
	UpdatedAt pgtype.Timestamptz
}

type GetPaginatedThreadIdsWithMacroUserIdSinceRow struct {
	ID      pgtype.UUID
	MacroID string
}

func (q *Queries) GetPaginatedThreadIdsWithMacroUserIdSince(ctx context.Context, arg GetPaginatedThreadIdsWithMacroUserIdSinceParams) ([]GetPaginatedThreadIdsWithMacroUserIdSinceRow, error) {
	rows, err := q.db.Query(ctx, getPaginatedThreadIdsWithMacroUserIdSince, arg.Limit, arg.Offset, arg.UpdatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPaginatedThreadIdsWithMacroUserIdSinceRow
	for rows.Next() {
		var i GetPaginatedThreadIdsWithMacroUserIdSinceRow
		if err := rows.Scan(&i.ID, &i.MacroID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProviderIdByLinkAndThreadId = `-- name: GetProviderIdByLinkAndThreadId :one
SELECT provider_id
        FROM email_threads
        WHERE link_id = $1 AND id = $2
`

type GetProviderIdByLinkAndThreadIdParams struct {
	LinkID pgtype.UUID
	ID     pgtype.UUID
}

func (q *Queries) GetProviderIdByLinkAndThreadId(ctx context.Context, arg GetProviderIdByLinkAndThreadIdParams) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getProviderIdByLinkAndThreadId, arg.LinkID, arg.ID)
	var provider_id pgtype.Text
	err := row.Scan(&provider_id)
	return provider_id, err
}

const getThreadByIdAndLinkId = `-- name: GetThreadByIdAndLinkId :one
SELECT t.id, t.provider_id, t.link_id, t.inbox_visible, t.is_read,
               t.latest_inbound_message_ts, t.latest_outbound_message_ts,
               t.latest_non_spam_message_ts, t.created_at, t.updated_at
        FROM email_threads t
        WHERE t.id = $1 AND t.link_id = $2
`

type GetThreadByIdAndLinkIdParams struct {
	ID     pgtype.UUID
	LinkID pgtype.UUID
}

type GetThreadByIdAndLinkIdRow struct {
	ID                      pgtype.UUID
	ProviderID              pgtype.Text
	LinkID                  pgtype.UUID
	InboxVisible            bool
	IsRead                  bool
	LatestInboundMessageTs  pgtype.Timestamptz
	LatestOutboundMessageTs pgtype.Timestamptz
	LatestNonSpamMessageTs  pgtype.Timestamptz
	CreatedAt               pgtype.Timestamptz
	UpdatedAt               pgtype.Timestamptz
}

func (q *Queries) GetThreadByIdAndLinkId(ctx context.Context, arg GetThreadByIdAndLinkIdParams) (GetThreadByIdAndLinkIdRow, error) {
	row := q.db.QueryRow(ctx, getThreadByIdAndLinkId, arg.ID, arg.LinkID)
	var i GetThreadByIdAndLinkIdRow
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.LinkID,
		&i.InboxVisible,
		&i.IsRead,
		&i.LatestInboundMessageTs,
		&i.LatestOutboundMessageTs,
		&i.LatestNonSpamMessageTs,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getThreadIdsByContactIds = `-- name: GetThreadIdsByContactIds :many
SELECT DISTINCT m.thread_id as "thread_id"
        FROM email_messages m
        WHERE m."from_contact_id" = ANY($1::uuid[])
        UNION
        SELECT DISTINCT m.thread_id as "thread_id"
        FROM email_messages m
        JOIN email_message_recipients mr ON m.id = mr.message_id
        WHERE mr."contact_id" = ANY($1::uuid[])
`

func (q *Queries) GetThreadIdsByContactIds(ctx context.Context, dollar_1 []pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, getThreadIdsByContactIds, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var thread_id pgtype.UUID
		if err := rows.Scan(&thread_id); err != nil {
			return nil, err
		}
		items = append(items, thread_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getThreadIdsWithMacroUserIdByIds = `-- name: GetThreadIdsWithMacroUserIdByIds :many
SELECT t.id, l.macro_id
        FROM email_threads t
        JOIN email_links l ON t.link_id = l.id
        WHERE t."id" = ANY($1::uuid[])
`

type GetThreadIdsWithMacroUserIdByIdsRow struct {
	ID      pgtype.UUID
	MacroID string
}

func (q *Queries) GetThreadIdsWithMacroUserIdByIds(ctx context.Context, dollar_1 []pgtype.UUID) ([]GetThreadIdsWithMacroUserIdByIdsRow, error) {
	rows, err := q.db.Query(ctx, getThreadIdsWithMacroUserIdByIds, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetThreadIdsWithMacroUserIdByIdsRow
	for rows.Next() {
		var i GetThreadIdsWithMacroUserIdByIdsRow
		if err := rows.Scan(&i.ID, &i.MacroID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getThreadsByLinkIdAndProviderIds = `-- name: GetThreadsByLinkIdAndProviderIds :many
SELECT id, provider_id as "provider_id"
        FROM email_threads
        WHERE link_id = $1
        AND "provider_id" = ANY($2::text[])
`

type GetThreadsByLinkIdAndProviderIdsParams struct {
	LinkID  pgtype.UUID
	Column2 []string
}

type GetThreadsByLinkIdAndProviderIdsRow struct {
	ID         pgtype.UUID
	ProviderID pgtype.Text
}

func (q *Queries) GetThreadsByLinkIdAndProviderIds(ctx context.Context, arg GetThreadsByLinkIdAndProviderIdsParams) ([]GetThreadsByLinkIdAndProviderIdsRow, error) {
	rows, err := q.db.Query(ctx, getThreadsByLinkIdAndProviderIds, arg.LinkID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetThreadsByLinkIdAndProviderIdsRow
	for rows.Next() {
		var i GetThreadsByLinkIdAndProviderIdsRow
		if err := rows.Scan(&i.ID, &i.ProviderID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getThreadsByUserWithOutbound = `-- name: GetThreadsByUserWithOutbound :many
SELECT t.id as thread_id
        FROM email_threads t
        JOIN email_links l ON t.link_id = l.id
        WHERE l.macro_id = $1
          AND t.latest_outbound_message_ts IS NOT NULL
        ORDER BY t.latest_outbound_message_ts DESC
        LIMIT $2 OFFSET $3
`

type GetThreadsByUserWithOutboundParams struct {
	MacroID string
	Limit   int32
	Offset  int32
}

func (q *Queries) GetThreadsByUserWithOutbound(ctx context.Context, arg GetThreadsByUserWithOutboundParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, getThreadsByUserWithOutbound, arg.MacroID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var thread_id pgtype.UUID
		if err := rows.Scan(&thread_id); err != nil {
			return nil, err
		}
		items = append(items, thread_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
