-- Queries ported from crates/notification_db_client/src/device.rs

-- name: GetDeviceEndpoint :one
-- Rust used fetch_optional: callers must treat pgx.ErrNoRows as "no device".
SELECT d.device_endpoint
FROM notification_user_device_registration d
WHERE d.device_token = $1
LIMIT 1;

-- name: UpsertUserDevice :exec
-- id is a uuid v7 generated by the caller (as in the Rust code).
INSERT INTO notification_user_device_registration (id, user_id, device_token, device_endpoint, device_type)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (device_endpoint) DO UPDATE SET user_id = $2, device_token = $3, device_type = $5, updated_at = NOW();

-- name: GetUsersDeviceEndpoints :many
SELECT d.device_endpoint,
       d.user_id,
       d.device_type
FROM notification_user_device_registration d
WHERE d.user_id = ANY(sqlc.arg(user_ids)::text[]);

-- name: GetUserDeviceEndpoints :many
SELECT d.device_endpoint
FROM notification_user_device_registration d
WHERE d.user_id = $1;

-- name: DeleteUserDeviceToken :one
DELETE FROM notification_user_device_registration
WHERE device_token = $1 AND device_type = $2
RETURNING device_endpoint;

-- name: DeleteUserDeviceByEndpoint :exec
DELETE FROM notification_user_device_registration
WHERE device_endpoint = $1;
